// ---------------------------------------------------------------------------
// AUTO-GENERATED by gen/vc3d_gen_ecc.py -- DO NOT HAND EDIT.
// SECDED (Hsiao) codec for 128 data bits + 9 check bits.
// Code distance 4: corrects 1 bit, detects 2 bits, detects all odd-weight
// error patterns.  Row loads (XOR-tree fan-in per check bit): [53, 53, 53, 52, 53, 52, 52, 52, 52]
// Max fan-in 53  ->  balanced XOR depth ceil(log2(max)) = 6.
// ---------------------------------------------------------------------------
`timescale 1ns/1ps

module vc3d_secded_enc_128 (
    input  wire [127:0] data_i,
    output wire [8:0] check_o
);

    // check bit 0: 53 taps
    assign check_o[0] =
          data_i[0] ^
        data_i[3] ^
        data_i[5] ^
        data_i[9] ^
        data_i[11] ^
        data_i[15] ^
        data_i[17] ^
        data_i[21] ^
        data_i[24] ^
        data_i[26] ^
        data_i[29] ^
        data_i[32] ^
        data_i[35] ^
        data_i[39] ^
        data_i[42] ^
        data_i[44] ^
        data_i[48] ^
        data_i[51] ^
        data_i[54] ^
        data_i[57] ^
        data_i[60] ^
        data_i[63] ^
        data_i[65] ^
        data_i[68] ^
        data_i[71] ^
        data_i[75] ^
        data_i[78] ^
        data_i[80] ^
        data_i[84] ^
        data_i[85] ^
        data_i[87] ^
        data_i[89] ^
        data_i[91] ^
        data_i[93] ^
        data_i[94] ^
        data_i[96] ^
        data_i[98] ^
        data_i[100] ^
        data_i[101] ^
        data_i[104] ^
        data_i[105] ^
        data_i[107] ^
        data_i[109] ^
        data_i[111] ^
        data_i[112] ^
        data_i[114] ^
        data_i[116] ^
        data_i[118] ^
        data_i[119] ^
        data_i[122] ^
        data_i[123] ^
        data_i[125] ^
        data_i[127];

    // check bit 1: 53 taps
    assign check_o[1] =
          data_i[0] ^
        data_i[3] ^
        data_i[6] ^
        data_i[9] ^
        data_i[12] ^
        data_i[15] ^
        data_i[18] ^
        data_i[21] ^
        data_i[24] ^
        data_i[27] ^
        data_i[30] ^
        data_i[33] ^
        data_i[36] ^
        data_i[38] ^
        data_i[42] ^
        data_i[45] ^
        data_i[49] ^
        data_i[50] ^
        data_i[55] ^
        data_i[56] ^
        data_i[61] ^
        data_i[62] ^
        data_i[66] ^
        data_i[69] ^
        data_i[72] ^
        data_i[76] ^
        data_i[79] ^
        data_i[81] ^
        data_i[84] ^
        data_i[86] ^
        data_i[87] ^
        data_i[89] ^
        data_i[91] ^
        data_i[93] ^
        data_i[95] ^
        data_i[96] ^
        data_i[98] ^
        data_i[100] ^
        data_i[102] ^
        data_i[103] ^
        data_i[106] ^
        data_i[107] ^
        data_i[109] ^
        data_i[111] ^
        data_i[113] ^
        data_i[114] ^
        data_i[116] ^
        data_i[118] ^
        data_i[120] ^
        data_i[121] ^
        data_i[124] ^
        data_i[125] ^
        data_i[127];

    // check bit 2: 53 taps
    assign check_o[2] =
          data_i[0] ^
        data_i[4] ^
        data_i[6] ^
        data_i[10] ^
        data_i[12] ^
        data_i[16] ^
        data_i[18] ^
        data_i[22] ^
        data_i[25] ^
        data_i[28] ^
        data_i[31] ^
        data_i[34] ^
        data_i[37] ^
        data_i[39] ^
        data_i[43] ^
        data_i[46] ^
        data_i[48] ^
        data_i[51] ^
        data_i[54] ^
        data_i[58] ^
        data_i[60] ^
        data_i[63] ^
        data_i[67] ^
        data_i[69] ^
        data_i[72] ^
        data_i[77] ^
        data_i[81] ^
        data_i[82] ^
        data_i[84] ^
        data_i[86] ^
        data_i[88] ^
        data_i[89] ^
        data_i[91] ^
        data_i[93] ^
        data_i[95] ^
        data_i[97] ^
        data_i[98] ^
        data_i[100] ^
        data_i[102] ^
        data_i[104] ^
        data_i[105] ^
        data_i[108] ^
        data_i[109] ^
        data_i[111] ^
        data_i[113] ^
        data_i[115] ^
        data_i[116] ^
        data_i[118] ^
        data_i[120] ^
        data_i[122] ^
        data_i[123] ^
        data_i[126] ^
        data_i[127];

    // check bit 3: 52 taps
    assign check_o[3] =
          data_i[1] ^
        data_i[3] ^
        data_i[7] ^
        data_i[10] ^
        data_i[13] ^
        data_i[16] ^
        data_i[19] ^
        data_i[22] ^
        data_i[25] ^
        data_i[27] ^
        data_i[31] ^
        data_i[33] ^
        data_i[36] ^
        data_i[40] ^
        data_i[44] ^
        data_i[47] ^
        data_i[48] ^
        data_i[52] ^
        data_i[55] ^
        data_i[57] ^
        data_i[61] ^
        data_i[64] ^
        data_i[68] ^
        data_i[70] ^
        data_i[73] ^
        data_i[75] ^
        data_i[78] ^
        data_i[81] ^
        data_i[84] ^
        data_i[86] ^
        data_i[88] ^
        data_i[90] ^
        data_i[91] ^
        data_i[93] ^
        data_i[95] ^
        data_i[97] ^
        data_i[99] ^
        data_i[100] ^
        data_i[102] ^
        data_i[104] ^
        data_i[106] ^
        data_i[107] ^
        data_i[110] ^
        data_i[111] ^
        data_i[113] ^
        data_i[115] ^
        data_i[117] ^
        data_i[119] ^
        data_i[120] ^
        data_i[122] ^
        data_i[124] ^
        data_i[125];

    // check bit 4: 53 taps
    assign check_o[4] =
          data_i[1] ^
        data_i[4] ^
        data_i[7] ^
        data_i[9] ^
        data_i[13] ^
        data_i[16] ^
        data_i[19] ^
        data_i[23] ^
        data_i[26] ^
        data_i[28] ^
        data_i[30] ^
        data_i[34] ^
        data_i[37] ^
        data_i[41] ^
        data_i[44] ^
        data_i[45] ^
        data_i[49] ^
        data_i[53] ^
        data_i[54] ^
        data_i[59] ^
        data_i[61] ^
        data_i[65] ^
        data_i[69] ^
        data_i[71] ^
        data_i[74] ^
        data_i[76] ^
        data_i[80] ^
        data_i[83] ^
        data_i[84] ^
        data_i[86] ^
        data_i[88] ^
        data_i[90] ^
        data_i[92] ^
        data_i[94] ^
        data_i[95] ^
        data_i[97] ^
        data_i[99] ^
        data_i[101] ^
        data_i[102] ^
        data_i[104] ^
        data_i[106] ^
        data_i[108] ^
        data_i[109] ^
        data_i[112] ^
        data_i[113] ^
        data_i[115] ^
        data_i[117] ^
        data_i[118] ^
        data_i[121] ^
        data_i[122] ^
        data_i[124] ^
        data_i[126] ^
        data_i[127];

    // check bit 5: 52 taps
    assign check_o[5] =
          data_i[1] ^
        data_i[4] ^
        data_i[8] ^
        data_i[10] ^
        data_i[14] ^
        data_i[15] ^
        data_i[20] ^
        data_i[23] ^
        data_i[26] ^
        data_i[29] ^
        data_i[32] ^
        data_i[35] ^
        data_i[38] ^
        data_i[40] ^
        data_i[43] ^
        data_i[46] ^
        data_i[49] ^
        data_i[52] ^
        data_i[55] ^
        data_i[58] ^
        data_i[60] ^
        data_i[64] ^
        data_i[66] ^
        data_i[72] ^
        data_i[74] ^
        data_i[75] ^
        data_i[79] ^
        data_i[83] ^
        data_i[85] ^
        data_i[86] ^
        data_i[88] ^
        data_i[90] ^
        data_i[92] ^
        data_i[93] ^
        data_i[96] ^
        data_i[97] ^
        data_i[99] ^
        data_i[101] ^
        data_i[103] ^
        data_i[104] ^
        data_i[106] ^
        data_i[108] ^
        data_i[110] ^
        data_i[112] ^
        data_i[114] ^
        data_i[115] ^
        data_i[117] ^
        data_i[119] ^
        data_i[120] ^
        data_i[123] ^
        data_i[124] ^
        data_i[126];

    // check bit 6: 52 taps
    assign check_o[6] =
          data_i[2] ^
        data_i[5] ^
        data_i[7] ^
        data_i[11] ^
        data_i[14] ^
        data_i[18] ^
        data_i[20] ^
        data_i[21] ^
        data_i[25] ^
        data_i[28] ^
        data_i[32] ^
        data_i[36] ^
        data_i[38] ^
        data_i[40] ^
        data_i[43] ^
        data_i[47] ^
        data_i[50] ^
        data_i[53] ^
        data_i[56] ^
        data_i[59] ^
        data_i[63] ^
        data_i[65] ^
        data_i[67] ^
        data_i[70] ^
        data_i[74] ^
        data_i[76] ^
        data_i[78] ^
        data_i[82] ^
        data_i[85] ^
        data_i[87] ^
        data_i[88] ^
        data_i[90] ^
        data_i[92] ^
        data_i[94] ^
        data_i[95] ^
        data_i[98] ^
        data_i[99] ^
        data_i[101] ^
        data_i[103] ^
        data_i[105] ^
        data_i[106] ^
        data_i[108] ^
        data_i[110] ^
        data_i[111] ^
        data_i[114] ^
        data_i[116] ^
        data_i[118] ^
        data_i[119] ^
        data_i[121] ^
        data_i[122] ^
        data_i[125] ^
        data_i[126];

    // check bit 7: 52 taps
    assign check_o[7] =
          data_i[2] ^
        data_i[5] ^
        data_i[8] ^
        data_i[12] ^
        data_i[13] ^
        data_i[17] ^
        data_i[20] ^
        data_i[22] ^
        data_i[24] ^
        data_i[29] ^
        data_i[33] ^
        data_i[34] ^
        data_i[39] ^
        data_i[41] ^
        data_i[45] ^
        data_i[46] ^
        data_i[50] ^
        data_i[52] ^
        data_i[57] ^
        data_i[59] ^
        data_i[62] ^
        data_i[66] ^
        data_i[67] ^
        data_i[70] ^
        data_i[73] ^
        data_i[77] ^
        data_i[80] ^
        data_i[83] ^
        data_i[85] ^
        data_i[87] ^
        data_i[89] ^
        data_i[90] ^
        data_i[92] ^
        data_i[94] ^
        data_i[96] ^
        data_i[97] ^
        data_i[100] ^
        data_i[101] ^
        data_i[103] ^
        data_i[105] ^
        data_i[107] ^
        data_i[108] ^
        data_i[110] ^
        data_i[112] ^
        data_i[113] ^
        data_i[116] ^
        data_i[117] ^
        data_i[119] ^
        data_i[121] ^
        data_i[123] ^
        data_i[124] ^
        data_i[127];

    // check bit 8: 52 taps
    assign check_o[8] =
          data_i[2] ^
        data_i[6] ^
        data_i[8] ^
        data_i[11] ^
        data_i[14] ^
        data_i[17] ^
        data_i[19] ^
        data_i[23] ^
        data_i[27] ^
        data_i[30] ^
        data_i[31] ^
        data_i[35] ^
        data_i[37] ^
        data_i[41] ^
        data_i[42] ^
        data_i[47] ^
        data_i[51] ^
        data_i[53] ^
        data_i[56] ^
        data_i[58] ^
        data_i[62] ^
        data_i[64] ^
        data_i[68] ^
        data_i[71] ^
        data_i[73] ^
        data_i[77] ^
        data_i[79] ^
        data_i[82] ^
        data_i[85] ^
        data_i[87] ^
        data_i[89] ^
        data_i[91] ^
        data_i[92] ^
        data_i[94] ^
        data_i[96] ^
        data_i[98] ^
        data_i[99] ^
        data_i[102] ^
        data_i[103] ^
        data_i[105] ^
        data_i[107] ^
        data_i[109] ^
        data_i[110] ^
        data_i[112] ^
        data_i[114] ^
        data_i[115] ^
        data_i[117] ^
        data_i[120] ^
        data_i[121] ^
        data_i[123] ^
        data_i[125] ^
        data_i[126];

endmodule

module vc3d_secded_dec_128 (
    input  wire [127:0] data_i,
    input  wire [8:0] check_i,
    input  wire poison_i,
    output wire [127:0] data_o,
    output wire [8:0] syndrome_o,
    output wire ce_o,           // corrected single-bit error
    output wire ue_o,           // uncorrectable (double bit) error
    output wire ce_in_check_o,  // the corrected bit was a check bit
    output wire poison_o
);

    wire [8:0] syndrome;
    assign syndrome[0] = check_i[0]
        ^ data_i[0]
        ^ data_i[3]
        ^ data_i[5]
        ^ data_i[9]
        ^ data_i[11]
        ^ data_i[15]
        ^ data_i[17]
        ^ data_i[21]
        ^ data_i[24]
        ^ data_i[26]
        ^ data_i[29]
        ^ data_i[32]
        ^ data_i[35]
        ^ data_i[39]
        ^ data_i[42]
        ^ data_i[44]
        ^ data_i[48]
        ^ data_i[51]
        ^ data_i[54]
        ^ data_i[57]
        ^ data_i[60]
        ^ data_i[63]
        ^ data_i[65]
        ^ data_i[68]
        ^ data_i[71]
        ^ data_i[75]
        ^ data_i[78]
        ^ data_i[80]
        ^ data_i[84]
        ^ data_i[85]
        ^ data_i[87]
        ^ data_i[89]
        ^ data_i[91]
        ^ data_i[93]
        ^ data_i[94]
        ^ data_i[96]
        ^ data_i[98]
        ^ data_i[100]
        ^ data_i[101]
        ^ data_i[104]
        ^ data_i[105]
        ^ data_i[107]
        ^ data_i[109]
        ^ data_i[111]
        ^ data_i[112]
        ^ data_i[114]
        ^ data_i[116]
        ^ data_i[118]
        ^ data_i[119]
        ^ data_i[122]
        ^ data_i[123]
        ^ data_i[125]
        ^ data_i[127]
        ;
    assign syndrome[1] = check_i[1]
        ^ data_i[0]
        ^ data_i[3]
        ^ data_i[6]
        ^ data_i[9]
        ^ data_i[12]
        ^ data_i[15]
        ^ data_i[18]
        ^ data_i[21]
        ^ data_i[24]
        ^ data_i[27]
        ^ data_i[30]
        ^ data_i[33]
        ^ data_i[36]
        ^ data_i[38]
        ^ data_i[42]
        ^ data_i[45]
        ^ data_i[49]
        ^ data_i[50]
        ^ data_i[55]
        ^ data_i[56]
        ^ data_i[61]
        ^ data_i[62]
        ^ data_i[66]
        ^ data_i[69]
        ^ data_i[72]
        ^ data_i[76]
        ^ data_i[79]
        ^ data_i[81]
        ^ data_i[84]
        ^ data_i[86]
        ^ data_i[87]
        ^ data_i[89]
        ^ data_i[91]
        ^ data_i[93]
        ^ data_i[95]
        ^ data_i[96]
        ^ data_i[98]
        ^ data_i[100]
        ^ data_i[102]
        ^ data_i[103]
        ^ data_i[106]
        ^ data_i[107]
        ^ data_i[109]
        ^ data_i[111]
        ^ data_i[113]
        ^ data_i[114]
        ^ data_i[116]
        ^ data_i[118]
        ^ data_i[120]
        ^ data_i[121]
        ^ data_i[124]
        ^ data_i[125]
        ^ data_i[127]
        ;
    assign syndrome[2] = check_i[2]
        ^ data_i[0]
        ^ data_i[4]
        ^ data_i[6]
        ^ data_i[10]
        ^ data_i[12]
        ^ data_i[16]
        ^ data_i[18]
        ^ data_i[22]
        ^ data_i[25]
        ^ data_i[28]
        ^ data_i[31]
        ^ data_i[34]
        ^ data_i[37]
        ^ data_i[39]
        ^ data_i[43]
        ^ data_i[46]
        ^ data_i[48]
        ^ data_i[51]
        ^ data_i[54]
        ^ data_i[58]
        ^ data_i[60]
        ^ data_i[63]
        ^ data_i[67]
        ^ data_i[69]
        ^ data_i[72]
        ^ data_i[77]
        ^ data_i[81]
        ^ data_i[82]
        ^ data_i[84]
        ^ data_i[86]
        ^ data_i[88]
        ^ data_i[89]
        ^ data_i[91]
        ^ data_i[93]
        ^ data_i[95]
        ^ data_i[97]
        ^ data_i[98]
        ^ data_i[100]
        ^ data_i[102]
        ^ data_i[104]
        ^ data_i[105]
        ^ data_i[108]
        ^ data_i[109]
        ^ data_i[111]
        ^ data_i[113]
        ^ data_i[115]
        ^ data_i[116]
        ^ data_i[118]
        ^ data_i[120]
        ^ data_i[122]
        ^ data_i[123]
        ^ data_i[126]
        ^ data_i[127]
        ;
    assign syndrome[3] = check_i[3]
        ^ data_i[1]
        ^ data_i[3]
        ^ data_i[7]
        ^ data_i[10]
        ^ data_i[13]
        ^ data_i[16]
        ^ data_i[19]
        ^ data_i[22]
        ^ data_i[25]
        ^ data_i[27]
        ^ data_i[31]
        ^ data_i[33]
        ^ data_i[36]
        ^ data_i[40]
        ^ data_i[44]
        ^ data_i[47]
        ^ data_i[48]
        ^ data_i[52]
        ^ data_i[55]
        ^ data_i[57]
        ^ data_i[61]
        ^ data_i[64]
        ^ data_i[68]
        ^ data_i[70]
        ^ data_i[73]
        ^ data_i[75]
        ^ data_i[78]
        ^ data_i[81]
        ^ data_i[84]
        ^ data_i[86]
        ^ data_i[88]
        ^ data_i[90]
        ^ data_i[91]
        ^ data_i[93]
        ^ data_i[95]
        ^ data_i[97]
        ^ data_i[99]
        ^ data_i[100]
        ^ data_i[102]
        ^ data_i[104]
        ^ data_i[106]
        ^ data_i[107]
        ^ data_i[110]
        ^ data_i[111]
        ^ data_i[113]
        ^ data_i[115]
        ^ data_i[117]
        ^ data_i[119]
        ^ data_i[120]
        ^ data_i[122]
        ^ data_i[124]
        ^ data_i[125]
        ;
    assign syndrome[4] = check_i[4]
        ^ data_i[1]
        ^ data_i[4]
        ^ data_i[7]
        ^ data_i[9]
        ^ data_i[13]
        ^ data_i[16]
        ^ data_i[19]
        ^ data_i[23]
        ^ data_i[26]
        ^ data_i[28]
        ^ data_i[30]
        ^ data_i[34]
        ^ data_i[37]
        ^ data_i[41]
        ^ data_i[44]
        ^ data_i[45]
        ^ data_i[49]
        ^ data_i[53]
        ^ data_i[54]
        ^ data_i[59]
        ^ data_i[61]
        ^ data_i[65]
        ^ data_i[69]
        ^ data_i[71]
        ^ data_i[74]
        ^ data_i[76]
        ^ data_i[80]
        ^ data_i[83]
        ^ data_i[84]
        ^ data_i[86]
        ^ data_i[88]
        ^ data_i[90]
        ^ data_i[92]
        ^ data_i[94]
        ^ data_i[95]
        ^ data_i[97]
        ^ data_i[99]
        ^ data_i[101]
        ^ data_i[102]
        ^ data_i[104]
        ^ data_i[106]
        ^ data_i[108]
        ^ data_i[109]
        ^ data_i[112]
        ^ data_i[113]
        ^ data_i[115]
        ^ data_i[117]
        ^ data_i[118]
        ^ data_i[121]
        ^ data_i[122]
        ^ data_i[124]
        ^ data_i[126]
        ^ data_i[127]
        ;
    assign syndrome[5] = check_i[5]
        ^ data_i[1]
        ^ data_i[4]
        ^ data_i[8]
        ^ data_i[10]
        ^ data_i[14]
        ^ data_i[15]
        ^ data_i[20]
        ^ data_i[23]
        ^ data_i[26]
        ^ data_i[29]
        ^ data_i[32]
        ^ data_i[35]
        ^ data_i[38]
        ^ data_i[40]
        ^ data_i[43]
        ^ data_i[46]
        ^ data_i[49]
        ^ data_i[52]
        ^ data_i[55]
        ^ data_i[58]
        ^ data_i[60]
        ^ data_i[64]
        ^ data_i[66]
        ^ data_i[72]
        ^ data_i[74]
        ^ data_i[75]
        ^ data_i[79]
        ^ data_i[83]
        ^ data_i[85]
        ^ data_i[86]
        ^ data_i[88]
        ^ data_i[90]
        ^ data_i[92]
        ^ data_i[93]
        ^ data_i[96]
        ^ data_i[97]
        ^ data_i[99]
        ^ data_i[101]
        ^ data_i[103]
        ^ data_i[104]
        ^ data_i[106]
        ^ data_i[108]
        ^ data_i[110]
        ^ data_i[112]
        ^ data_i[114]
        ^ data_i[115]
        ^ data_i[117]
        ^ data_i[119]
        ^ data_i[120]
        ^ data_i[123]
        ^ data_i[124]
        ^ data_i[126]
        ;
    assign syndrome[6] = check_i[6]
        ^ data_i[2]
        ^ data_i[5]
        ^ data_i[7]
        ^ data_i[11]
        ^ data_i[14]
        ^ data_i[18]
        ^ data_i[20]
        ^ data_i[21]
        ^ data_i[25]
        ^ data_i[28]
        ^ data_i[32]
        ^ data_i[36]
        ^ data_i[38]
        ^ data_i[40]
        ^ data_i[43]
        ^ data_i[47]
        ^ data_i[50]
        ^ data_i[53]
        ^ data_i[56]
        ^ data_i[59]
        ^ data_i[63]
        ^ data_i[65]
        ^ data_i[67]
        ^ data_i[70]
        ^ data_i[74]
        ^ data_i[76]
        ^ data_i[78]
        ^ data_i[82]
        ^ data_i[85]
        ^ data_i[87]
        ^ data_i[88]
        ^ data_i[90]
        ^ data_i[92]
        ^ data_i[94]
        ^ data_i[95]
        ^ data_i[98]
        ^ data_i[99]
        ^ data_i[101]
        ^ data_i[103]
        ^ data_i[105]
        ^ data_i[106]
        ^ data_i[108]
        ^ data_i[110]
        ^ data_i[111]
        ^ data_i[114]
        ^ data_i[116]
        ^ data_i[118]
        ^ data_i[119]
        ^ data_i[121]
        ^ data_i[122]
        ^ data_i[125]
        ^ data_i[126]
        ;
    assign syndrome[7] = check_i[7]
        ^ data_i[2]
        ^ data_i[5]
        ^ data_i[8]
        ^ data_i[12]
        ^ data_i[13]
        ^ data_i[17]
        ^ data_i[20]
        ^ data_i[22]
        ^ data_i[24]
        ^ data_i[29]
        ^ data_i[33]
        ^ data_i[34]
        ^ data_i[39]
        ^ data_i[41]
        ^ data_i[45]
        ^ data_i[46]
        ^ data_i[50]
        ^ data_i[52]
        ^ data_i[57]
        ^ data_i[59]
        ^ data_i[62]
        ^ data_i[66]
        ^ data_i[67]
        ^ data_i[70]
        ^ data_i[73]
        ^ data_i[77]
        ^ data_i[80]
        ^ data_i[83]
        ^ data_i[85]
        ^ data_i[87]
        ^ data_i[89]
        ^ data_i[90]
        ^ data_i[92]
        ^ data_i[94]
        ^ data_i[96]
        ^ data_i[97]
        ^ data_i[100]
        ^ data_i[101]
        ^ data_i[103]
        ^ data_i[105]
        ^ data_i[107]
        ^ data_i[108]
        ^ data_i[110]
        ^ data_i[112]
        ^ data_i[113]
        ^ data_i[116]
        ^ data_i[117]
        ^ data_i[119]
        ^ data_i[121]
        ^ data_i[123]
        ^ data_i[124]
        ^ data_i[127]
        ;
    assign syndrome[8] = check_i[8]
        ^ data_i[2]
        ^ data_i[6]
        ^ data_i[8]
        ^ data_i[11]
        ^ data_i[14]
        ^ data_i[17]
        ^ data_i[19]
        ^ data_i[23]
        ^ data_i[27]
        ^ data_i[30]
        ^ data_i[31]
        ^ data_i[35]
        ^ data_i[37]
        ^ data_i[41]
        ^ data_i[42]
        ^ data_i[47]
        ^ data_i[51]
        ^ data_i[53]
        ^ data_i[56]
        ^ data_i[58]
        ^ data_i[62]
        ^ data_i[64]
        ^ data_i[68]
        ^ data_i[71]
        ^ data_i[73]
        ^ data_i[77]
        ^ data_i[79]
        ^ data_i[82]
        ^ data_i[85]
        ^ data_i[87]
        ^ data_i[89]
        ^ data_i[91]
        ^ data_i[92]
        ^ data_i[94]
        ^ data_i[96]
        ^ data_i[98]
        ^ data_i[99]
        ^ data_i[102]
        ^ data_i[103]
        ^ data_i[105]
        ^ data_i[107]
        ^ data_i[109]
        ^ data_i[110]
        ^ data_i[112]
        ^ data_i[114]
        ^ data_i[115]
        ^ data_i[117]
        ^ data_i[120]
        ^ data_i[121]
        ^ data_i[123]
        ^ data_i[125]
        ^ data_i[126]
        ;

    assign syndrome_o = syndrome;

    wire syndrome_nz  = |syndrome;
    wire syndrome_odd = ^syndrome;
    // Hsiao: odd syndrome parity == single-bit (correctable) error.
    assign ce_o = syndrome_nz &  syndrome_odd & ~poison_i;
    assign ue_o = (syndrome_nz & ~syndrome_odd) | poison_i;
    assign poison_o = poison_i | (syndrome_nz & ~syndrome_odd);

    wire [127:0] correct;
    assign correct[0] = (syndrome == 9'd7);
    assign correct[1] = (syndrome == 9'd56);
    assign correct[2] = (syndrome == 9'd448);
    assign correct[3] = (syndrome == 9'd11);
    assign correct[4] = (syndrome == 9'd52);
    assign correct[5] = (syndrome == 9'd193);
    assign correct[6] = (syndrome == 9'd262);
    assign correct[7] = (syndrome == 9'd88);
    assign correct[8] = (syndrome == 9'd416);
    assign correct[9] = (syndrome == 9'd19);
    assign correct[10] = (syndrome == 9'd44);
    assign correct[11] = (syndrome == 9'd321);
    assign correct[12] = (syndrome == 9'd134);
    assign correct[13] = (syndrome == 9'd152);
    assign correct[14] = (syndrome == 9'd352);
    assign correct[15] = (syndrome == 9'd35);
    assign correct[16] = (syndrome == 9'd28);
    assign correct[17] = (syndrome == 9'd385);
    assign correct[18] = (syndrome == 9'd70);
    assign correct[19] = (syndrome == 9'd280);
    assign correct[20] = (syndrome == 9'd224);
    assign correct[21] = (syndrome == 9'd67);
    assign correct[22] = (syndrome == 9'd140);
    assign correct[23] = (syndrome == 9'd304);
    assign correct[24] = (syndrome == 9'd131);
    assign correct[25] = (syndrome == 9'd76);
    assign correct[26] = (syndrome == 9'd49);
    assign correct[27] = (syndrome == 9'd266);
    assign correct[28] = (syndrome == 9'd84);
    assign correct[29] = (syndrome == 9'd161);
    assign correct[30] = (syndrome == 9'd274);
    assign correct[31] = (syndrome == 9'd268);
    assign correct[32] = (syndrome == 9'd97);
    assign correct[33] = (syndrome == 9'd138);
    assign correct[34] = (syndrome == 9'd148);
    assign correct[35] = (syndrome == 9'd289);
    assign correct[36] = (syndrome == 9'd74);
    assign correct[37] = (syndrome == 9'd276);
    assign correct[38] = (syndrome == 9'd98);
    assign correct[39] = (syndrome == 9'd133);
    assign correct[40] = (syndrome == 9'd104);
    assign correct[41] = (syndrome == 9'd400);
    assign correct[42] = (syndrome == 9'd259);
    assign correct[43] = (syndrome == 9'd100);
    assign correct[44] = (syndrome == 9'd25);
    assign correct[45] = (syndrome == 9'd146);
    assign correct[46] = (syndrome == 9'd164);
    assign correct[47] = (syndrome == 9'd328);
    assign correct[48] = (syndrome == 9'd13);
    assign correct[49] = (syndrome == 9'd50);
    assign correct[50] = (syndrome == 9'd194);
    assign correct[51] = (syndrome == 9'd261);
    assign correct[52] = (syndrome == 9'd168);
    assign correct[53] = (syndrome == 9'd336);
    assign correct[54] = (syndrome == 9'd21);
    assign correct[55] = (syndrome == 9'd42);
    assign correct[56] = (syndrome == 9'd322);
    assign correct[57] = (syndrome == 9'd137);
    assign correct[58] = (syndrome == 9'd292);
    assign correct[59] = (syndrome == 9'd208);
    assign correct[60] = (syndrome == 9'd37);
    assign correct[61] = (syndrome == 9'd26);
    assign correct[62] = (syndrome == 9'd386);
    assign correct[63] = (syndrome == 9'd69);
    assign correct[64] = (syndrome == 9'd296);
    assign correct[65] = (syndrome == 9'd81);
    assign correct[66] = (syndrome == 9'd162);
    assign correct[67] = (syndrome == 9'd196);
    assign correct[68] = (syndrome == 9'd265);
    assign correct[69] = (syndrome == 9'd22);
    assign correct[70] = (syndrome == 9'd200);
    assign correct[71] = (syndrome == 9'd273);
    assign correct[72] = (syndrome == 9'd38);
    assign correct[73] = (syndrome == 9'd392);
    assign correct[74] = (syndrome == 9'd112);
    assign correct[75] = (syndrome == 9'd41);
    assign correct[76] = (syndrome == 9'd82);
    assign correct[77] = (syndrome == 9'd388);
    assign correct[78] = (syndrome == 9'd73);
    assign correct[79] = (syndrome == 9'd290);
    assign correct[80] = (syndrome == 9'd145);
    assign correct[81] = (syndrome == 9'd14);
    assign correct[82] = (syndrome == 9'd324);
    assign correct[83] = (syndrome == 9'd176);
    assign correct[84] = (syndrome == 9'd31);
    assign correct[85] = (syndrome == 9'd481);
    assign correct[86] = (syndrome == 9'd62);
    assign correct[87] = (syndrome == 9'd451);
    assign correct[88] = (syndrome == 9'd124);
    assign correct[89] = (syndrome == 9'd391);
    assign correct[90] = (syndrome == 9'd248);
    assign correct[91] = (syndrome == 9'd271);
    assign correct[92] = (syndrome == 9'd496);
    assign correct[93] = (syndrome == 9'd47);
    assign correct[94] = (syndrome == 9'd465);
    assign correct[95] = (syndrome == 9'd94);
    assign correct[96] = (syndrome == 9'd419);
    assign correct[97] = (syndrome == 9'd188);
    assign correct[98] = (syndrome == 9'd327);
    assign correct[99] = (syndrome == 9'd376);
    assign correct[100] = (syndrome == 9'd143);
    assign correct[101] = (syndrome == 9'd241);
    assign correct[102] = (syndrome == 9'd286);
    assign correct[103] = (syndrome == 9'd482);
    assign correct[104] = (syndrome == 9'd61);
    assign correct[105] = (syndrome == 9'd453);
    assign correct[106] = (syndrome == 9'd122);
    assign correct[107] = (syndrome == 9'd395);
    assign correct[108] = (syndrome == 9'd244);
    assign correct[109] = (syndrome == 9'd279);
    assign correct[110] = (syndrome == 9'd488);
    assign correct[111] = (syndrome == 9'd79);
    assign correct[112] = (syndrome == 9'd433);
    assign correct[113] = (syndrome == 9'd158);
    assign correct[114] = (syndrome == 9'd355);
    assign correct[115] = (syndrome == 9'd316);
    assign correct[116] = (syndrome == 9'd199);
    assign correct[117] = (syndrome == 9'd440);
    assign correct[118] = (syndrome == 9'd87);
    assign correct[119] = (syndrome == 9'd233);
    assign correct[120] = (syndrome == 9'd302);
    assign correct[121] = (syndrome == 9'd466);
    assign correct[122] = (syndrome == 9'd93);
    assign correct[123] = (syndrome == 9'd421);
    assign correct[124] = (syndrome == 9'd186);
    assign correct[125] = (syndrome == 9'd331);
    assign correct[126] = (syndrome == 9'd372);
    assign correct[127] = (syndrome == 9'd151);

    // A syndrome equal to a unit vector points at a check bit, not data.
    assign ce_in_check_o = ce_o & ((syndrome == 9'd1) | (syndrome == 9'd2) | (syndrome == 9'd4) | (syndrome == 9'd8) | (syndrome == 9'd16) | (syndrome == 9'd32) | (syndrome == 9'd64) | (syndrome == 9'd128) | (syndrome == 9'd256));

    assign data_o = data_i ^ (correct & {128{ce_o}});

endmodule

// ---------------------------------------------------------------------------
// Pipelined split of the same code: vc3d_secded_syn_128 computes the
// syndrome (stage 1) and vc3d_secded_cor_128 applies the correction
// (stage 2) from a REGISTERED syndrome.  Splitting the decoder is what lets
// the ECC sit in a 3 GHz pipeline: the XOR tree and the 1-of-N correction
// compare are each about half of the combinational decoder.
// ---------------------------------------------------------------------------
module vc3d_secded_syn_128 (
    input  wire [127:0] data_i,
    input  wire [8:0] check_i,
    output wire [8:0] syndrome_o
);

    assign syndrome_o[0] = check_i[0]
        ^ data_i[0]
        ^ data_i[3]
        ^ data_i[5]
        ^ data_i[9]
        ^ data_i[11]
        ^ data_i[15]
        ^ data_i[17]
        ^ data_i[21]
        ^ data_i[24]
        ^ data_i[26]
        ^ data_i[29]
        ^ data_i[32]
        ^ data_i[35]
        ^ data_i[39]
        ^ data_i[42]
        ^ data_i[44]
        ^ data_i[48]
        ^ data_i[51]
        ^ data_i[54]
        ^ data_i[57]
        ^ data_i[60]
        ^ data_i[63]
        ^ data_i[65]
        ^ data_i[68]
        ^ data_i[71]
        ^ data_i[75]
        ^ data_i[78]
        ^ data_i[80]
        ^ data_i[84]
        ^ data_i[85]
        ^ data_i[87]
        ^ data_i[89]
        ^ data_i[91]
        ^ data_i[93]
        ^ data_i[94]
        ^ data_i[96]
        ^ data_i[98]
        ^ data_i[100]
        ^ data_i[101]
        ^ data_i[104]
        ^ data_i[105]
        ^ data_i[107]
        ^ data_i[109]
        ^ data_i[111]
        ^ data_i[112]
        ^ data_i[114]
        ^ data_i[116]
        ^ data_i[118]
        ^ data_i[119]
        ^ data_i[122]
        ^ data_i[123]
        ^ data_i[125]
        ^ data_i[127]
        ;
    assign syndrome_o[1] = check_i[1]
        ^ data_i[0]
        ^ data_i[3]
        ^ data_i[6]
        ^ data_i[9]
        ^ data_i[12]
        ^ data_i[15]
        ^ data_i[18]
        ^ data_i[21]
        ^ data_i[24]
        ^ data_i[27]
        ^ data_i[30]
        ^ data_i[33]
        ^ data_i[36]
        ^ data_i[38]
        ^ data_i[42]
        ^ data_i[45]
        ^ data_i[49]
        ^ data_i[50]
        ^ data_i[55]
        ^ data_i[56]
        ^ data_i[61]
        ^ data_i[62]
        ^ data_i[66]
        ^ data_i[69]
        ^ data_i[72]
        ^ data_i[76]
        ^ data_i[79]
        ^ data_i[81]
        ^ data_i[84]
        ^ data_i[86]
        ^ data_i[87]
        ^ data_i[89]
        ^ data_i[91]
        ^ data_i[93]
        ^ data_i[95]
        ^ data_i[96]
        ^ data_i[98]
        ^ data_i[100]
        ^ data_i[102]
        ^ data_i[103]
        ^ data_i[106]
        ^ data_i[107]
        ^ data_i[109]
        ^ data_i[111]
        ^ data_i[113]
        ^ data_i[114]
        ^ data_i[116]
        ^ data_i[118]
        ^ data_i[120]
        ^ data_i[121]
        ^ data_i[124]
        ^ data_i[125]
        ^ data_i[127]
        ;
    assign syndrome_o[2] = check_i[2]
        ^ data_i[0]
        ^ data_i[4]
        ^ data_i[6]
        ^ data_i[10]
        ^ data_i[12]
        ^ data_i[16]
        ^ data_i[18]
        ^ data_i[22]
        ^ data_i[25]
        ^ data_i[28]
        ^ data_i[31]
        ^ data_i[34]
        ^ data_i[37]
        ^ data_i[39]
        ^ data_i[43]
        ^ data_i[46]
        ^ data_i[48]
        ^ data_i[51]
        ^ data_i[54]
        ^ data_i[58]
        ^ data_i[60]
        ^ data_i[63]
        ^ data_i[67]
        ^ data_i[69]
        ^ data_i[72]
        ^ data_i[77]
        ^ data_i[81]
        ^ data_i[82]
        ^ data_i[84]
        ^ data_i[86]
        ^ data_i[88]
        ^ data_i[89]
        ^ data_i[91]
        ^ data_i[93]
        ^ data_i[95]
        ^ data_i[97]
        ^ data_i[98]
        ^ data_i[100]
        ^ data_i[102]
        ^ data_i[104]
        ^ data_i[105]
        ^ data_i[108]
        ^ data_i[109]
        ^ data_i[111]
        ^ data_i[113]
        ^ data_i[115]
        ^ data_i[116]
        ^ data_i[118]
        ^ data_i[120]
        ^ data_i[122]
        ^ data_i[123]
        ^ data_i[126]
        ^ data_i[127]
        ;
    assign syndrome_o[3] = check_i[3]
        ^ data_i[1]
        ^ data_i[3]
        ^ data_i[7]
        ^ data_i[10]
        ^ data_i[13]
        ^ data_i[16]
        ^ data_i[19]
        ^ data_i[22]
        ^ data_i[25]
        ^ data_i[27]
        ^ data_i[31]
        ^ data_i[33]
        ^ data_i[36]
        ^ data_i[40]
        ^ data_i[44]
        ^ data_i[47]
        ^ data_i[48]
        ^ data_i[52]
        ^ data_i[55]
        ^ data_i[57]
        ^ data_i[61]
        ^ data_i[64]
        ^ data_i[68]
        ^ data_i[70]
        ^ data_i[73]
        ^ data_i[75]
        ^ data_i[78]
        ^ data_i[81]
        ^ data_i[84]
        ^ data_i[86]
        ^ data_i[88]
        ^ data_i[90]
        ^ data_i[91]
        ^ data_i[93]
        ^ data_i[95]
        ^ data_i[97]
        ^ data_i[99]
        ^ data_i[100]
        ^ data_i[102]
        ^ data_i[104]
        ^ data_i[106]
        ^ data_i[107]
        ^ data_i[110]
        ^ data_i[111]
        ^ data_i[113]
        ^ data_i[115]
        ^ data_i[117]
        ^ data_i[119]
        ^ data_i[120]
        ^ data_i[122]
        ^ data_i[124]
        ^ data_i[125]
        ;
    assign syndrome_o[4] = check_i[4]
        ^ data_i[1]
        ^ data_i[4]
        ^ data_i[7]
        ^ data_i[9]
        ^ data_i[13]
        ^ data_i[16]
        ^ data_i[19]
        ^ data_i[23]
        ^ data_i[26]
        ^ data_i[28]
        ^ data_i[30]
        ^ data_i[34]
        ^ data_i[37]
        ^ data_i[41]
        ^ data_i[44]
        ^ data_i[45]
        ^ data_i[49]
        ^ data_i[53]
        ^ data_i[54]
        ^ data_i[59]
        ^ data_i[61]
        ^ data_i[65]
        ^ data_i[69]
        ^ data_i[71]
        ^ data_i[74]
        ^ data_i[76]
        ^ data_i[80]
        ^ data_i[83]
        ^ data_i[84]
        ^ data_i[86]
        ^ data_i[88]
        ^ data_i[90]
        ^ data_i[92]
        ^ data_i[94]
        ^ data_i[95]
        ^ data_i[97]
        ^ data_i[99]
        ^ data_i[101]
        ^ data_i[102]
        ^ data_i[104]
        ^ data_i[106]
        ^ data_i[108]
        ^ data_i[109]
        ^ data_i[112]
        ^ data_i[113]
        ^ data_i[115]
        ^ data_i[117]
        ^ data_i[118]
        ^ data_i[121]
        ^ data_i[122]
        ^ data_i[124]
        ^ data_i[126]
        ^ data_i[127]
        ;
    assign syndrome_o[5] = check_i[5]
        ^ data_i[1]
        ^ data_i[4]
        ^ data_i[8]
        ^ data_i[10]
        ^ data_i[14]
        ^ data_i[15]
        ^ data_i[20]
        ^ data_i[23]
        ^ data_i[26]
        ^ data_i[29]
        ^ data_i[32]
        ^ data_i[35]
        ^ data_i[38]
        ^ data_i[40]
        ^ data_i[43]
        ^ data_i[46]
        ^ data_i[49]
        ^ data_i[52]
        ^ data_i[55]
        ^ data_i[58]
        ^ data_i[60]
        ^ data_i[64]
        ^ data_i[66]
        ^ data_i[72]
        ^ data_i[74]
        ^ data_i[75]
        ^ data_i[79]
        ^ data_i[83]
        ^ data_i[85]
        ^ data_i[86]
        ^ data_i[88]
        ^ data_i[90]
        ^ data_i[92]
        ^ data_i[93]
        ^ data_i[96]
        ^ data_i[97]
        ^ data_i[99]
        ^ data_i[101]
        ^ data_i[103]
        ^ data_i[104]
        ^ data_i[106]
        ^ data_i[108]
        ^ data_i[110]
        ^ data_i[112]
        ^ data_i[114]
        ^ data_i[115]
        ^ data_i[117]
        ^ data_i[119]
        ^ data_i[120]
        ^ data_i[123]
        ^ data_i[124]
        ^ data_i[126]
        ;
    assign syndrome_o[6] = check_i[6]
        ^ data_i[2]
        ^ data_i[5]
        ^ data_i[7]
        ^ data_i[11]
        ^ data_i[14]
        ^ data_i[18]
        ^ data_i[20]
        ^ data_i[21]
        ^ data_i[25]
        ^ data_i[28]
        ^ data_i[32]
        ^ data_i[36]
        ^ data_i[38]
        ^ data_i[40]
        ^ data_i[43]
        ^ data_i[47]
        ^ data_i[50]
        ^ data_i[53]
        ^ data_i[56]
        ^ data_i[59]
        ^ data_i[63]
        ^ data_i[65]
        ^ data_i[67]
        ^ data_i[70]
        ^ data_i[74]
        ^ data_i[76]
        ^ data_i[78]
        ^ data_i[82]
        ^ data_i[85]
        ^ data_i[87]
        ^ data_i[88]
        ^ data_i[90]
        ^ data_i[92]
        ^ data_i[94]
        ^ data_i[95]
        ^ data_i[98]
        ^ data_i[99]
        ^ data_i[101]
        ^ data_i[103]
        ^ data_i[105]
        ^ data_i[106]
        ^ data_i[108]
        ^ data_i[110]
        ^ data_i[111]
        ^ data_i[114]
        ^ data_i[116]
        ^ data_i[118]
        ^ data_i[119]
        ^ data_i[121]
        ^ data_i[122]
        ^ data_i[125]
        ^ data_i[126]
        ;
    assign syndrome_o[7] = check_i[7]
        ^ data_i[2]
        ^ data_i[5]
        ^ data_i[8]
        ^ data_i[12]
        ^ data_i[13]
        ^ data_i[17]
        ^ data_i[20]
        ^ data_i[22]
        ^ data_i[24]
        ^ data_i[29]
        ^ data_i[33]
        ^ data_i[34]
        ^ data_i[39]
        ^ data_i[41]
        ^ data_i[45]
        ^ data_i[46]
        ^ data_i[50]
        ^ data_i[52]
        ^ data_i[57]
        ^ data_i[59]
        ^ data_i[62]
        ^ data_i[66]
        ^ data_i[67]
        ^ data_i[70]
        ^ data_i[73]
        ^ data_i[77]
        ^ data_i[80]
        ^ data_i[83]
        ^ data_i[85]
        ^ data_i[87]
        ^ data_i[89]
        ^ data_i[90]
        ^ data_i[92]
        ^ data_i[94]
        ^ data_i[96]
        ^ data_i[97]
        ^ data_i[100]
        ^ data_i[101]
        ^ data_i[103]
        ^ data_i[105]
        ^ data_i[107]
        ^ data_i[108]
        ^ data_i[110]
        ^ data_i[112]
        ^ data_i[113]
        ^ data_i[116]
        ^ data_i[117]
        ^ data_i[119]
        ^ data_i[121]
        ^ data_i[123]
        ^ data_i[124]
        ^ data_i[127]
        ;
    assign syndrome_o[8] = check_i[8]
        ^ data_i[2]
        ^ data_i[6]
        ^ data_i[8]
        ^ data_i[11]
        ^ data_i[14]
        ^ data_i[17]
        ^ data_i[19]
        ^ data_i[23]
        ^ data_i[27]
        ^ data_i[30]
        ^ data_i[31]
        ^ data_i[35]
        ^ data_i[37]
        ^ data_i[41]
        ^ data_i[42]
        ^ data_i[47]
        ^ data_i[51]
        ^ data_i[53]
        ^ data_i[56]
        ^ data_i[58]
        ^ data_i[62]
        ^ data_i[64]
        ^ data_i[68]
        ^ data_i[71]
        ^ data_i[73]
        ^ data_i[77]
        ^ data_i[79]
        ^ data_i[82]
        ^ data_i[85]
        ^ data_i[87]
        ^ data_i[89]
        ^ data_i[91]
        ^ data_i[92]
        ^ data_i[94]
        ^ data_i[96]
        ^ data_i[98]
        ^ data_i[99]
        ^ data_i[102]
        ^ data_i[103]
        ^ data_i[105]
        ^ data_i[107]
        ^ data_i[109]
        ^ data_i[110]
        ^ data_i[112]
        ^ data_i[114]
        ^ data_i[115]
        ^ data_i[117]
        ^ data_i[120]
        ^ data_i[121]
        ^ data_i[123]
        ^ data_i[125]
        ^ data_i[126]
        ;

endmodule

module vc3d_secded_cor_128 (
    input  wire [127:0] data_i,      // registered, same beat as syndrome
    input  wire [8:0] syndrome_i,
    input  wire poison_i,
    output wire [127:0] data_o,
    output wire ce_o,
    output wire ue_o,
    output wire poison_o
);

    wire syndrome_nz  = |syndrome_i;
    wire syndrome_odd = ^syndrome_i;
    assign ce_o     = syndrome_nz &  syndrome_odd & ~poison_i;
    assign ue_o     = (syndrome_nz & ~syndrome_odd) | poison_i;
    assign poison_o = poison_i | (syndrome_nz & ~syndrome_odd);

    wire [127:0] correct;
    assign correct[0] = (syndrome_i == 9'd7);
    assign correct[1] = (syndrome_i == 9'd56);
    assign correct[2] = (syndrome_i == 9'd448);
    assign correct[3] = (syndrome_i == 9'd11);
    assign correct[4] = (syndrome_i == 9'd52);
    assign correct[5] = (syndrome_i == 9'd193);
    assign correct[6] = (syndrome_i == 9'd262);
    assign correct[7] = (syndrome_i == 9'd88);
    assign correct[8] = (syndrome_i == 9'd416);
    assign correct[9] = (syndrome_i == 9'd19);
    assign correct[10] = (syndrome_i == 9'd44);
    assign correct[11] = (syndrome_i == 9'd321);
    assign correct[12] = (syndrome_i == 9'd134);
    assign correct[13] = (syndrome_i == 9'd152);
    assign correct[14] = (syndrome_i == 9'd352);
    assign correct[15] = (syndrome_i == 9'd35);
    assign correct[16] = (syndrome_i == 9'd28);
    assign correct[17] = (syndrome_i == 9'd385);
    assign correct[18] = (syndrome_i == 9'd70);
    assign correct[19] = (syndrome_i == 9'd280);
    assign correct[20] = (syndrome_i == 9'd224);
    assign correct[21] = (syndrome_i == 9'd67);
    assign correct[22] = (syndrome_i == 9'd140);
    assign correct[23] = (syndrome_i == 9'd304);
    assign correct[24] = (syndrome_i == 9'd131);
    assign correct[25] = (syndrome_i == 9'd76);
    assign correct[26] = (syndrome_i == 9'd49);
    assign correct[27] = (syndrome_i == 9'd266);
    assign correct[28] = (syndrome_i == 9'd84);
    assign correct[29] = (syndrome_i == 9'd161);
    assign correct[30] = (syndrome_i == 9'd274);
    assign correct[31] = (syndrome_i == 9'd268);
    assign correct[32] = (syndrome_i == 9'd97);
    assign correct[33] = (syndrome_i == 9'd138);
    assign correct[34] = (syndrome_i == 9'd148);
    assign correct[35] = (syndrome_i == 9'd289);
    assign correct[36] = (syndrome_i == 9'd74);
    assign correct[37] = (syndrome_i == 9'd276);
    assign correct[38] = (syndrome_i == 9'd98);
    assign correct[39] = (syndrome_i == 9'd133);
    assign correct[40] = (syndrome_i == 9'd104);
    assign correct[41] = (syndrome_i == 9'd400);
    assign correct[42] = (syndrome_i == 9'd259);
    assign correct[43] = (syndrome_i == 9'd100);
    assign correct[44] = (syndrome_i == 9'd25);
    assign correct[45] = (syndrome_i == 9'd146);
    assign correct[46] = (syndrome_i == 9'd164);
    assign correct[47] = (syndrome_i == 9'd328);
    assign correct[48] = (syndrome_i == 9'd13);
    assign correct[49] = (syndrome_i == 9'd50);
    assign correct[50] = (syndrome_i == 9'd194);
    assign correct[51] = (syndrome_i == 9'd261);
    assign correct[52] = (syndrome_i == 9'd168);
    assign correct[53] = (syndrome_i == 9'd336);
    assign correct[54] = (syndrome_i == 9'd21);
    assign correct[55] = (syndrome_i == 9'd42);
    assign correct[56] = (syndrome_i == 9'd322);
    assign correct[57] = (syndrome_i == 9'd137);
    assign correct[58] = (syndrome_i == 9'd292);
    assign correct[59] = (syndrome_i == 9'd208);
    assign correct[60] = (syndrome_i == 9'd37);
    assign correct[61] = (syndrome_i == 9'd26);
    assign correct[62] = (syndrome_i == 9'd386);
    assign correct[63] = (syndrome_i == 9'd69);
    assign correct[64] = (syndrome_i == 9'd296);
    assign correct[65] = (syndrome_i == 9'd81);
    assign correct[66] = (syndrome_i == 9'd162);
    assign correct[67] = (syndrome_i == 9'd196);
    assign correct[68] = (syndrome_i == 9'd265);
    assign correct[69] = (syndrome_i == 9'd22);
    assign correct[70] = (syndrome_i == 9'd200);
    assign correct[71] = (syndrome_i == 9'd273);
    assign correct[72] = (syndrome_i == 9'd38);
    assign correct[73] = (syndrome_i == 9'd392);
    assign correct[74] = (syndrome_i == 9'd112);
    assign correct[75] = (syndrome_i == 9'd41);
    assign correct[76] = (syndrome_i == 9'd82);
    assign correct[77] = (syndrome_i == 9'd388);
    assign correct[78] = (syndrome_i == 9'd73);
    assign correct[79] = (syndrome_i == 9'd290);
    assign correct[80] = (syndrome_i == 9'd145);
    assign correct[81] = (syndrome_i == 9'd14);
    assign correct[82] = (syndrome_i == 9'd324);
    assign correct[83] = (syndrome_i == 9'd176);
    assign correct[84] = (syndrome_i == 9'd31);
    assign correct[85] = (syndrome_i == 9'd481);
    assign correct[86] = (syndrome_i == 9'd62);
    assign correct[87] = (syndrome_i == 9'd451);
    assign correct[88] = (syndrome_i == 9'd124);
    assign correct[89] = (syndrome_i == 9'd391);
    assign correct[90] = (syndrome_i == 9'd248);
    assign correct[91] = (syndrome_i == 9'd271);
    assign correct[92] = (syndrome_i == 9'd496);
    assign correct[93] = (syndrome_i == 9'd47);
    assign correct[94] = (syndrome_i == 9'd465);
    assign correct[95] = (syndrome_i == 9'd94);
    assign correct[96] = (syndrome_i == 9'd419);
    assign correct[97] = (syndrome_i == 9'd188);
    assign correct[98] = (syndrome_i == 9'd327);
    assign correct[99] = (syndrome_i == 9'd376);
    assign correct[100] = (syndrome_i == 9'd143);
    assign correct[101] = (syndrome_i == 9'd241);
    assign correct[102] = (syndrome_i == 9'd286);
    assign correct[103] = (syndrome_i == 9'd482);
    assign correct[104] = (syndrome_i == 9'd61);
    assign correct[105] = (syndrome_i == 9'd453);
    assign correct[106] = (syndrome_i == 9'd122);
    assign correct[107] = (syndrome_i == 9'd395);
    assign correct[108] = (syndrome_i == 9'd244);
    assign correct[109] = (syndrome_i == 9'd279);
    assign correct[110] = (syndrome_i == 9'd488);
    assign correct[111] = (syndrome_i == 9'd79);
    assign correct[112] = (syndrome_i == 9'd433);
    assign correct[113] = (syndrome_i == 9'd158);
    assign correct[114] = (syndrome_i == 9'd355);
    assign correct[115] = (syndrome_i == 9'd316);
    assign correct[116] = (syndrome_i == 9'd199);
    assign correct[117] = (syndrome_i == 9'd440);
    assign correct[118] = (syndrome_i == 9'd87);
    assign correct[119] = (syndrome_i == 9'd233);
    assign correct[120] = (syndrome_i == 9'd302);
    assign correct[121] = (syndrome_i == 9'd466);
    assign correct[122] = (syndrome_i == 9'd93);
    assign correct[123] = (syndrome_i == 9'd421);
    assign correct[124] = (syndrome_i == 9'd186);
    assign correct[125] = (syndrome_i == 9'd331);
    assign correct[126] = (syndrome_i == 9'd372);
    assign correct[127] = (syndrome_i == 9'd151);

    assign data_o = data_i ^ (correct & {128{ce_o}});

endmodule

