// ---------------------------------------------------------------------------
// AUTO-GENERATED by gen/vc3d_gen_ecc.py -- DO NOT HAND EDIT.
// SECDED (Hsiao) codec for 32 data bits + 7 check bits.
// Code distance 4: corrects 1 bit, detects 2 bits, detects all odd-weight
// error patterns.  Row loads (XOR-tree fan-in per check bit): [14, 14, 14, 14, 14, 13, 13]
// Max fan-in 14  ->  balanced XOR depth ceil(log2(max)) = 4.
// ---------------------------------------------------------------------------
`timescale 1ns/1ps

module vc3d_secded_enc_32 (
    input  wire [31:0] data_i,
    output wire [6:0] check_o
);

    // check bit 0: 14 taps
    assign check_o[0] =
          data_i[0] ^
        data_i[2] ^
        data_i[4] ^
        data_i[7] ^
        data_i[9] ^
        data_i[12] ^
        data_i[13] ^
        data_i[16] ^
        data_i[18] ^
        data_i[21] ^
        data_i[23] ^
        data_i[26] ^
        data_i[27] ^
        data_i[31];

    // check bit 1: 14 taps
    assign check_o[1] =
          data_i[0] ^
        data_i[2] ^
        data_i[5] ^
        data_i[7] ^
        data_i[10] ^
        data_i[11] ^
        data_i[14] ^
        data_i[16] ^
        data_i[19] ^
        data_i[21] ^
        data_i[24] ^
        data_i[25] ^
        data_i[28] ^
        data_i[30];

    // check bit 2: 14 taps
    assign check_o[2] =
          data_i[0] ^
        data_i[3] ^
        data_i[5] ^
        data_i[8] ^
        data_i[9] ^
        data_i[12] ^
        data_i[14] ^
        data_i[17] ^
        data_i[19] ^
        data_i[22] ^
        data_i[23] ^
        data_i[26] ^
        data_i[29] ^
        data_i[30];

    // check bit 3: 14 taps
    assign check_o[3] =
          data_i[1] ^
        data_i[3] ^
        data_i[5] ^
        data_i[7] ^
        data_i[10] ^
        data_i[12] ^
        data_i[15] ^
        data_i[17] ^
        data_i[20] ^
        data_i[22] ^
        data_i[24] ^
        data_i[27] ^
        data_i[28] ^
        data_i[31];

    // check bit 4: 14 taps
    assign check_o[4] =
          data_i[1] ^
        data_i[3] ^
        data_i[6] ^
        data_i[8] ^
        data_i[10] ^
        data_i[13] ^
        data_i[15] ^
        data_i[18] ^
        data_i[19] ^
        data_i[21] ^
        data_i[25] ^
        data_i[26] ^
        data_i[29] ^
        data_i[31];

    // check bit 5: 13 taps
    assign check_o[5] =
          data_i[1] ^
        data_i[4] ^
        data_i[6] ^
        data_i[8] ^
        data_i[11] ^
        data_i[13] ^
        data_i[16] ^
        data_i[17] ^
        data_i[20] ^
        data_i[23] ^
        data_i[24] ^
        data_i[27] ^
        data_i[30];

    // check bit 6: 13 taps
    assign check_o[6] =
          data_i[2] ^
        data_i[4] ^
        data_i[6] ^
        data_i[9] ^
        data_i[11] ^
        data_i[14] ^
        data_i[15] ^
        data_i[18] ^
        data_i[20] ^
        data_i[22] ^
        data_i[25] ^
        data_i[28] ^
        data_i[29];

endmodule

module vc3d_secded_dec_32 (
    input  wire [31:0] data_i,
    input  wire [6:0] check_i,
    input  wire poison_i,
    output wire [31:0] data_o,
    output wire [6:0] syndrome_o,
    output wire ce_o,           // corrected single-bit error
    output wire ue_o,           // uncorrectable (double bit) error
    output wire ce_in_check_o,  // the corrected bit was a check bit
    output wire poison_o
);

    wire [6:0] syndrome;
    assign syndrome[0] = check_i[0]
        ^ data_i[0]
        ^ data_i[2]
        ^ data_i[4]
        ^ data_i[7]
        ^ data_i[9]
        ^ data_i[12]
        ^ data_i[13]
        ^ data_i[16]
        ^ data_i[18]
        ^ data_i[21]
        ^ data_i[23]
        ^ data_i[26]
        ^ data_i[27]
        ^ data_i[31]
        ;
    assign syndrome[1] = check_i[1]
        ^ data_i[0]
        ^ data_i[2]
        ^ data_i[5]
        ^ data_i[7]
        ^ data_i[10]
        ^ data_i[11]
        ^ data_i[14]
        ^ data_i[16]
        ^ data_i[19]
        ^ data_i[21]
        ^ data_i[24]
        ^ data_i[25]
        ^ data_i[28]
        ^ data_i[30]
        ;
    assign syndrome[2] = check_i[2]
        ^ data_i[0]
        ^ data_i[3]
        ^ data_i[5]
        ^ data_i[8]
        ^ data_i[9]
        ^ data_i[12]
        ^ data_i[14]
        ^ data_i[17]
        ^ data_i[19]
        ^ data_i[22]
        ^ data_i[23]
        ^ data_i[26]
        ^ data_i[29]
        ^ data_i[30]
        ;
    assign syndrome[3] = check_i[3]
        ^ data_i[1]
        ^ data_i[3]
        ^ data_i[5]
        ^ data_i[7]
        ^ data_i[10]
        ^ data_i[12]
        ^ data_i[15]
        ^ data_i[17]
        ^ data_i[20]
        ^ data_i[22]
        ^ data_i[24]
        ^ data_i[27]
        ^ data_i[28]
        ^ data_i[31]
        ;
    assign syndrome[4] = check_i[4]
        ^ data_i[1]
        ^ data_i[3]
        ^ data_i[6]
        ^ data_i[8]
        ^ data_i[10]
        ^ data_i[13]
        ^ data_i[15]
        ^ data_i[18]
        ^ data_i[19]
        ^ data_i[21]
        ^ data_i[25]
        ^ data_i[26]
        ^ data_i[29]
        ^ data_i[31]
        ;
    assign syndrome[5] = check_i[5]
        ^ data_i[1]
        ^ data_i[4]
        ^ data_i[6]
        ^ data_i[8]
        ^ data_i[11]
        ^ data_i[13]
        ^ data_i[16]
        ^ data_i[17]
        ^ data_i[20]
        ^ data_i[23]
        ^ data_i[24]
        ^ data_i[27]
        ^ data_i[30]
        ;
    assign syndrome[6] = check_i[6]
        ^ data_i[2]
        ^ data_i[4]
        ^ data_i[6]
        ^ data_i[9]
        ^ data_i[11]
        ^ data_i[14]
        ^ data_i[15]
        ^ data_i[18]
        ^ data_i[20]
        ^ data_i[22]
        ^ data_i[25]
        ^ data_i[28]
        ^ data_i[29]
        ;

    assign syndrome_o = syndrome;

    wire syndrome_nz  = |syndrome;
    wire syndrome_odd = ^syndrome;
    // Hsiao: odd syndrome parity == single-bit (correctable) error.
    assign ce_o = syndrome_nz &  syndrome_odd & ~poison_i;
    assign ue_o = (syndrome_nz & ~syndrome_odd) | poison_i;
    assign poison_o = poison_i | (syndrome_nz & ~syndrome_odd);

    wire [31:0] correct;
    assign correct[0] = (syndrome == 7'd7);
    assign correct[1] = (syndrome == 7'd56);
    assign correct[2] = (syndrome == 7'd67);
    assign correct[3] = (syndrome == 7'd28);
    assign correct[4] = (syndrome == 7'd97);
    assign correct[5] = (syndrome == 7'd14);
    assign correct[6] = (syndrome == 7'd112);
    assign correct[7] = (syndrome == 7'd11);
    assign correct[8] = (syndrome == 7'd52);
    assign correct[9] = (syndrome == 7'd69);
    assign correct[10] = (syndrome == 7'd26);
    assign correct[11] = (syndrome == 7'd98);
    assign correct[12] = (syndrome == 7'd13);
    assign correct[13] = (syndrome == 7'd49);
    assign correct[14] = (syndrome == 7'd70);
    assign correct[15] = (syndrome == 7'd88);
    assign correct[16] = (syndrome == 7'd35);
    assign correct[17] = (syndrome == 7'd44);
    assign correct[18] = (syndrome == 7'd81);
    assign correct[19] = (syndrome == 7'd22);
    assign correct[20] = (syndrome == 7'd104);
    assign correct[21] = (syndrome == 7'd19);
    assign correct[22] = (syndrome == 7'd76);
    assign correct[23] = (syndrome == 7'd37);
    assign correct[24] = (syndrome == 7'd42);
    assign correct[25] = (syndrome == 7'd82);
    assign correct[26] = (syndrome == 7'd21);
    assign correct[27] = (syndrome == 7'd41);
    assign correct[28] = (syndrome == 7'd74);
    assign correct[29] = (syndrome == 7'd84);
    assign correct[30] = (syndrome == 7'd38);
    assign correct[31] = (syndrome == 7'd25);

    // A syndrome equal to a unit vector points at a check bit, not data.
    assign ce_in_check_o = ce_o & ((syndrome == 7'd1) | (syndrome == 7'd2) | (syndrome == 7'd4) | (syndrome == 7'd8) | (syndrome == 7'd16) | (syndrome == 7'd32) | (syndrome == 7'd64));

    assign data_o = data_i ^ (correct & {32{ce_o}});

endmodule

// ---------------------------------------------------------------------------
// Pipelined split of the same code: vc3d_secded_syn_32 computes the
// syndrome (stage 1) and vc3d_secded_cor_32 applies the correction
// (stage 2) from a REGISTERED syndrome.  Splitting the decoder is what lets
// the ECC sit in a 3 GHz pipeline: the XOR tree and the 1-of-N correction
// compare are each about half of the combinational decoder.
// ---------------------------------------------------------------------------
module vc3d_secded_syn_32 (
    input  wire [31:0] data_i,
    input  wire [6:0] check_i,
    output wire [6:0] syndrome_o
);

    assign syndrome_o[0] = check_i[0]
        ^ data_i[0]
        ^ data_i[2]
        ^ data_i[4]
        ^ data_i[7]
        ^ data_i[9]
        ^ data_i[12]
        ^ data_i[13]
        ^ data_i[16]
        ^ data_i[18]
        ^ data_i[21]
        ^ data_i[23]
        ^ data_i[26]
        ^ data_i[27]
        ^ data_i[31]
        ;
    assign syndrome_o[1] = check_i[1]
        ^ data_i[0]
        ^ data_i[2]
        ^ data_i[5]
        ^ data_i[7]
        ^ data_i[10]
        ^ data_i[11]
        ^ data_i[14]
        ^ data_i[16]
        ^ data_i[19]
        ^ data_i[21]
        ^ data_i[24]
        ^ data_i[25]
        ^ data_i[28]
        ^ data_i[30]
        ;
    assign syndrome_o[2] = check_i[2]
        ^ data_i[0]
        ^ data_i[3]
        ^ data_i[5]
        ^ data_i[8]
        ^ data_i[9]
        ^ data_i[12]
        ^ data_i[14]
        ^ data_i[17]
        ^ data_i[19]
        ^ data_i[22]
        ^ data_i[23]
        ^ data_i[26]
        ^ data_i[29]
        ^ data_i[30]
        ;
    assign syndrome_o[3] = check_i[3]
        ^ data_i[1]
        ^ data_i[3]
        ^ data_i[5]
        ^ data_i[7]
        ^ data_i[10]
        ^ data_i[12]
        ^ data_i[15]
        ^ data_i[17]
        ^ data_i[20]
        ^ data_i[22]
        ^ data_i[24]
        ^ data_i[27]
        ^ data_i[28]
        ^ data_i[31]
        ;
    assign syndrome_o[4] = check_i[4]
        ^ data_i[1]
        ^ data_i[3]
        ^ data_i[6]
        ^ data_i[8]
        ^ data_i[10]
        ^ data_i[13]
        ^ data_i[15]
        ^ data_i[18]
        ^ data_i[19]
        ^ data_i[21]
        ^ data_i[25]
        ^ data_i[26]
        ^ data_i[29]
        ^ data_i[31]
        ;
    assign syndrome_o[5] = check_i[5]
        ^ data_i[1]
        ^ data_i[4]
        ^ data_i[6]
        ^ data_i[8]
        ^ data_i[11]
        ^ data_i[13]
        ^ data_i[16]
        ^ data_i[17]
        ^ data_i[20]
        ^ data_i[23]
        ^ data_i[24]
        ^ data_i[27]
        ^ data_i[30]
        ;
    assign syndrome_o[6] = check_i[6]
        ^ data_i[2]
        ^ data_i[4]
        ^ data_i[6]
        ^ data_i[9]
        ^ data_i[11]
        ^ data_i[14]
        ^ data_i[15]
        ^ data_i[18]
        ^ data_i[20]
        ^ data_i[22]
        ^ data_i[25]
        ^ data_i[28]
        ^ data_i[29]
        ;

endmodule

module vc3d_secded_cor_32 (
    input  wire [31:0] data_i,      // registered, same beat as syndrome
    input  wire [6:0] syndrome_i,
    input  wire poison_i,
    output wire [31:0] data_o,
    output wire ce_o,
    output wire ue_o,
    output wire poison_o
);

    wire syndrome_nz  = |syndrome_i;
    wire syndrome_odd = ^syndrome_i;
    assign ce_o     = syndrome_nz &  syndrome_odd & ~poison_i;
    assign ue_o     = (syndrome_nz & ~syndrome_odd) | poison_i;
    assign poison_o = poison_i | (syndrome_nz & ~syndrome_odd);

    wire [31:0] correct;
    assign correct[0] = (syndrome_i == 7'd7);
    assign correct[1] = (syndrome_i == 7'd56);
    assign correct[2] = (syndrome_i == 7'd67);
    assign correct[3] = (syndrome_i == 7'd28);
    assign correct[4] = (syndrome_i == 7'd97);
    assign correct[5] = (syndrome_i == 7'd14);
    assign correct[6] = (syndrome_i == 7'd112);
    assign correct[7] = (syndrome_i == 7'd11);
    assign correct[8] = (syndrome_i == 7'd52);
    assign correct[9] = (syndrome_i == 7'd69);
    assign correct[10] = (syndrome_i == 7'd26);
    assign correct[11] = (syndrome_i == 7'd98);
    assign correct[12] = (syndrome_i == 7'd13);
    assign correct[13] = (syndrome_i == 7'd49);
    assign correct[14] = (syndrome_i == 7'd70);
    assign correct[15] = (syndrome_i == 7'd88);
    assign correct[16] = (syndrome_i == 7'd35);
    assign correct[17] = (syndrome_i == 7'd44);
    assign correct[18] = (syndrome_i == 7'd81);
    assign correct[19] = (syndrome_i == 7'd22);
    assign correct[20] = (syndrome_i == 7'd104);
    assign correct[21] = (syndrome_i == 7'd19);
    assign correct[22] = (syndrome_i == 7'd76);
    assign correct[23] = (syndrome_i == 7'd37);
    assign correct[24] = (syndrome_i == 7'd42);
    assign correct[25] = (syndrome_i == 7'd82);
    assign correct[26] = (syndrome_i == 7'd21);
    assign correct[27] = (syndrome_i == 7'd41);
    assign correct[28] = (syndrome_i == 7'd74);
    assign correct[29] = (syndrome_i == 7'd84);
    assign correct[30] = (syndrome_i == 7'd38);
    assign correct[31] = (syndrome_i == 7'd25);

    assign data_o = data_i ^ (correct & {32{ce_o}});

endmodule

