// ---------------------------------------------------------------------------
// AUTO-GENERATED by gen/vc3d_gen_ecc.py -- DO NOT HAND EDIT.
// SECDED (Hsiao) codec for 256 data bits + 10 check bits.
// Code distance 4: corrects 1 bit, detects 2 bits, detects all odd-weight
// error patterns.  Row loads (XOR-tree fan-in per check bit): [104, 104, 104, 104, 104, 104, 104, 104, 104, 104]
// Max fan-in 104  ->  balanced XOR depth ceil(log2(max)) = 7.
// ---------------------------------------------------------------------------
`timescale 1ns/1ps

module vc3d_secded_enc_256 (
    input  wire [255:0] data_i,
    output wire [9:0] check_o
);

    // check bit 0: 104 taps
    assign check_o[0] =
          data_i[0] ^
        data_i[3] ^
        data_i[6] ^
        data_i[10] ^
        data_i[13] ^
        data_i[17] ^
        data_i[20] ^
        data_i[23] ^
        data_i[26] ^
        data_i[29] ^
        data_i[33] ^
        data_i[37] ^
        data_i[39] ^
        data_i[43] ^
        data_i[46] ^
        data_i[50] ^
        data_i[53] ^
        data_i[57] ^
        data_i[59] ^
        data_i[62] ^
        data_i[66] ^
        data_i[69] ^
        data_i[72] ^
        data_i[77] ^
        data_i[80] ^
        data_i[83] ^
        data_i[87] ^
        data_i[89] ^
        data_i[93] ^
        data_i[96] ^
        data_i[99] ^
        data_i[102] ^
        data_i[107] ^
        data_i[111] ^
        data_i[114] ^
        data_i[117] ^
        data_i[120] ^
        data_i[122] ^
        data_i[124] ^
        data_i[126] ^
        data_i[128] ^
        data_i[130] ^
        data_i[132] ^
        data_i[134] ^
        data_i[136] ^
        data_i[138] ^
        data_i[140] ^
        data_i[142] ^
        data_i[144] ^
        data_i[146] ^
        data_i[148] ^
        data_i[150] ^
        data_i[152] ^
        data_i[154] ^
        data_i[156] ^
        data_i[158] ^
        data_i[160] ^
        data_i[162] ^
        data_i[164] ^
        data_i[166] ^
        data_i[168] ^
        data_i[170] ^
        data_i[172] ^
        data_i[174] ^
        data_i[176] ^
        data_i[178] ^
        data_i[180] ^
        data_i[182] ^
        data_i[184] ^
        data_i[186] ^
        data_i[188] ^
        data_i[190] ^
        data_i[192] ^
        data_i[194] ^
        data_i[196] ^
        data_i[198] ^
        data_i[200] ^
        data_i[202] ^
        data_i[204] ^
        data_i[206] ^
        data_i[208] ^
        data_i[210] ^
        data_i[212] ^
        data_i[214] ^
        data_i[216] ^
        data_i[218] ^
        data_i[220] ^
        data_i[222] ^
        data_i[224] ^
        data_i[226] ^
        data_i[228] ^
        data_i[230] ^
        data_i[232] ^
        data_i[234] ^
        data_i[236] ^
        data_i[238] ^
        data_i[240] ^
        data_i[242] ^
        data_i[244] ^
        data_i[246] ^
        data_i[248] ^
        data_i[250] ^
        data_i[252] ^
        data_i[254];

    // check bit 1: 104 taps
    assign check_o[1] =
          data_i[0] ^
        data_i[3] ^
        data_i[7] ^
        data_i[10] ^
        data_i[13] ^
        data_i[16] ^
        data_i[20] ^
        data_i[24] ^
        data_i[27] ^
        data_i[30] ^
        data_i[34] ^
        data_i[36] ^
        data_i[40] ^
        data_i[43] ^
        data_i[47] ^
        data_i[49] ^
        data_i[54] ^
        data_i[56] ^
        data_i[60] ^
        data_i[64] ^
        data_i[67] ^
        data_i[70] ^
        data_i[74] ^
        data_i[76] ^
        data_i[80] ^
        data_i[84] ^
        data_i[86] ^
        data_i[90] ^
        data_i[93] ^
        data_i[97] ^
        data_i[100] ^
        data_i[103] ^
        data_i[108] ^
        data_i[112] ^
        data_i[115] ^
        data_i[118] ^
        data_i[120] ^
        data_i[122] ^
        data_i[124] ^
        data_i[126] ^
        data_i[128] ^
        data_i[130] ^
        data_i[132] ^
        data_i[134] ^
        data_i[136] ^
        data_i[138] ^
        data_i[140] ^
        data_i[142] ^
        data_i[144] ^
        data_i[146] ^
        data_i[148] ^
        data_i[150] ^
        data_i[152] ^
        data_i[154] ^
        data_i[156] ^
        data_i[158] ^
        data_i[160] ^
        data_i[162] ^
        data_i[164] ^
        data_i[166] ^
        data_i[168] ^
        data_i[170] ^
        data_i[172] ^
        data_i[174] ^
        data_i[176] ^
        data_i[178] ^
        data_i[180] ^
        data_i[182] ^
        data_i[184] ^
        data_i[186] ^
        data_i[188] ^
        data_i[190] ^
        data_i[192] ^
        data_i[194] ^
        data_i[196] ^
        data_i[198] ^
        data_i[200] ^
        data_i[202] ^
        data_i[204] ^
        data_i[206] ^
        data_i[208] ^
        data_i[210] ^
        data_i[212] ^
        data_i[214] ^
        data_i[216] ^
        data_i[218] ^
        data_i[220] ^
        data_i[222] ^
        data_i[224] ^
        data_i[226] ^
        data_i[228] ^
        data_i[230] ^
        data_i[233] ^
        data_i[235] ^
        data_i[237] ^
        data_i[239] ^
        data_i[241] ^
        data_i[243] ^
        data_i[245] ^
        data_i[247] ^
        data_i[249] ^
        data_i[251] ^
        data_i[253] ^
        data_i[255];

    // check bit 2: 104 taps
    assign check_o[2] =
          data_i[0] ^
        data_i[4] ^
        data_i[7] ^
        data_i[11] ^
        data_i[14] ^
        data_i[17] ^
        data_i[21] ^
        data_i[23] ^
        data_i[27] ^
        data_i[30] ^
        data_i[33] ^
        data_i[37] ^
        data_i[41] ^
        data_i[44] ^
        data_i[47] ^
        data_i[51] ^
        data_i[54] ^
        data_i[57] ^
        data_i[61] ^
        data_i[63] ^
        data_i[67] ^
        data_i[71] ^
        data_i[73] ^
        data_i[77] ^
        data_i[81] ^
        data_i[84] ^
        data_i[87] ^
        data_i[91] ^
        data_i[94] ^
        data_i[98] ^
        data_i[101] ^
        data_i[104] ^
        data_i[106] ^
        data_i[109] ^
        data_i[113] ^
        data_i[116] ^
        data_i[120] ^
        data_i[122] ^
        data_i[124] ^
        data_i[126] ^
        data_i[128] ^
        data_i[130] ^
        data_i[132] ^
        data_i[134] ^
        data_i[136] ^
        data_i[138] ^
        data_i[140] ^
        data_i[142] ^
        data_i[144] ^
        data_i[146] ^
        data_i[148] ^
        data_i[150] ^
        data_i[152] ^
        data_i[154] ^
        data_i[156] ^
        data_i[158] ^
        data_i[160] ^
        data_i[163] ^
        data_i[165] ^
        data_i[167] ^
        data_i[169] ^
        data_i[171] ^
        data_i[173] ^
        data_i[175] ^
        data_i[177] ^
        data_i[179] ^
        data_i[181] ^
        data_i[183] ^
        data_i[185] ^
        data_i[187] ^
        data_i[189] ^
        data_i[191] ^
        data_i[193] ^
        data_i[195] ^
        data_i[197] ^
        data_i[199] ^
        data_i[201] ^
        data_i[203] ^
        data_i[205] ^
        data_i[207] ^
        data_i[209] ^
        data_i[211] ^
        data_i[213] ^
        data_i[215] ^
        data_i[217] ^
        data_i[219] ^
        data_i[221] ^
        data_i[223] ^
        data_i[225] ^
        data_i[227] ^
        data_i[229] ^
        data_i[231] ^
        data_i[232] ^
        data_i[234] ^
        data_i[236] ^
        data_i[238] ^
        data_i[240] ^
        data_i[242] ^
        data_i[244] ^
        data_i[246] ^
        data_i[248] ^
        data_i[250] ^
        data_i[252] ^
        data_i[254];

    // check bit 3: 104 taps
    assign check_o[3] =
          data_i[1] ^
        data_i[4] ^
        data_i[7] ^
        data_i[10] ^
        data_i[14] ^
        data_i[17] ^
        data_i[21] ^
        data_i[24] ^
        data_i[28] ^
        data_i[31] ^
        data_i[34] ^
        data_i[38] ^
        data_i[40] ^
        data_i[44] ^
        data_i[48] ^
        data_i[50] ^
        data_i[53] ^
        data_i[58] ^
        data_i[61] ^
        data_i[64] ^
        data_i[68] ^
        data_i[71] ^
        data_i[74] ^
        data_i[78] ^
        data_i[82] ^
        data_i[85] ^
        data_i[88] ^
        data_i[92] ^
        data_i[95] ^
        data_i[97] ^
        data_i[102] ^
        data_i[105] ^
        data_i[107] ^
        data_i[110] ^
        data_i[114] ^
        data_i[117] ^
        data_i[120] ^
        data_i[122] ^
        data_i[124] ^
        data_i[126] ^
        data_i[128] ^
        data_i[130] ^
        data_i[133] ^
        data_i[135] ^
        data_i[137] ^
        data_i[139] ^
        data_i[141] ^
        data_i[143] ^
        data_i[145] ^
        data_i[147] ^
        data_i[149] ^
        data_i[151] ^
        data_i[153] ^
        data_i[155] ^
        data_i[157] ^
        data_i[159] ^
        data_i[161] ^
        data_i[162] ^
        data_i[164] ^
        data_i[166] ^
        data_i[168] ^
        data_i[170] ^
        data_i[172] ^
        data_i[174] ^
        data_i[176] ^
        data_i[178] ^
        data_i[180] ^
        data_i[182] ^
        data_i[184] ^
        data_i[186] ^
        data_i[188] ^
        data_i[190] ^
        data_i[193] ^
        data_i[195] ^
        data_i[197] ^
        data_i[199] ^
        data_i[201] ^
        data_i[203] ^
        data_i[205] ^
        data_i[207] ^
        data_i[209] ^
        data_i[211] ^
        data_i[213] ^
        data_i[215] ^
        data_i[217] ^
        data_i[219] ^
        data_i[221] ^
        data_i[223] ^
        data_i[225] ^
        data_i[227] ^
        data_i[229] ^
        data_i[231] ^
        data_i[232] ^
        data_i[234] ^
        data_i[236] ^
        data_i[238] ^
        data_i[240] ^
        data_i[242] ^
        data_i[244] ^
        data_i[246] ^
        data_i[248] ^
        data_i[250] ^
        data_i[252] ^
        data_i[254];

    // check bit 4: 104 taps
    assign check_o[4] =
          data_i[1] ^
        data_i[4] ^
        data_i[8] ^
        data_i[11] ^
        data_i[15] ^
        data_i[18] ^
        data_i[20] ^
        data_i[24] ^
        data_i[27] ^
        data_i[31] ^
        data_i[35] ^
        data_i[37] ^
        data_i[41] ^
        data_i[45] ^
        data_i[48] ^
        data_i[51] ^
        data_i[55] ^
        data_i[58] ^
        data_i[60] ^
        data_i[65] ^
        data_i[68] ^
        data_i[70] ^
        data_i[75] ^
        data_i[79] ^
        data_i[81] ^
        data_i[83] ^
        data_i[89] ^
        data_i[91] ^
        data_i[96] ^
        data_i[99] ^
        data_i[102] ^
        data_i[103] ^
        data_i[108] ^
        data_i[111] ^
        data_i[115] ^
        data_i[119] ^
        data_i[120] ^
        data_i[123] ^
        data_i[125] ^
        data_i[127] ^
        data_i[129] ^
        data_i[131] ^
        data_i[132] ^
        data_i[134] ^
        data_i[136] ^
        data_i[138] ^
        data_i[140] ^
        data_i[143] ^
        data_i[145] ^
        data_i[147] ^
        data_i[149] ^
        data_i[151] ^
        data_i[153] ^
        data_i[155] ^
        data_i[157] ^
        data_i[159] ^
        data_i[161] ^
        data_i[162] ^
        data_i[164] ^
        data_i[166] ^
        data_i[168] ^
        data_i[170] ^
        data_i[173] ^
        data_i[175] ^
        data_i[177] ^
        data_i[179] ^
        data_i[181] ^
        data_i[183] ^
        data_i[185] ^
        data_i[187] ^
        data_i[189] ^
        data_i[191] ^
        data_i[192] ^
        data_i[194] ^
        data_i[196] ^
        data_i[198] ^
        data_i[200] ^
        data_i[202] ^
        data_i[204] ^
        data_i[206] ^
        data_i[208] ^
        data_i[210] ^
        data_i[213] ^
        data_i[215] ^
        data_i[217] ^
        data_i[219] ^
        data_i[221] ^
        data_i[223] ^
        data_i[225] ^
        data_i[227] ^
        data_i[229] ^
        data_i[231] ^
        data_i[232] ^
        data_i[234] ^
        data_i[236] ^
        data_i[238] ^
        data_i[240] ^
        data_i[243] ^
        data_i[245] ^
        data_i[247] ^
        data_i[249] ^
        data_i[251] ^
        data_i[253] ^
        data_i[255];

    // check bit 5: 104 taps
    assign check_o[5] =
          data_i[1] ^
        data_i[5] ^
        data_i[8] ^
        data_i[11] ^
        data_i[14] ^
        data_i[18] ^
        data_i[22] ^
        data_i[25] ^
        data_i[28] ^
        data_i[32] ^
        data_i[34] ^
        data_i[38] ^
        data_i[42] ^
        data_i[45] ^
        data_i[47] ^
        data_i[52] ^
        data_i[55] ^
        data_i[57] ^
        data_i[62] ^
        data_i[66] ^
        data_i[69] ^
        data_i[72] ^
        data_i[76] ^
        data_i[78] ^
        data_i[80] ^
        data_i[85] ^
        data_i[89] ^
        data_i[90] ^
        data_i[94] ^
        data_i[98] ^
        data_i[101] ^
        data_i[104] ^
        data_i[107] ^
        data_i[112] ^
        data_i[115] ^
        data_i[118] ^
        data_i[121] ^
        data_i[122] ^
        data_i[125] ^
        data_i[127] ^
        data_i[129] ^
        data_i[131] ^
        data_i[132] ^
        data_i[135] ^
        data_i[137] ^
        data_i[139] ^
        data_i[141] ^
        data_i[142] ^
        data_i[144] ^
        data_i[146] ^
        data_i[148] ^
        data_i[151] ^
        data_i[153] ^
        data_i[155] ^
        data_i[157] ^
        data_i[159] ^
        data_i[161] ^
        data_i[162] ^
        data_i[165] ^
        data_i[167] ^
        data_i[169] ^
        data_i[171] ^
        data_i[172] ^
        data_i[174] ^
        data_i[176] ^
        data_i[178] ^
        data_i[181] ^
        data_i[183] ^
        data_i[185] ^
        data_i[187] ^
        data_i[189] ^
        data_i[191] ^
        data_i[192] ^
        data_i[194] ^
        data_i[196] ^
        data_i[198] ^
        data_i[201] ^
        data_i[203] ^
        data_i[205] ^
        data_i[207] ^
        data_i[209] ^
        data_i[211] ^
        data_i[212] ^
        data_i[214] ^
        data_i[216] ^
        data_i[218] ^
        data_i[220] ^
        data_i[222] ^
        data_i[225] ^
        data_i[227] ^
        data_i[229] ^
        data_i[231] ^
        data_i[232] ^
        data_i[235] ^
        data_i[237] ^
        data_i[239] ^
        data_i[241] ^
        data_i[242] ^
        data_i[244] ^
        data_i[246] ^
        data_i[248] ^
        data_i[251] ^
        data_i[253] ^
        data_i[255];

    // check bit 6: 104 taps
    assign check_o[6] =
          data_i[2] ^
        data_i[5] ^
        data_i[8] ^
        data_i[12] ^
        data_i[15] ^
        data_i[19] ^
        data_i[21] ^
        data_i[25] ^
        data_i[28] ^
        data_i[31] ^
        data_i[35] ^
        data_i[39] ^
        data_i[41] ^
        data_i[46] ^
        data_i[49] ^
        data_i[52] ^
        data_i[54] ^
        data_i[59] ^
        data_i[62] ^
        data_i[64] ^
        data_i[70] ^
        data_i[73] ^
        data_i[75] ^
        data_i[77] ^
        data_i[82] ^
        data_i[86] ^
        data_i[88] ^
        data_i[93] ^
        data_i[94] ^
        data_i[99] ^
        data_i[100] ^
        data_i[105] ^
        data_i[109] ^
        data_i[112] ^
        data_i[113] ^
        data_i[117] ^
        data_i[121] ^
        data_i[123] ^
        data_i[124] ^
        data_i[127] ^
        data_i[129] ^
        data_i[131] ^
        data_i[133] ^
        data_i[134] ^
        data_i[137] ^
        data_i[139] ^
        data_i[141] ^
        data_i[142] ^
        data_i[145] ^
        data_i[147] ^
        data_i[149] ^
        data_i[150] ^
        data_i[152] ^
        data_i[154] ^
        data_i[157] ^
        data_i[159] ^
        data_i[161] ^
        data_i[163] ^
        data_i[164] ^
        data_i[167] ^
        data_i[169] ^
        data_i[171] ^
        data_i[172] ^
        data_i[175] ^
        data_i[177] ^
        data_i[179] ^
        data_i[180] ^
        data_i[182] ^
        data_i[184] ^
        data_i[187] ^
        data_i[189] ^
        data_i[191] ^
        data_i[192] ^
        data_i[195] ^
        data_i[197] ^
        data_i[199] ^
        data_i[200] ^
        data_i[202] ^
        data_i[204] ^
        data_i[207] ^
        data_i[209] ^
        data_i[211] ^
        data_i[212] ^
        data_i[214] ^
        data_i[216] ^
        data_i[219] ^
        data_i[221] ^
        data_i[223] ^
        data_i[224] ^
        data_i[226] ^
        data_i[228] ^
        data_i[231] ^
        data_i[233] ^
        data_i[234] ^
        data_i[237] ^
        data_i[239] ^
        data_i[241] ^
        data_i[242] ^
        data_i[245] ^
        data_i[247] ^
        data_i[249] ^
        data_i[250] ^
        data_i[252] ^
        data_i[254];

    // check bit 7: 104 taps
    assign check_o[7] =
          data_i[2] ^
        data_i[5] ^
        data_i[9] ^
        data_i[12] ^
        data_i[15] ^
        data_i[18] ^
        data_i[22] ^
        data_i[26] ^
        data_i[29] ^
        data_i[32] ^
        data_i[36] ^
        data_i[38] ^
        data_i[43] ^
        data_i[44] ^
        data_i[48] ^
        data_i[51] ^
        data_i[56] ^
        data_i[59] ^
        data_i[63] ^
        data_i[65] ^
        data_i[67] ^
        data_i[72] ^
        data_i[74] ^
        data_i[79] ^
        data_i[82] ^
        data_i[86] ^
        data_i[87] ^
        data_i[92] ^
        data_i[95] ^
        data_i[98] ^
        data_i[103] ^
        data_i[106] ^
        data_i[109] ^
        data_i[111] ^
        data_i[114] ^
        data_i[118] ^
        data_i[121] ^
        data_i[123] ^
        data_i[125] ^
        data_i[126] ^
        data_i[129] ^
        data_i[131] ^
        data_i[133] ^
        data_i[135] ^
        data_i[136] ^
        data_i[139] ^
        data_i[141] ^
        data_i[143] ^
        data_i[144] ^
        data_i[147] ^
        data_i[149] ^
        data_i[150] ^
        data_i[153] ^
        data_i[155] ^
        data_i[156] ^
        data_i[158] ^
        data_i[161] ^
        data_i[163] ^
        data_i[165] ^
        data_i[166] ^
        data_i[169] ^
        data_i[171] ^
        data_i[173] ^
        data_i[174] ^
        data_i[177] ^
        data_i[179] ^
        data_i[180] ^
        data_i[183] ^
        data_i[185] ^
        data_i[186] ^
        data_i[188] ^
        data_i[191] ^
        data_i[193] ^
        data_i[194] ^
        data_i[197] ^
        data_i[199] ^
        data_i[200] ^
        data_i[203] ^
        data_i[205] ^
        data_i[206] ^
        data_i[208] ^
        data_i[211] ^
        data_i[212] ^
        data_i[215] ^
        data_i[217] ^
        data_i[218] ^
        data_i[220] ^
        data_i[223] ^
        data_i[224] ^
        data_i[226] ^
        data_i[229] ^
        data_i[230] ^
        data_i[233] ^
        data_i[235] ^
        data_i[236] ^
        data_i[239] ^
        data_i[241] ^
        data_i[243] ^
        data_i[244] ^
        data_i[247] ^
        data_i[249] ^
        data_i[250] ^
        data_i[253] ^
        data_i[255];

    // check bit 8: 104 taps
    assign check_o[8] =
          data_i[2] ^
        data_i[6] ^
        data_i[9] ^
        data_i[13] ^
        data_i[16] ^
        data_i[19] ^
        data_i[22] ^
        data_i[25] ^
        data_i[29] ^
        data_i[33] ^
        data_i[35] ^
        data_i[39] ^
        data_i[42] ^
        data_i[45] ^
        data_i[49] ^
        data_i[53] ^
        data_i[56] ^
        data_i[58] ^
        data_i[61] ^
        data_i[65] ^
        data_i[69] ^
        data_i[73] ^
        data_i[76] ^
        data_i[78] ^
        data_i[81] ^
        data_i[84] ^
        data_i[88] ^
        data_i[92] ^
        data_i[96] ^
        data_i[97] ^
        data_i[101] ^
        data_i[106] ^
        data_i[108] ^
        data_i[110] ^
        data_i[116] ^
        data_i[119] ^
        data_i[121] ^
        data_i[123] ^
        data_i[125] ^
        data_i[127] ^
        data_i[128] ^
        data_i[131] ^
        data_i[133] ^
        data_i[135] ^
        data_i[137] ^
        data_i[138] ^
        data_i[141] ^
        data_i[143] ^
        data_i[145] ^
        data_i[146] ^
        data_i[149] ^
        data_i[151] ^
        data_i[152] ^
        data_i[155] ^
        data_i[156] ^
        data_i[159] ^
        data_i[160] ^
        data_i[163] ^
        data_i[165] ^
        data_i[167] ^
        data_i[168] ^
        data_i[171] ^
        data_i[173] ^
        data_i[175] ^
        data_i[176] ^
        data_i[179] ^
        data_i[181] ^
        data_i[182] ^
        data_i[185] ^
        data_i[186] ^
        data_i[189] ^
        data_i[190] ^
        data_i[193] ^
        data_i[195] ^
        data_i[196] ^
        data_i[199] ^
        data_i[201] ^
        data_i[202] ^
        data_i[205] ^
        data_i[206] ^
        data_i[209] ^
        data_i[210] ^
        data_i[213] ^
        data_i[214] ^
        data_i[217] ^
        data_i[218] ^
        data_i[221] ^
        data_i[222] ^
        data_i[224] ^
        data_i[227] ^
        data_i[228] ^
        data_i[230] ^
        data_i[233] ^
        data_i[235] ^
        data_i[237] ^
        data_i[238] ^
        data_i[241] ^
        data_i[243] ^
        data_i[245] ^
        data_i[246] ^
        data_i[249] ^
        data_i[251] ^
        data_i[252] ^
        data_i[255];

    // check bit 9: 104 taps
    assign check_o[9] =
          data_i[3] ^
        data_i[6] ^
        data_i[9] ^
        data_i[12] ^
        data_i[16] ^
        data_i[19] ^
        data_i[23] ^
        data_i[26] ^
        data_i[30] ^
        data_i[32] ^
        data_i[36] ^
        data_i[40] ^
        data_i[42] ^
        data_i[46] ^
        data_i[50] ^
        data_i[52] ^
        data_i[55] ^
        data_i[60] ^
        data_i[63] ^
        data_i[66] ^
        data_i[68] ^
        data_i[71] ^
        data_i[75] ^
        data_i[79] ^
        data_i[83] ^
        data_i[85] ^
        data_i[90] ^
        data_i[91] ^
        data_i[95] ^
        data_i[100] ^
        data_i[104] ^
        data_i[105] ^
        data_i[110] ^
        data_i[113] ^
        data_i[116] ^
        data_i[119] ^
        data_i[121] ^
        data_i[123] ^
        data_i[125] ^
        data_i[127] ^
        data_i[129] ^
        data_i[130] ^
        data_i[133] ^
        data_i[135] ^
        data_i[137] ^
        data_i[139] ^
        data_i[140] ^
        data_i[143] ^
        data_i[145] ^
        data_i[147] ^
        data_i[148] ^
        data_i[151] ^
        data_i[153] ^
        data_i[154] ^
        data_i[157] ^
        data_i[158] ^
        data_i[160] ^
        data_i[163] ^
        data_i[165] ^
        data_i[167] ^
        data_i[169] ^
        data_i[170] ^
        data_i[173] ^
        data_i[175] ^
        data_i[177] ^
        data_i[178] ^
        data_i[181] ^
        data_i[183] ^
        data_i[184] ^
        data_i[187] ^
        data_i[188] ^
        data_i[190] ^
        data_i[193] ^
        data_i[195] ^
        data_i[197] ^
        data_i[198] ^
        data_i[201] ^
        data_i[203] ^
        data_i[204] ^
        data_i[207] ^
        data_i[208] ^
        data_i[210] ^
        data_i[213] ^
        data_i[215] ^
        data_i[216] ^
        data_i[219] ^
        data_i[220] ^
        data_i[222] ^
        data_i[225] ^
        data_i[226] ^
        data_i[228] ^
        data_i[230] ^
        data_i[233] ^
        data_i[235] ^
        data_i[237] ^
        data_i[239] ^
        data_i[240] ^
        data_i[243] ^
        data_i[245] ^
        data_i[247] ^
        data_i[248] ^
        data_i[251] ^
        data_i[253] ^
        data_i[254];

endmodule

module vc3d_secded_dec_256 (
    input  wire [255:0] data_i,
    input  wire [9:0] check_i,
    input  wire poison_i,
    output wire [255:0] data_o,
    output wire [9:0] syndrome_o,
    output wire ce_o,           // corrected single-bit error
    output wire ue_o,           // uncorrectable (double bit) error
    output wire ce_in_check_o,  // the corrected bit was a check bit
    output wire poison_o
);

    wire [9:0] syndrome;
    assign syndrome[0] = check_i[0]
        ^ data_i[0]
        ^ data_i[3]
        ^ data_i[6]
        ^ data_i[10]
        ^ data_i[13]
        ^ data_i[17]
        ^ data_i[20]
        ^ data_i[23]
        ^ data_i[26]
        ^ data_i[29]
        ^ data_i[33]
        ^ data_i[37]
        ^ data_i[39]
        ^ data_i[43]
        ^ data_i[46]
        ^ data_i[50]
        ^ data_i[53]
        ^ data_i[57]
        ^ data_i[59]
        ^ data_i[62]
        ^ data_i[66]
        ^ data_i[69]
        ^ data_i[72]
        ^ data_i[77]
        ^ data_i[80]
        ^ data_i[83]
        ^ data_i[87]
        ^ data_i[89]
        ^ data_i[93]
        ^ data_i[96]
        ^ data_i[99]
        ^ data_i[102]
        ^ data_i[107]
        ^ data_i[111]
        ^ data_i[114]
        ^ data_i[117]
        ^ data_i[120]
        ^ data_i[122]
        ^ data_i[124]
        ^ data_i[126]
        ^ data_i[128]
        ^ data_i[130]
        ^ data_i[132]
        ^ data_i[134]
        ^ data_i[136]
        ^ data_i[138]
        ^ data_i[140]
        ^ data_i[142]
        ^ data_i[144]
        ^ data_i[146]
        ^ data_i[148]
        ^ data_i[150]
        ^ data_i[152]
        ^ data_i[154]
        ^ data_i[156]
        ^ data_i[158]
        ^ data_i[160]
        ^ data_i[162]
        ^ data_i[164]
        ^ data_i[166]
        ^ data_i[168]
        ^ data_i[170]
        ^ data_i[172]
        ^ data_i[174]
        ^ data_i[176]
        ^ data_i[178]
        ^ data_i[180]
        ^ data_i[182]
        ^ data_i[184]
        ^ data_i[186]
        ^ data_i[188]
        ^ data_i[190]
        ^ data_i[192]
        ^ data_i[194]
        ^ data_i[196]
        ^ data_i[198]
        ^ data_i[200]
        ^ data_i[202]
        ^ data_i[204]
        ^ data_i[206]
        ^ data_i[208]
        ^ data_i[210]
        ^ data_i[212]
        ^ data_i[214]
        ^ data_i[216]
        ^ data_i[218]
        ^ data_i[220]
        ^ data_i[222]
        ^ data_i[224]
        ^ data_i[226]
        ^ data_i[228]
        ^ data_i[230]
        ^ data_i[232]
        ^ data_i[234]
        ^ data_i[236]
        ^ data_i[238]
        ^ data_i[240]
        ^ data_i[242]
        ^ data_i[244]
        ^ data_i[246]
        ^ data_i[248]
        ^ data_i[250]
        ^ data_i[252]
        ^ data_i[254]
        ;
    assign syndrome[1] = check_i[1]
        ^ data_i[0]
        ^ data_i[3]
        ^ data_i[7]
        ^ data_i[10]
        ^ data_i[13]
        ^ data_i[16]
        ^ data_i[20]
        ^ data_i[24]
        ^ data_i[27]
        ^ data_i[30]
        ^ data_i[34]
        ^ data_i[36]
        ^ data_i[40]
        ^ data_i[43]
        ^ data_i[47]
        ^ data_i[49]
        ^ data_i[54]
        ^ data_i[56]
        ^ data_i[60]
        ^ data_i[64]
        ^ data_i[67]
        ^ data_i[70]
        ^ data_i[74]
        ^ data_i[76]
        ^ data_i[80]
        ^ data_i[84]
        ^ data_i[86]
        ^ data_i[90]
        ^ data_i[93]
        ^ data_i[97]
        ^ data_i[100]
        ^ data_i[103]
        ^ data_i[108]
        ^ data_i[112]
        ^ data_i[115]
        ^ data_i[118]
        ^ data_i[120]
        ^ data_i[122]
        ^ data_i[124]
        ^ data_i[126]
        ^ data_i[128]
        ^ data_i[130]
        ^ data_i[132]
        ^ data_i[134]
        ^ data_i[136]
        ^ data_i[138]
        ^ data_i[140]
        ^ data_i[142]
        ^ data_i[144]
        ^ data_i[146]
        ^ data_i[148]
        ^ data_i[150]
        ^ data_i[152]
        ^ data_i[154]
        ^ data_i[156]
        ^ data_i[158]
        ^ data_i[160]
        ^ data_i[162]
        ^ data_i[164]
        ^ data_i[166]
        ^ data_i[168]
        ^ data_i[170]
        ^ data_i[172]
        ^ data_i[174]
        ^ data_i[176]
        ^ data_i[178]
        ^ data_i[180]
        ^ data_i[182]
        ^ data_i[184]
        ^ data_i[186]
        ^ data_i[188]
        ^ data_i[190]
        ^ data_i[192]
        ^ data_i[194]
        ^ data_i[196]
        ^ data_i[198]
        ^ data_i[200]
        ^ data_i[202]
        ^ data_i[204]
        ^ data_i[206]
        ^ data_i[208]
        ^ data_i[210]
        ^ data_i[212]
        ^ data_i[214]
        ^ data_i[216]
        ^ data_i[218]
        ^ data_i[220]
        ^ data_i[222]
        ^ data_i[224]
        ^ data_i[226]
        ^ data_i[228]
        ^ data_i[230]
        ^ data_i[233]
        ^ data_i[235]
        ^ data_i[237]
        ^ data_i[239]
        ^ data_i[241]
        ^ data_i[243]
        ^ data_i[245]
        ^ data_i[247]
        ^ data_i[249]
        ^ data_i[251]
        ^ data_i[253]
        ^ data_i[255]
        ;
    assign syndrome[2] = check_i[2]
        ^ data_i[0]
        ^ data_i[4]
        ^ data_i[7]
        ^ data_i[11]
        ^ data_i[14]
        ^ data_i[17]
        ^ data_i[21]
        ^ data_i[23]
        ^ data_i[27]
        ^ data_i[30]
        ^ data_i[33]
        ^ data_i[37]
        ^ data_i[41]
        ^ data_i[44]
        ^ data_i[47]
        ^ data_i[51]
        ^ data_i[54]
        ^ data_i[57]
        ^ data_i[61]
        ^ data_i[63]
        ^ data_i[67]
        ^ data_i[71]
        ^ data_i[73]
        ^ data_i[77]
        ^ data_i[81]
        ^ data_i[84]
        ^ data_i[87]
        ^ data_i[91]
        ^ data_i[94]
        ^ data_i[98]
        ^ data_i[101]
        ^ data_i[104]
        ^ data_i[106]
        ^ data_i[109]
        ^ data_i[113]
        ^ data_i[116]
        ^ data_i[120]
        ^ data_i[122]
        ^ data_i[124]
        ^ data_i[126]
        ^ data_i[128]
        ^ data_i[130]
        ^ data_i[132]
        ^ data_i[134]
        ^ data_i[136]
        ^ data_i[138]
        ^ data_i[140]
        ^ data_i[142]
        ^ data_i[144]
        ^ data_i[146]
        ^ data_i[148]
        ^ data_i[150]
        ^ data_i[152]
        ^ data_i[154]
        ^ data_i[156]
        ^ data_i[158]
        ^ data_i[160]
        ^ data_i[163]
        ^ data_i[165]
        ^ data_i[167]
        ^ data_i[169]
        ^ data_i[171]
        ^ data_i[173]
        ^ data_i[175]
        ^ data_i[177]
        ^ data_i[179]
        ^ data_i[181]
        ^ data_i[183]
        ^ data_i[185]
        ^ data_i[187]
        ^ data_i[189]
        ^ data_i[191]
        ^ data_i[193]
        ^ data_i[195]
        ^ data_i[197]
        ^ data_i[199]
        ^ data_i[201]
        ^ data_i[203]
        ^ data_i[205]
        ^ data_i[207]
        ^ data_i[209]
        ^ data_i[211]
        ^ data_i[213]
        ^ data_i[215]
        ^ data_i[217]
        ^ data_i[219]
        ^ data_i[221]
        ^ data_i[223]
        ^ data_i[225]
        ^ data_i[227]
        ^ data_i[229]
        ^ data_i[231]
        ^ data_i[232]
        ^ data_i[234]
        ^ data_i[236]
        ^ data_i[238]
        ^ data_i[240]
        ^ data_i[242]
        ^ data_i[244]
        ^ data_i[246]
        ^ data_i[248]
        ^ data_i[250]
        ^ data_i[252]
        ^ data_i[254]
        ;
    assign syndrome[3] = check_i[3]
        ^ data_i[1]
        ^ data_i[4]
        ^ data_i[7]
        ^ data_i[10]
        ^ data_i[14]
        ^ data_i[17]
        ^ data_i[21]
        ^ data_i[24]
        ^ data_i[28]
        ^ data_i[31]
        ^ data_i[34]
        ^ data_i[38]
        ^ data_i[40]
        ^ data_i[44]
        ^ data_i[48]
        ^ data_i[50]
        ^ data_i[53]
        ^ data_i[58]
        ^ data_i[61]
        ^ data_i[64]
        ^ data_i[68]
        ^ data_i[71]
        ^ data_i[74]
        ^ data_i[78]
        ^ data_i[82]
        ^ data_i[85]
        ^ data_i[88]
        ^ data_i[92]
        ^ data_i[95]
        ^ data_i[97]
        ^ data_i[102]
        ^ data_i[105]
        ^ data_i[107]
        ^ data_i[110]
        ^ data_i[114]
        ^ data_i[117]
        ^ data_i[120]
        ^ data_i[122]
        ^ data_i[124]
        ^ data_i[126]
        ^ data_i[128]
        ^ data_i[130]
        ^ data_i[133]
        ^ data_i[135]
        ^ data_i[137]
        ^ data_i[139]
        ^ data_i[141]
        ^ data_i[143]
        ^ data_i[145]
        ^ data_i[147]
        ^ data_i[149]
        ^ data_i[151]
        ^ data_i[153]
        ^ data_i[155]
        ^ data_i[157]
        ^ data_i[159]
        ^ data_i[161]
        ^ data_i[162]
        ^ data_i[164]
        ^ data_i[166]
        ^ data_i[168]
        ^ data_i[170]
        ^ data_i[172]
        ^ data_i[174]
        ^ data_i[176]
        ^ data_i[178]
        ^ data_i[180]
        ^ data_i[182]
        ^ data_i[184]
        ^ data_i[186]
        ^ data_i[188]
        ^ data_i[190]
        ^ data_i[193]
        ^ data_i[195]
        ^ data_i[197]
        ^ data_i[199]
        ^ data_i[201]
        ^ data_i[203]
        ^ data_i[205]
        ^ data_i[207]
        ^ data_i[209]
        ^ data_i[211]
        ^ data_i[213]
        ^ data_i[215]
        ^ data_i[217]
        ^ data_i[219]
        ^ data_i[221]
        ^ data_i[223]
        ^ data_i[225]
        ^ data_i[227]
        ^ data_i[229]
        ^ data_i[231]
        ^ data_i[232]
        ^ data_i[234]
        ^ data_i[236]
        ^ data_i[238]
        ^ data_i[240]
        ^ data_i[242]
        ^ data_i[244]
        ^ data_i[246]
        ^ data_i[248]
        ^ data_i[250]
        ^ data_i[252]
        ^ data_i[254]
        ;
    assign syndrome[4] = check_i[4]
        ^ data_i[1]
        ^ data_i[4]
        ^ data_i[8]
        ^ data_i[11]
        ^ data_i[15]
        ^ data_i[18]
        ^ data_i[20]
        ^ data_i[24]
        ^ data_i[27]
        ^ data_i[31]
        ^ data_i[35]
        ^ data_i[37]
        ^ data_i[41]
        ^ data_i[45]
        ^ data_i[48]
        ^ data_i[51]
        ^ data_i[55]
        ^ data_i[58]
        ^ data_i[60]
        ^ data_i[65]
        ^ data_i[68]
        ^ data_i[70]
        ^ data_i[75]
        ^ data_i[79]
        ^ data_i[81]
        ^ data_i[83]
        ^ data_i[89]
        ^ data_i[91]
        ^ data_i[96]
        ^ data_i[99]
        ^ data_i[102]
        ^ data_i[103]
        ^ data_i[108]
        ^ data_i[111]
        ^ data_i[115]
        ^ data_i[119]
        ^ data_i[120]
        ^ data_i[123]
        ^ data_i[125]
        ^ data_i[127]
        ^ data_i[129]
        ^ data_i[131]
        ^ data_i[132]
        ^ data_i[134]
        ^ data_i[136]
        ^ data_i[138]
        ^ data_i[140]
        ^ data_i[143]
        ^ data_i[145]
        ^ data_i[147]
        ^ data_i[149]
        ^ data_i[151]
        ^ data_i[153]
        ^ data_i[155]
        ^ data_i[157]
        ^ data_i[159]
        ^ data_i[161]
        ^ data_i[162]
        ^ data_i[164]
        ^ data_i[166]
        ^ data_i[168]
        ^ data_i[170]
        ^ data_i[173]
        ^ data_i[175]
        ^ data_i[177]
        ^ data_i[179]
        ^ data_i[181]
        ^ data_i[183]
        ^ data_i[185]
        ^ data_i[187]
        ^ data_i[189]
        ^ data_i[191]
        ^ data_i[192]
        ^ data_i[194]
        ^ data_i[196]
        ^ data_i[198]
        ^ data_i[200]
        ^ data_i[202]
        ^ data_i[204]
        ^ data_i[206]
        ^ data_i[208]
        ^ data_i[210]
        ^ data_i[213]
        ^ data_i[215]
        ^ data_i[217]
        ^ data_i[219]
        ^ data_i[221]
        ^ data_i[223]
        ^ data_i[225]
        ^ data_i[227]
        ^ data_i[229]
        ^ data_i[231]
        ^ data_i[232]
        ^ data_i[234]
        ^ data_i[236]
        ^ data_i[238]
        ^ data_i[240]
        ^ data_i[243]
        ^ data_i[245]
        ^ data_i[247]
        ^ data_i[249]
        ^ data_i[251]
        ^ data_i[253]
        ^ data_i[255]
        ;
    assign syndrome[5] = check_i[5]
        ^ data_i[1]
        ^ data_i[5]
        ^ data_i[8]
        ^ data_i[11]
        ^ data_i[14]
        ^ data_i[18]
        ^ data_i[22]
        ^ data_i[25]
        ^ data_i[28]
        ^ data_i[32]
        ^ data_i[34]
        ^ data_i[38]
        ^ data_i[42]
        ^ data_i[45]
        ^ data_i[47]
        ^ data_i[52]
        ^ data_i[55]
        ^ data_i[57]
        ^ data_i[62]
        ^ data_i[66]
        ^ data_i[69]
        ^ data_i[72]
        ^ data_i[76]
        ^ data_i[78]
        ^ data_i[80]
        ^ data_i[85]
        ^ data_i[89]
        ^ data_i[90]
        ^ data_i[94]
        ^ data_i[98]
        ^ data_i[101]
        ^ data_i[104]
        ^ data_i[107]
        ^ data_i[112]
        ^ data_i[115]
        ^ data_i[118]
        ^ data_i[121]
        ^ data_i[122]
        ^ data_i[125]
        ^ data_i[127]
        ^ data_i[129]
        ^ data_i[131]
        ^ data_i[132]
        ^ data_i[135]
        ^ data_i[137]
        ^ data_i[139]
        ^ data_i[141]
        ^ data_i[142]
        ^ data_i[144]
        ^ data_i[146]
        ^ data_i[148]
        ^ data_i[151]
        ^ data_i[153]
        ^ data_i[155]
        ^ data_i[157]
        ^ data_i[159]
        ^ data_i[161]
        ^ data_i[162]
        ^ data_i[165]
        ^ data_i[167]
        ^ data_i[169]
        ^ data_i[171]
        ^ data_i[172]
        ^ data_i[174]
        ^ data_i[176]
        ^ data_i[178]
        ^ data_i[181]
        ^ data_i[183]
        ^ data_i[185]
        ^ data_i[187]
        ^ data_i[189]
        ^ data_i[191]
        ^ data_i[192]
        ^ data_i[194]
        ^ data_i[196]
        ^ data_i[198]
        ^ data_i[201]
        ^ data_i[203]
        ^ data_i[205]
        ^ data_i[207]
        ^ data_i[209]
        ^ data_i[211]
        ^ data_i[212]
        ^ data_i[214]
        ^ data_i[216]
        ^ data_i[218]
        ^ data_i[220]
        ^ data_i[222]
        ^ data_i[225]
        ^ data_i[227]
        ^ data_i[229]
        ^ data_i[231]
        ^ data_i[232]
        ^ data_i[235]
        ^ data_i[237]
        ^ data_i[239]
        ^ data_i[241]
        ^ data_i[242]
        ^ data_i[244]
        ^ data_i[246]
        ^ data_i[248]
        ^ data_i[251]
        ^ data_i[253]
        ^ data_i[255]
        ;
    assign syndrome[6] = check_i[6]
        ^ data_i[2]
        ^ data_i[5]
        ^ data_i[8]
        ^ data_i[12]
        ^ data_i[15]
        ^ data_i[19]
        ^ data_i[21]
        ^ data_i[25]
        ^ data_i[28]
        ^ data_i[31]
        ^ data_i[35]
        ^ data_i[39]
        ^ data_i[41]
        ^ data_i[46]
        ^ data_i[49]
        ^ data_i[52]
        ^ data_i[54]
        ^ data_i[59]
        ^ data_i[62]
        ^ data_i[64]
        ^ data_i[70]
        ^ data_i[73]
        ^ data_i[75]
        ^ data_i[77]
        ^ data_i[82]
        ^ data_i[86]
        ^ data_i[88]
        ^ data_i[93]
        ^ data_i[94]
        ^ data_i[99]
        ^ data_i[100]
        ^ data_i[105]
        ^ data_i[109]
        ^ data_i[112]
        ^ data_i[113]
        ^ data_i[117]
        ^ data_i[121]
        ^ data_i[123]
        ^ data_i[124]
        ^ data_i[127]
        ^ data_i[129]
        ^ data_i[131]
        ^ data_i[133]
        ^ data_i[134]
        ^ data_i[137]
        ^ data_i[139]
        ^ data_i[141]
        ^ data_i[142]
        ^ data_i[145]
        ^ data_i[147]
        ^ data_i[149]
        ^ data_i[150]
        ^ data_i[152]
        ^ data_i[154]
        ^ data_i[157]
        ^ data_i[159]
        ^ data_i[161]
        ^ data_i[163]
        ^ data_i[164]
        ^ data_i[167]
        ^ data_i[169]
        ^ data_i[171]
        ^ data_i[172]
        ^ data_i[175]
        ^ data_i[177]
        ^ data_i[179]
        ^ data_i[180]
        ^ data_i[182]
        ^ data_i[184]
        ^ data_i[187]
        ^ data_i[189]
        ^ data_i[191]
        ^ data_i[192]
        ^ data_i[195]
        ^ data_i[197]
        ^ data_i[199]
        ^ data_i[200]
        ^ data_i[202]
        ^ data_i[204]
        ^ data_i[207]
        ^ data_i[209]
        ^ data_i[211]
        ^ data_i[212]
        ^ data_i[214]
        ^ data_i[216]
        ^ data_i[219]
        ^ data_i[221]
        ^ data_i[223]
        ^ data_i[224]
        ^ data_i[226]
        ^ data_i[228]
        ^ data_i[231]
        ^ data_i[233]
        ^ data_i[234]
        ^ data_i[237]
        ^ data_i[239]
        ^ data_i[241]
        ^ data_i[242]
        ^ data_i[245]
        ^ data_i[247]
        ^ data_i[249]
        ^ data_i[250]
        ^ data_i[252]
        ^ data_i[254]
        ;
    assign syndrome[7] = check_i[7]
        ^ data_i[2]
        ^ data_i[5]
        ^ data_i[9]
        ^ data_i[12]
        ^ data_i[15]
        ^ data_i[18]
        ^ data_i[22]
        ^ data_i[26]
        ^ data_i[29]
        ^ data_i[32]
        ^ data_i[36]
        ^ data_i[38]
        ^ data_i[43]
        ^ data_i[44]
        ^ data_i[48]
        ^ data_i[51]
        ^ data_i[56]
        ^ data_i[59]
        ^ data_i[63]
        ^ data_i[65]
        ^ data_i[67]
        ^ data_i[72]
        ^ data_i[74]
        ^ data_i[79]
        ^ data_i[82]
        ^ data_i[86]
        ^ data_i[87]
        ^ data_i[92]
        ^ data_i[95]
        ^ data_i[98]
        ^ data_i[103]
        ^ data_i[106]
        ^ data_i[109]
        ^ data_i[111]
        ^ data_i[114]
        ^ data_i[118]
        ^ data_i[121]
        ^ data_i[123]
        ^ data_i[125]
        ^ data_i[126]
        ^ data_i[129]
        ^ data_i[131]
        ^ data_i[133]
        ^ data_i[135]
        ^ data_i[136]
        ^ data_i[139]
        ^ data_i[141]
        ^ data_i[143]
        ^ data_i[144]
        ^ data_i[147]
        ^ data_i[149]
        ^ data_i[150]
        ^ data_i[153]
        ^ data_i[155]
        ^ data_i[156]
        ^ data_i[158]
        ^ data_i[161]
        ^ data_i[163]
        ^ data_i[165]
        ^ data_i[166]
        ^ data_i[169]
        ^ data_i[171]
        ^ data_i[173]
        ^ data_i[174]
        ^ data_i[177]
        ^ data_i[179]
        ^ data_i[180]
        ^ data_i[183]
        ^ data_i[185]
        ^ data_i[186]
        ^ data_i[188]
        ^ data_i[191]
        ^ data_i[193]
        ^ data_i[194]
        ^ data_i[197]
        ^ data_i[199]
        ^ data_i[200]
        ^ data_i[203]
        ^ data_i[205]
        ^ data_i[206]
        ^ data_i[208]
        ^ data_i[211]
        ^ data_i[212]
        ^ data_i[215]
        ^ data_i[217]
        ^ data_i[218]
        ^ data_i[220]
        ^ data_i[223]
        ^ data_i[224]
        ^ data_i[226]
        ^ data_i[229]
        ^ data_i[230]
        ^ data_i[233]
        ^ data_i[235]
        ^ data_i[236]
        ^ data_i[239]
        ^ data_i[241]
        ^ data_i[243]
        ^ data_i[244]
        ^ data_i[247]
        ^ data_i[249]
        ^ data_i[250]
        ^ data_i[253]
        ^ data_i[255]
        ;
    assign syndrome[8] = check_i[8]
        ^ data_i[2]
        ^ data_i[6]
        ^ data_i[9]
        ^ data_i[13]
        ^ data_i[16]
        ^ data_i[19]
        ^ data_i[22]
        ^ data_i[25]
        ^ data_i[29]
        ^ data_i[33]
        ^ data_i[35]
        ^ data_i[39]
        ^ data_i[42]
        ^ data_i[45]
        ^ data_i[49]
        ^ data_i[53]
        ^ data_i[56]
        ^ data_i[58]
        ^ data_i[61]
        ^ data_i[65]
        ^ data_i[69]
        ^ data_i[73]
        ^ data_i[76]
        ^ data_i[78]
        ^ data_i[81]
        ^ data_i[84]
        ^ data_i[88]
        ^ data_i[92]
        ^ data_i[96]
        ^ data_i[97]
        ^ data_i[101]
        ^ data_i[106]
        ^ data_i[108]
        ^ data_i[110]
        ^ data_i[116]
        ^ data_i[119]
        ^ data_i[121]
        ^ data_i[123]
        ^ data_i[125]
        ^ data_i[127]
        ^ data_i[128]
        ^ data_i[131]
        ^ data_i[133]
        ^ data_i[135]
        ^ data_i[137]
        ^ data_i[138]
        ^ data_i[141]
        ^ data_i[143]
        ^ data_i[145]
        ^ data_i[146]
        ^ data_i[149]
        ^ data_i[151]
        ^ data_i[152]
        ^ data_i[155]
        ^ data_i[156]
        ^ data_i[159]
        ^ data_i[160]
        ^ data_i[163]
        ^ data_i[165]
        ^ data_i[167]
        ^ data_i[168]
        ^ data_i[171]
        ^ data_i[173]
        ^ data_i[175]
        ^ data_i[176]
        ^ data_i[179]
        ^ data_i[181]
        ^ data_i[182]
        ^ data_i[185]
        ^ data_i[186]
        ^ data_i[189]
        ^ data_i[190]
        ^ data_i[193]
        ^ data_i[195]
        ^ data_i[196]
        ^ data_i[199]
        ^ data_i[201]
        ^ data_i[202]
        ^ data_i[205]
        ^ data_i[206]
        ^ data_i[209]
        ^ data_i[210]
        ^ data_i[213]
        ^ data_i[214]
        ^ data_i[217]
        ^ data_i[218]
        ^ data_i[221]
        ^ data_i[222]
        ^ data_i[224]
        ^ data_i[227]
        ^ data_i[228]
        ^ data_i[230]
        ^ data_i[233]
        ^ data_i[235]
        ^ data_i[237]
        ^ data_i[238]
        ^ data_i[241]
        ^ data_i[243]
        ^ data_i[245]
        ^ data_i[246]
        ^ data_i[249]
        ^ data_i[251]
        ^ data_i[252]
        ^ data_i[255]
        ;
    assign syndrome[9] = check_i[9]
        ^ data_i[3]
        ^ data_i[6]
        ^ data_i[9]
        ^ data_i[12]
        ^ data_i[16]
        ^ data_i[19]
        ^ data_i[23]
        ^ data_i[26]
        ^ data_i[30]
        ^ data_i[32]
        ^ data_i[36]
        ^ data_i[40]
        ^ data_i[42]
        ^ data_i[46]
        ^ data_i[50]
        ^ data_i[52]
        ^ data_i[55]
        ^ data_i[60]
        ^ data_i[63]
        ^ data_i[66]
        ^ data_i[68]
        ^ data_i[71]
        ^ data_i[75]
        ^ data_i[79]
        ^ data_i[83]
        ^ data_i[85]
        ^ data_i[90]
        ^ data_i[91]
        ^ data_i[95]
        ^ data_i[100]
        ^ data_i[104]
        ^ data_i[105]
        ^ data_i[110]
        ^ data_i[113]
        ^ data_i[116]
        ^ data_i[119]
        ^ data_i[121]
        ^ data_i[123]
        ^ data_i[125]
        ^ data_i[127]
        ^ data_i[129]
        ^ data_i[130]
        ^ data_i[133]
        ^ data_i[135]
        ^ data_i[137]
        ^ data_i[139]
        ^ data_i[140]
        ^ data_i[143]
        ^ data_i[145]
        ^ data_i[147]
        ^ data_i[148]
        ^ data_i[151]
        ^ data_i[153]
        ^ data_i[154]
        ^ data_i[157]
        ^ data_i[158]
        ^ data_i[160]
        ^ data_i[163]
        ^ data_i[165]
        ^ data_i[167]
        ^ data_i[169]
        ^ data_i[170]
        ^ data_i[173]
        ^ data_i[175]
        ^ data_i[177]
        ^ data_i[178]
        ^ data_i[181]
        ^ data_i[183]
        ^ data_i[184]
        ^ data_i[187]
        ^ data_i[188]
        ^ data_i[190]
        ^ data_i[193]
        ^ data_i[195]
        ^ data_i[197]
        ^ data_i[198]
        ^ data_i[201]
        ^ data_i[203]
        ^ data_i[204]
        ^ data_i[207]
        ^ data_i[208]
        ^ data_i[210]
        ^ data_i[213]
        ^ data_i[215]
        ^ data_i[216]
        ^ data_i[219]
        ^ data_i[220]
        ^ data_i[222]
        ^ data_i[225]
        ^ data_i[226]
        ^ data_i[228]
        ^ data_i[230]
        ^ data_i[233]
        ^ data_i[235]
        ^ data_i[237]
        ^ data_i[239]
        ^ data_i[240]
        ^ data_i[243]
        ^ data_i[245]
        ^ data_i[247]
        ^ data_i[248]
        ^ data_i[251]
        ^ data_i[253]
        ^ data_i[254]
        ;

    assign syndrome_o = syndrome;

    wire syndrome_nz  = |syndrome;
    wire syndrome_odd = ^syndrome;
    // Hsiao: odd syndrome parity == single-bit (correctable) error.
    assign ce_o = syndrome_nz &  syndrome_odd & ~poison_i;
    assign ue_o = (syndrome_nz & ~syndrome_odd) | poison_i;
    assign poison_o = poison_i | (syndrome_nz & ~syndrome_odd);

    wire [255:0] correct;
    assign correct[0] = (syndrome == 10'd7);
    assign correct[1] = (syndrome == 10'd56);
    assign correct[2] = (syndrome == 10'd448);
    assign correct[3] = (syndrome == 10'd515);
    assign correct[4] = (syndrome == 10'd28);
    assign correct[5] = (syndrome == 10'd224);
    assign correct[6] = (syndrome == 10'd769);
    assign correct[7] = (syndrome == 10'd14);
    assign correct[8] = (syndrome == 10'd112);
    assign correct[9] = (syndrome == 10'd896);
    assign correct[10] = (syndrome == 10'd11);
    assign correct[11] = (syndrome == 10'd52);
    assign correct[12] = (syndrome == 10'd704);
    assign correct[13] = (syndrome == 10'd259);
    assign correct[14] = (syndrome == 10'd44);
    assign correct[15] = (syndrome == 10'd208);
    assign correct[16] = (syndrome == 10'd770);
    assign correct[17] = (syndrome == 10'd13);
    assign correct[18] = (syndrome == 10'd176);
    assign correct[19] = (syndrome == 10'd832);
    assign correct[20] = (syndrome == 10'd19);
    assign correct[21] = (syndrome == 10'd76);
    assign correct[22] = (syndrome == 10'd416);
    assign correct[23] = (syndrome == 10'd517);
    assign correct[24] = (syndrome == 10'd26);
    assign correct[25] = (syndrome == 10'd352);
    assign correct[26] = (syndrome == 10'd641);
    assign correct[27] = (syndrome == 10'd22);
    assign correct[28] = (syndrome == 10'd104);
    assign correct[29] = (syndrome == 10'd385);
    assign correct[30] = (syndrome == 10'd518);
    assign correct[31] = (syndrome == 10'd88);
    assign correct[32] = (syndrome == 10'd672);
    assign correct[33] = (syndrome == 10'd261);
    assign correct[34] = (syndrome == 10'd42);
    assign correct[35] = (syndrome == 10'd336);
    assign correct[36] = (syndrome == 10'd642);
    assign correct[37] = (syndrome == 10'd21);
    assign correct[38] = (syndrome == 10'd168);
    assign correct[39] = (syndrome == 10'd321);
    assign correct[40] = (syndrome == 10'd522);
    assign correct[41] = (syndrome == 10'd84);
    assign correct[42] = (syndrome == 10'd800);
    assign correct[43] = (syndrome == 10'd131);
    assign correct[44] = (syndrome == 10'd140);
    assign correct[45] = (syndrome == 10'd304);
    assign correct[46] = (syndrome == 10'd577);
    assign correct[47] = (syndrome == 10'd38);
    assign correct[48] = (syndrome == 10'd152);
    assign correct[49] = (syndrome == 10'd322);
    assign correct[50] = (syndrome == 10'd521);
    assign correct[51] = (syndrome == 10'd148);
    assign correct[52] = (syndrome == 10'd608);
    assign correct[53] = (syndrome == 10'd265);
    assign correct[54] = (syndrome == 10'd70);
    assign correct[55] = (syndrome == 10'd560);
    assign correct[56] = (syndrome == 10'd386);
    assign correct[57] = (syndrome == 10'd37);
    assign correct[58] = (syndrome == 10'd280);
    assign correct[59] = (syndrome == 10'd193);
    assign correct[60] = (syndrome == 10'd530);
    assign correct[61] = (syndrome == 10'd268);
    assign correct[62] = (syndrome == 10'd97);
    assign correct[63] = (syndrome == 10'd644);
    assign correct[64] = (syndrome == 10'd74);
    assign correct[65] = (syndrome == 10'd400);
    assign correct[66] = (syndrome == 10'd545);
    assign correct[67] = (syndrome == 10'd134);
    assign correct[68] = (syndrome == 10'd536);
    assign correct[69] = (syndrome == 10'd289);
    assign correct[70] = (syndrome == 10'd82);
    assign correct[71] = (syndrome == 10'd524);
    assign correct[72] = (syndrome == 10'd161);
    assign correct[73] = (syndrome == 10'd324);
    assign correct[74] = (syndrome == 10'd138);
    assign correct[75] = (syndrome == 10'd592);
    assign correct[76] = (syndrome == 10'd290);
    assign correct[77] = (syndrome == 10'd69);
    assign correct[78] = (syndrome == 10'd296);
    assign correct[79] = (syndrome == 10'd656);
    assign correct[80] = (syndrome == 10'd35);
    assign correct[81] = (syndrome == 10'd276);
    assign correct[82] = (syndrome == 10'd200);
    assign correct[83] = (syndrome == 10'd529);
    assign correct[84] = (syndrome == 10'd262);
    assign correct[85] = (syndrome == 10'd552);
    assign correct[86] = (syndrome == 10'd194);
    assign correct[87] = (syndrome == 10'd133);
    assign correct[88] = (syndrome == 10'd328);
    assign correct[89] = (syndrome == 10'd49);
    assign correct[90] = (syndrome == 10'd546);
    assign correct[91] = (syndrome == 10'd532);
    assign correct[92] = (syndrome == 10'd392);
    assign correct[93] = (syndrome == 10'd67);
    assign correct[94] = (syndrome == 10'd100);
    assign correct[95] = (syndrome == 10'd648);
    assign correct[96] = (syndrome == 10'd273);
    assign correct[97] = (syndrome == 10'd266);
    assign correct[98] = (syndrome == 10'd164);
    assign correct[99] = (syndrome == 10'd81);
    assign correct[100] = (syndrome == 10'd578);
    assign correct[101] = (syndrome == 10'd292);
    assign correct[102] = (syndrome == 10'd25);
    assign correct[103] = (syndrome == 10'd146);
    assign correct[104] = (syndrome == 10'd548);
    assign correct[105] = (syndrome == 10'd584);
    assign correct[106] = (syndrome == 10'd388);
    assign correct[107] = (syndrome == 10'd41);
    assign correct[108] = (syndrome == 10'd274);
    assign correct[109] = (syndrome == 10'd196);
    assign correct[110] = (syndrome == 10'd776);
    assign correct[111] = (syndrome == 10'd145);
    assign correct[112] = (syndrome == 10'd98);
    assign correct[113] = (syndrome == 10'd580);
    assign correct[114] = (syndrome == 10'd137);
    assign correct[115] = (syndrome == 10'd50);
    assign correct[116] = (syndrome == 10'd772);
    assign correct[117] = (syndrome == 10'd73);
    assign correct[118] = (syndrome == 10'd162);
    assign correct[119] = (syndrome == 10'd784);
    assign correct[120] = (syndrome == 10'd31);
    assign correct[121] = (syndrome == 10'd992);
    assign correct[122] = (syndrome == 10'd47);
    assign correct[123] = (syndrome == 10'd976);
    assign correct[124] = (syndrome == 10'd79);
    assign correct[125] = (syndrome == 10'd944);
    assign correct[126] = (syndrome == 10'd143);
    assign correct[127] = (syndrome == 10'd880);
    assign correct[128] = (syndrome == 10'd271);
    assign correct[129] = (syndrome == 10'd752);
    assign correct[130] = (syndrome == 10'd527);
    assign correct[131] = (syndrome == 10'd496);
    assign correct[132] = (syndrome == 10'd55);
    assign correct[133] = (syndrome == 10'd968);
    assign correct[134] = (syndrome == 10'd87);
    assign correct[135] = (syndrome == 10'd936);
    assign correct[136] = (syndrome == 10'd151);
    assign correct[137] = (syndrome == 10'd872);
    assign correct[138] = (syndrome == 10'd279);
    assign correct[139] = (syndrome == 10'd744);
    assign correct[140] = (syndrome == 10'd535);
    assign correct[141] = (syndrome == 10'd488);
    assign correct[142] = (syndrome == 10'd103);
    assign correct[143] = (syndrome == 10'd920);
    assign correct[144] = (syndrome == 10'd167);
    assign correct[145] = (syndrome == 10'd856);
    assign correct[146] = (syndrome == 10'd295);
    assign correct[147] = (syndrome == 10'd728);
    assign correct[148] = (syndrome == 10'd551);
    assign correct[149] = (syndrome == 10'd472);
    assign correct[150] = (syndrome == 10'd199);
    assign correct[151] = (syndrome == 10'd824);
    assign correct[152] = (syndrome == 10'd327);
    assign correct[153] = (syndrome == 10'd696);
    assign correct[154] = (syndrome == 10'd583);
    assign correct[155] = (syndrome == 10'd440);
    assign correct[156] = (syndrome == 10'd391);
    assign correct[157] = (syndrome == 10'd632);
    assign correct[158] = (syndrome == 10'd647);
    assign correct[159] = (syndrome == 10'd376);
    assign correct[160] = (syndrome == 10'd775);
    assign correct[161] = (syndrome == 10'd248);
    assign correct[162] = (syndrome == 10'd59);
    assign correct[163] = (syndrome == 10'd964);
    assign correct[164] = (syndrome == 10'd91);
    assign correct[165] = (syndrome == 10'd932);
    assign correct[166] = (syndrome == 10'd155);
    assign correct[167] = (syndrome == 10'd868);
    assign correct[168] = (syndrome == 10'd283);
    assign correct[169] = (syndrome == 10'd740);
    assign correct[170] = (syndrome == 10'd539);
    assign correct[171] = (syndrome == 10'd484);
    assign correct[172] = (syndrome == 10'd107);
    assign correct[173] = (syndrome == 10'd916);
    assign correct[174] = (syndrome == 10'd171);
    assign correct[175] = (syndrome == 10'd852);
    assign correct[176] = (syndrome == 10'd299);
    assign correct[177] = (syndrome == 10'd724);
    assign correct[178] = (syndrome == 10'd555);
    assign correct[179] = (syndrome == 10'd468);
    assign correct[180] = (syndrome == 10'd203);
    assign correct[181] = (syndrome == 10'd820);
    assign correct[182] = (syndrome == 10'd331);
    assign correct[183] = (syndrome == 10'd692);
    assign correct[184] = (syndrome == 10'd587);
    assign correct[185] = (syndrome == 10'd436);
    assign correct[186] = (syndrome == 10'd395);
    assign correct[187] = (syndrome == 10'd628);
    assign correct[188] = (syndrome == 10'd651);
    assign correct[189] = (syndrome == 10'd372);
    assign correct[190] = (syndrome == 10'd779);
    assign correct[191] = (syndrome == 10'd244);
    assign correct[192] = (syndrome == 10'd115);
    assign correct[193] = (syndrome == 10'd908);
    assign correct[194] = (syndrome == 10'd179);
    assign correct[195] = (syndrome == 10'd844);
    assign correct[196] = (syndrome == 10'd307);
    assign correct[197] = (syndrome == 10'd716);
    assign correct[198] = (syndrome == 10'd563);
    assign correct[199] = (syndrome == 10'd460);
    assign correct[200] = (syndrome == 10'd211);
    assign correct[201] = (syndrome == 10'd812);
    assign correct[202] = (syndrome == 10'd339);
    assign correct[203] = (syndrome == 10'd684);
    assign correct[204] = (syndrome == 10'd595);
    assign correct[205] = (syndrome == 10'd428);
    assign correct[206] = (syndrome == 10'd403);
    assign correct[207] = (syndrome == 10'd620);
    assign correct[208] = (syndrome == 10'd659);
    assign correct[209] = (syndrome == 10'd364);
    assign correct[210] = (syndrome == 10'd787);
    assign correct[211] = (syndrome == 10'd236);
    assign correct[212] = (syndrome == 10'd227);
    assign correct[213] = (syndrome == 10'd796);
    assign correct[214] = (syndrome == 10'd355);
    assign correct[215] = (syndrome == 10'd668);
    assign correct[216] = (syndrome == 10'd611);
    assign correct[217] = (syndrome == 10'd412);
    assign correct[218] = (syndrome == 10'd419);
    assign correct[219] = (syndrome == 10'd604);
    assign correct[220] = (syndrome == 10'd675);
    assign correct[221] = (syndrome == 10'd348);
    assign correct[222] = (syndrome == 10'd803);
    assign correct[223] = (syndrome == 10'd220);
    assign correct[224] = (syndrome == 10'd451);
    assign correct[225] = (syndrome == 10'd572);
    assign correct[226] = (syndrome == 10'd707);
    assign correct[227] = (syndrome == 10'd316);
    assign correct[228] = (syndrome == 10'd835);
    assign correct[229] = (syndrome == 10'd188);
    assign correct[230] = (syndrome == 10'd899);
    assign correct[231] = (syndrome == 10'd124);
    assign correct[232] = (syndrome == 10'd61);
    assign correct[233] = (syndrome == 10'd962);
    assign correct[234] = (syndrome == 10'd93);
    assign correct[235] = (syndrome == 10'd930);
    assign correct[236] = (syndrome == 10'd157);
    assign correct[237] = (syndrome == 10'd866);
    assign correct[238] = (syndrome == 10'd285);
    assign correct[239] = (syndrome == 10'd738);
    assign correct[240] = (syndrome == 10'd541);
    assign correct[241] = (syndrome == 10'd482);
    assign correct[242] = (syndrome == 10'd109);
    assign correct[243] = (syndrome == 10'd914);
    assign correct[244] = (syndrome == 10'd173);
    assign correct[245] = (syndrome == 10'd850);
    assign correct[246] = (syndrome == 10'd301);
    assign correct[247] = (syndrome == 10'd722);
    assign correct[248] = (syndrome == 10'd557);
    assign correct[249] = (syndrome == 10'd466);
    assign correct[250] = (syndrome == 10'd205);
    assign correct[251] = (syndrome == 10'd818);
    assign correct[252] = (syndrome == 10'd333);
    assign correct[253] = (syndrome == 10'd690);
    assign correct[254] = (syndrome == 10'd589);
    assign correct[255] = (syndrome == 10'd434);

    // A syndrome equal to a unit vector points at a check bit, not data.
    assign ce_in_check_o = ce_o & ((syndrome == 10'd1) | (syndrome == 10'd2) | (syndrome == 10'd4) | (syndrome == 10'd8) | (syndrome == 10'd16) | (syndrome == 10'd32) | (syndrome == 10'd64) | (syndrome == 10'd128) | (syndrome == 10'd256) | (syndrome == 10'd512));

    assign data_o = data_i ^ (correct & {256{ce_o}});

endmodule

// ---------------------------------------------------------------------------
// Pipelined split of the same code: vc3d_secded_syn_256 computes the
// syndrome (stage 1) and vc3d_secded_cor_256 applies the correction
// (stage 2) from a REGISTERED syndrome.  Splitting the decoder is what lets
// the ECC sit in a 3 GHz pipeline: the XOR tree and the 1-of-N correction
// compare are each about half of the combinational decoder.
// ---------------------------------------------------------------------------
module vc3d_secded_syn_256 (
    input  wire [255:0] data_i,
    input  wire [9:0] check_i,
    output wire [9:0] syndrome_o
);

    assign syndrome_o[0] = check_i[0]
        ^ data_i[0]
        ^ data_i[3]
        ^ data_i[6]
        ^ data_i[10]
        ^ data_i[13]
        ^ data_i[17]
        ^ data_i[20]
        ^ data_i[23]
        ^ data_i[26]
        ^ data_i[29]
        ^ data_i[33]
        ^ data_i[37]
        ^ data_i[39]
        ^ data_i[43]
        ^ data_i[46]
        ^ data_i[50]
        ^ data_i[53]
        ^ data_i[57]
        ^ data_i[59]
        ^ data_i[62]
        ^ data_i[66]
        ^ data_i[69]
        ^ data_i[72]
        ^ data_i[77]
        ^ data_i[80]
        ^ data_i[83]
        ^ data_i[87]
        ^ data_i[89]
        ^ data_i[93]
        ^ data_i[96]
        ^ data_i[99]
        ^ data_i[102]
        ^ data_i[107]
        ^ data_i[111]
        ^ data_i[114]
        ^ data_i[117]
        ^ data_i[120]
        ^ data_i[122]
        ^ data_i[124]
        ^ data_i[126]
        ^ data_i[128]
        ^ data_i[130]
        ^ data_i[132]
        ^ data_i[134]
        ^ data_i[136]
        ^ data_i[138]
        ^ data_i[140]
        ^ data_i[142]
        ^ data_i[144]
        ^ data_i[146]
        ^ data_i[148]
        ^ data_i[150]
        ^ data_i[152]
        ^ data_i[154]
        ^ data_i[156]
        ^ data_i[158]
        ^ data_i[160]
        ^ data_i[162]
        ^ data_i[164]
        ^ data_i[166]
        ^ data_i[168]
        ^ data_i[170]
        ^ data_i[172]
        ^ data_i[174]
        ^ data_i[176]
        ^ data_i[178]
        ^ data_i[180]
        ^ data_i[182]
        ^ data_i[184]
        ^ data_i[186]
        ^ data_i[188]
        ^ data_i[190]
        ^ data_i[192]
        ^ data_i[194]
        ^ data_i[196]
        ^ data_i[198]
        ^ data_i[200]
        ^ data_i[202]
        ^ data_i[204]
        ^ data_i[206]
        ^ data_i[208]
        ^ data_i[210]
        ^ data_i[212]
        ^ data_i[214]
        ^ data_i[216]
        ^ data_i[218]
        ^ data_i[220]
        ^ data_i[222]
        ^ data_i[224]
        ^ data_i[226]
        ^ data_i[228]
        ^ data_i[230]
        ^ data_i[232]
        ^ data_i[234]
        ^ data_i[236]
        ^ data_i[238]
        ^ data_i[240]
        ^ data_i[242]
        ^ data_i[244]
        ^ data_i[246]
        ^ data_i[248]
        ^ data_i[250]
        ^ data_i[252]
        ^ data_i[254]
        ;
    assign syndrome_o[1] = check_i[1]
        ^ data_i[0]
        ^ data_i[3]
        ^ data_i[7]
        ^ data_i[10]
        ^ data_i[13]
        ^ data_i[16]
        ^ data_i[20]
        ^ data_i[24]
        ^ data_i[27]
        ^ data_i[30]
        ^ data_i[34]
        ^ data_i[36]
        ^ data_i[40]
        ^ data_i[43]
        ^ data_i[47]
        ^ data_i[49]
        ^ data_i[54]
        ^ data_i[56]
        ^ data_i[60]
        ^ data_i[64]
        ^ data_i[67]
        ^ data_i[70]
        ^ data_i[74]
        ^ data_i[76]
        ^ data_i[80]
        ^ data_i[84]
        ^ data_i[86]
        ^ data_i[90]
        ^ data_i[93]
        ^ data_i[97]
        ^ data_i[100]
        ^ data_i[103]
        ^ data_i[108]
        ^ data_i[112]
        ^ data_i[115]
        ^ data_i[118]
        ^ data_i[120]
        ^ data_i[122]
        ^ data_i[124]
        ^ data_i[126]
        ^ data_i[128]
        ^ data_i[130]
        ^ data_i[132]
        ^ data_i[134]
        ^ data_i[136]
        ^ data_i[138]
        ^ data_i[140]
        ^ data_i[142]
        ^ data_i[144]
        ^ data_i[146]
        ^ data_i[148]
        ^ data_i[150]
        ^ data_i[152]
        ^ data_i[154]
        ^ data_i[156]
        ^ data_i[158]
        ^ data_i[160]
        ^ data_i[162]
        ^ data_i[164]
        ^ data_i[166]
        ^ data_i[168]
        ^ data_i[170]
        ^ data_i[172]
        ^ data_i[174]
        ^ data_i[176]
        ^ data_i[178]
        ^ data_i[180]
        ^ data_i[182]
        ^ data_i[184]
        ^ data_i[186]
        ^ data_i[188]
        ^ data_i[190]
        ^ data_i[192]
        ^ data_i[194]
        ^ data_i[196]
        ^ data_i[198]
        ^ data_i[200]
        ^ data_i[202]
        ^ data_i[204]
        ^ data_i[206]
        ^ data_i[208]
        ^ data_i[210]
        ^ data_i[212]
        ^ data_i[214]
        ^ data_i[216]
        ^ data_i[218]
        ^ data_i[220]
        ^ data_i[222]
        ^ data_i[224]
        ^ data_i[226]
        ^ data_i[228]
        ^ data_i[230]
        ^ data_i[233]
        ^ data_i[235]
        ^ data_i[237]
        ^ data_i[239]
        ^ data_i[241]
        ^ data_i[243]
        ^ data_i[245]
        ^ data_i[247]
        ^ data_i[249]
        ^ data_i[251]
        ^ data_i[253]
        ^ data_i[255]
        ;
    assign syndrome_o[2] = check_i[2]
        ^ data_i[0]
        ^ data_i[4]
        ^ data_i[7]
        ^ data_i[11]
        ^ data_i[14]
        ^ data_i[17]
        ^ data_i[21]
        ^ data_i[23]
        ^ data_i[27]
        ^ data_i[30]
        ^ data_i[33]
        ^ data_i[37]
        ^ data_i[41]
        ^ data_i[44]
        ^ data_i[47]
        ^ data_i[51]
        ^ data_i[54]
        ^ data_i[57]
        ^ data_i[61]
        ^ data_i[63]
        ^ data_i[67]
        ^ data_i[71]
        ^ data_i[73]
        ^ data_i[77]
        ^ data_i[81]
        ^ data_i[84]
        ^ data_i[87]
        ^ data_i[91]
        ^ data_i[94]
        ^ data_i[98]
        ^ data_i[101]
        ^ data_i[104]
        ^ data_i[106]
        ^ data_i[109]
        ^ data_i[113]
        ^ data_i[116]
        ^ data_i[120]
        ^ data_i[122]
        ^ data_i[124]
        ^ data_i[126]
        ^ data_i[128]
        ^ data_i[130]
        ^ data_i[132]
        ^ data_i[134]
        ^ data_i[136]
        ^ data_i[138]
        ^ data_i[140]
        ^ data_i[142]
        ^ data_i[144]
        ^ data_i[146]
        ^ data_i[148]
        ^ data_i[150]
        ^ data_i[152]
        ^ data_i[154]
        ^ data_i[156]
        ^ data_i[158]
        ^ data_i[160]
        ^ data_i[163]
        ^ data_i[165]
        ^ data_i[167]
        ^ data_i[169]
        ^ data_i[171]
        ^ data_i[173]
        ^ data_i[175]
        ^ data_i[177]
        ^ data_i[179]
        ^ data_i[181]
        ^ data_i[183]
        ^ data_i[185]
        ^ data_i[187]
        ^ data_i[189]
        ^ data_i[191]
        ^ data_i[193]
        ^ data_i[195]
        ^ data_i[197]
        ^ data_i[199]
        ^ data_i[201]
        ^ data_i[203]
        ^ data_i[205]
        ^ data_i[207]
        ^ data_i[209]
        ^ data_i[211]
        ^ data_i[213]
        ^ data_i[215]
        ^ data_i[217]
        ^ data_i[219]
        ^ data_i[221]
        ^ data_i[223]
        ^ data_i[225]
        ^ data_i[227]
        ^ data_i[229]
        ^ data_i[231]
        ^ data_i[232]
        ^ data_i[234]
        ^ data_i[236]
        ^ data_i[238]
        ^ data_i[240]
        ^ data_i[242]
        ^ data_i[244]
        ^ data_i[246]
        ^ data_i[248]
        ^ data_i[250]
        ^ data_i[252]
        ^ data_i[254]
        ;
    assign syndrome_o[3] = check_i[3]
        ^ data_i[1]
        ^ data_i[4]
        ^ data_i[7]
        ^ data_i[10]
        ^ data_i[14]
        ^ data_i[17]
        ^ data_i[21]
        ^ data_i[24]
        ^ data_i[28]
        ^ data_i[31]
        ^ data_i[34]
        ^ data_i[38]
        ^ data_i[40]
        ^ data_i[44]
        ^ data_i[48]
        ^ data_i[50]
        ^ data_i[53]
        ^ data_i[58]
        ^ data_i[61]
        ^ data_i[64]
        ^ data_i[68]
        ^ data_i[71]
        ^ data_i[74]
        ^ data_i[78]
        ^ data_i[82]
        ^ data_i[85]
        ^ data_i[88]
        ^ data_i[92]
        ^ data_i[95]
        ^ data_i[97]
        ^ data_i[102]
        ^ data_i[105]
        ^ data_i[107]
        ^ data_i[110]
        ^ data_i[114]
        ^ data_i[117]
        ^ data_i[120]
        ^ data_i[122]
        ^ data_i[124]
        ^ data_i[126]
        ^ data_i[128]
        ^ data_i[130]
        ^ data_i[133]
        ^ data_i[135]
        ^ data_i[137]
        ^ data_i[139]
        ^ data_i[141]
        ^ data_i[143]
        ^ data_i[145]
        ^ data_i[147]
        ^ data_i[149]
        ^ data_i[151]
        ^ data_i[153]
        ^ data_i[155]
        ^ data_i[157]
        ^ data_i[159]
        ^ data_i[161]
        ^ data_i[162]
        ^ data_i[164]
        ^ data_i[166]
        ^ data_i[168]
        ^ data_i[170]
        ^ data_i[172]
        ^ data_i[174]
        ^ data_i[176]
        ^ data_i[178]
        ^ data_i[180]
        ^ data_i[182]
        ^ data_i[184]
        ^ data_i[186]
        ^ data_i[188]
        ^ data_i[190]
        ^ data_i[193]
        ^ data_i[195]
        ^ data_i[197]
        ^ data_i[199]
        ^ data_i[201]
        ^ data_i[203]
        ^ data_i[205]
        ^ data_i[207]
        ^ data_i[209]
        ^ data_i[211]
        ^ data_i[213]
        ^ data_i[215]
        ^ data_i[217]
        ^ data_i[219]
        ^ data_i[221]
        ^ data_i[223]
        ^ data_i[225]
        ^ data_i[227]
        ^ data_i[229]
        ^ data_i[231]
        ^ data_i[232]
        ^ data_i[234]
        ^ data_i[236]
        ^ data_i[238]
        ^ data_i[240]
        ^ data_i[242]
        ^ data_i[244]
        ^ data_i[246]
        ^ data_i[248]
        ^ data_i[250]
        ^ data_i[252]
        ^ data_i[254]
        ;
    assign syndrome_o[4] = check_i[4]
        ^ data_i[1]
        ^ data_i[4]
        ^ data_i[8]
        ^ data_i[11]
        ^ data_i[15]
        ^ data_i[18]
        ^ data_i[20]
        ^ data_i[24]
        ^ data_i[27]
        ^ data_i[31]
        ^ data_i[35]
        ^ data_i[37]
        ^ data_i[41]
        ^ data_i[45]
        ^ data_i[48]
        ^ data_i[51]
        ^ data_i[55]
        ^ data_i[58]
        ^ data_i[60]
        ^ data_i[65]
        ^ data_i[68]
        ^ data_i[70]
        ^ data_i[75]
        ^ data_i[79]
        ^ data_i[81]
        ^ data_i[83]
        ^ data_i[89]
        ^ data_i[91]
        ^ data_i[96]
        ^ data_i[99]
        ^ data_i[102]
        ^ data_i[103]
        ^ data_i[108]
        ^ data_i[111]
        ^ data_i[115]
        ^ data_i[119]
        ^ data_i[120]
        ^ data_i[123]
        ^ data_i[125]
        ^ data_i[127]
        ^ data_i[129]
        ^ data_i[131]
        ^ data_i[132]
        ^ data_i[134]
        ^ data_i[136]
        ^ data_i[138]
        ^ data_i[140]
        ^ data_i[143]
        ^ data_i[145]
        ^ data_i[147]
        ^ data_i[149]
        ^ data_i[151]
        ^ data_i[153]
        ^ data_i[155]
        ^ data_i[157]
        ^ data_i[159]
        ^ data_i[161]
        ^ data_i[162]
        ^ data_i[164]
        ^ data_i[166]
        ^ data_i[168]
        ^ data_i[170]
        ^ data_i[173]
        ^ data_i[175]
        ^ data_i[177]
        ^ data_i[179]
        ^ data_i[181]
        ^ data_i[183]
        ^ data_i[185]
        ^ data_i[187]
        ^ data_i[189]
        ^ data_i[191]
        ^ data_i[192]
        ^ data_i[194]
        ^ data_i[196]
        ^ data_i[198]
        ^ data_i[200]
        ^ data_i[202]
        ^ data_i[204]
        ^ data_i[206]
        ^ data_i[208]
        ^ data_i[210]
        ^ data_i[213]
        ^ data_i[215]
        ^ data_i[217]
        ^ data_i[219]
        ^ data_i[221]
        ^ data_i[223]
        ^ data_i[225]
        ^ data_i[227]
        ^ data_i[229]
        ^ data_i[231]
        ^ data_i[232]
        ^ data_i[234]
        ^ data_i[236]
        ^ data_i[238]
        ^ data_i[240]
        ^ data_i[243]
        ^ data_i[245]
        ^ data_i[247]
        ^ data_i[249]
        ^ data_i[251]
        ^ data_i[253]
        ^ data_i[255]
        ;
    assign syndrome_o[5] = check_i[5]
        ^ data_i[1]
        ^ data_i[5]
        ^ data_i[8]
        ^ data_i[11]
        ^ data_i[14]
        ^ data_i[18]
        ^ data_i[22]
        ^ data_i[25]
        ^ data_i[28]
        ^ data_i[32]
        ^ data_i[34]
        ^ data_i[38]
        ^ data_i[42]
        ^ data_i[45]
        ^ data_i[47]
        ^ data_i[52]
        ^ data_i[55]
        ^ data_i[57]
        ^ data_i[62]
        ^ data_i[66]
        ^ data_i[69]
        ^ data_i[72]
        ^ data_i[76]
        ^ data_i[78]
        ^ data_i[80]
        ^ data_i[85]
        ^ data_i[89]
        ^ data_i[90]
        ^ data_i[94]
        ^ data_i[98]
        ^ data_i[101]
        ^ data_i[104]
        ^ data_i[107]
        ^ data_i[112]
        ^ data_i[115]
        ^ data_i[118]
        ^ data_i[121]
        ^ data_i[122]
        ^ data_i[125]
        ^ data_i[127]
        ^ data_i[129]
        ^ data_i[131]
        ^ data_i[132]
        ^ data_i[135]
        ^ data_i[137]
        ^ data_i[139]
        ^ data_i[141]
        ^ data_i[142]
        ^ data_i[144]
        ^ data_i[146]
        ^ data_i[148]
        ^ data_i[151]
        ^ data_i[153]
        ^ data_i[155]
        ^ data_i[157]
        ^ data_i[159]
        ^ data_i[161]
        ^ data_i[162]
        ^ data_i[165]
        ^ data_i[167]
        ^ data_i[169]
        ^ data_i[171]
        ^ data_i[172]
        ^ data_i[174]
        ^ data_i[176]
        ^ data_i[178]
        ^ data_i[181]
        ^ data_i[183]
        ^ data_i[185]
        ^ data_i[187]
        ^ data_i[189]
        ^ data_i[191]
        ^ data_i[192]
        ^ data_i[194]
        ^ data_i[196]
        ^ data_i[198]
        ^ data_i[201]
        ^ data_i[203]
        ^ data_i[205]
        ^ data_i[207]
        ^ data_i[209]
        ^ data_i[211]
        ^ data_i[212]
        ^ data_i[214]
        ^ data_i[216]
        ^ data_i[218]
        ^ data_i[220]
        ^ data_i[222]
        ^ data_i[225]
        ^ data_i[227]
        ^ data_i[229]
        ^ data_i[231]
        ^ data_i[232]
        ^ data_i[235]
        ^ data_i[237]
        ^ data_i[239]
        ^ data_i[241]
        ^ data_i[242]
        ^ data_i[244]
        ^ data_i[246]
        ^ data_i[248]
        ^ data_i[251]
        ^ data_i[253]
        ^ data_i[255]
        ;
    assign syndrome_o[6] = check_i[6]
        ^ data_i[2]
        ^ data_i[5]
        ^ data_i[8]
        ^ data_i[12]
        ^ data_i[15]
        ^ data_i[19]
        ^ data_i[21]
        ^ data_i[25]
        ^ data_i[28]
        ^ data_i[31]
        ^ data_i[35]
        ^ data_i[39]
        ^ data_i[41]
        ^ data_i[46]
        ^ data_i[49]
        ^ data_i[52]
        ^ data_i[54]
        ^ data_i[59]
        ^ data_i[62]
        ^ data_i[64]
        ^ data_i[70]
        ^ data_i[73]
        ^ data_i[75]
        ^ data_i[77]
        ^ data_i[82]
        ^ data_i[86]
        ^ data_i[88]
        ^ data_i[93]
        ^ data_i[94]
        ^ data_i[99]
        ^ data_i[100]
        ^ data_i[105]
        ^ data_i[109]
        ^ data_i[112]
        ^ data_i[113]
        ^ data_i[117]
        ^ data_i[121]
        ^ data_i[123]
        ^ data_i[124]
        ^ data_i[127]
        ^ data_i[129]
        ^ data_i[131]
        ^ data_i[133]
        ^ data_i[134]
        ^ data_i[137]
        ^ data_i[139]
        ^ data_i[141]
        ^ data_i[142]
        ^ data_i[145]
        ^ data_i[147]
        ^ data_i[149]
        ^ data_i[150]
        ^ data_i[152]
        ^ data_i[154]
        ^ data_i[157]
        ^ data_i[159]
        ^ data_i[161]
        ^ data_i[163]
        ^ data_i[164]
        ^ data_i[167]
        ^ data_i[169]
        ^ data_i[171]
        ^ data_i[172]
        ^ data_i[175]
        ^ data_i[177]
        ^ data_i[179]
        ^ data_i[180]
        ^ data_i[182]
        ^ data_i[184]
        ^ data_i[187]
        ^ data_i[189]
        ^ data_i[191]
        ^ data_i[192]
        ^ data_i[195]
        ^ data_i[197]
        ^ data_i[199]
        ^ data_i[200]
        ^ data_i[202]
        ^ data_i[204]
        ^ data_i[207]
        ^ data_i[209]
        ^ data_i[211]
        ^ data_i[212]
        ^ data_i[214]
        ^ data_i[216]
        ^ data_i[219]
        ^ data_i[221]
        ^ data_i[223]
        ^ data_i[224]
        ^ data_i[226]
        ^ data_i[228]
        ^ data_i[231]
        ^ data_i[233]
        ^ data_i[234]
        ^ data_i[237]
        ^ data_i[239]
        ^ data_i[241]
        ^ data_i[242]
        ^ data_i[245]
        ^ data_i[247]
        ^ data_i[249]
        ^ data_i[250]
        ^ data_i[252]
        ^ data_i[254]
        ;
    assign syndrome_o[7] = check_i[7]
        ^ data_i[2]
        ^ data_i[5]
        ^ data_i[9]
        ^ data_i[12]
        ^ data_i[15]
        ^ data_i[18]
        ^ data_i[22]
        ^ data_i[26]
        ^ data_i[29]
        ^ data_i[32]
        ^ data_i[36]
        ^ data_i[38]
        ^ data_i[43]
        ^ data_i[44]
        ^ data_i[48]
        ^ data_i[51]
        ^ data_i[56]
        ^ data_i[59]
        ^ data_i[63]
        ^ data_i[65]
        ^ data_i[67]
        ^ data_i[72]
        ^ data_i[74]
        ^ data_i[79]
        ^ data_i[82]
        ^ data_i[86]
        ^ data_i[87]
        ^ data_i[92]
        ^ data_i[95]
        ^ data_i[98]
        ^ data_i[103]
        ^ data_i[106]
        ^ data_i[109]
        ^ data_i[111]
        ^ data_i[114]
        ^ data_i[118]
        ^ data_i[121]
        ^ data_i[123]
        ^ data_i[125]
        ^ data_i[126]
        ^ data_i[129]
        ^ data_i[131]
        ^ data_i[133]
        ^ data_i[135]
        ^ data_i[136]
        ^ data_i[139]
        ^ data_i[141]
        ^ data_i[143]
        ^ data_i[144]
        ^ data_i[147]
        ^ data_i[149]
        ^ data_i[150]
        ^ data_i[153]
        ^ data_i[155]
        ^ data_i[156]
        ^ data_i[158]
        ^ data_i[161]
        ^ data_i[163]
        ^ data_i[165]
        ^ data_i[166]
        ^ data_i[169]
        ^ data_i[171]
        ^ data_i[173]
        ^ data_i[174]
        ^ data_i[177]
        ^ data_i[179]
        ^ data_i[180]
        ^ data_i[183]
        ^ data_i[185]
        ^ data_i[186]
        ^ data_i[188]
        ^ data_i[191]
        ^ data_i[193]
        ^ data_i[194]
        ^ data_i[197]
        ^ data_i[199]
        ^ data_i[200]
        ^ data_i[203]
        ^ data_i[205]
        ^ data_i[206]
        ^ data_i[208]
        ^ data_i[211]
        ^ data_i[212]
        ^ data_i[215]
        ^ data_i[217]
        ^ data_i[218]
        ^ data_i[220]
        ^ data_i[223]
        ^ data_i[224]
        ^ data_i[226]
        ^ data_i[229]
        ^ data_i[230]
        ^ data_i[233]
        ^ data_i[235]
        ^ data_i[236]
        ^ data_i[239]
        ^ data_i[241]
        ^ data_i[243]
        ^ data_i[244]
        ^ data_i[247]
        ^ data_i[249]
        ^ data_i[250]
        ^ data_i[253]
        ^ data_i[255]
        ;
    assign syndrome_o[8] = check_i[8]
        ^ data_i[2]
        ^ data_i[6]
        ^ data_i[9]
        ^ data_i[13]
        ^ data_i[16]
        ^ data_i[19]
        ^ data_i[22]
        ^ data_i[25]
        ^ data_i[29]
        ^ data_i[33]
        ^ data_i[35]
        ^ data_i[39]
        ^ data_i[42]
        ^ data_i[45]
        ^ data_i[49]
        ^ data_i[53]
        ^ data_i[56]
        ^ data_i[58]
        ^ data_i[61]
        ^ data_i[65]
        ^ data_i[69]
        ^ data_i[73]
        ^ data_i[76]
        ^ data_i[78]
        ^ data_i[81]
        ^ data_i[84]
        ^ data_i[88]
        ^ data_i[92]
        ^ data_i[96]
        ^ data_i[97]
        ^ data_i[101]
        ^ data_i[106]
        ^ data_i[108]
        ^ data_i[110]
        ^ data_i[116]
        ^ data_i[119]
        ^ data_i[121]
        ^ data_i[123]
        ^ data_i[125]
        ^ data_i[127]
        ^ data_i[128]
        ^ data_i[131]
        ^ data_i[133]
        ^ data_i[135]
        ^ data_i[137]
        ^ data_i[138]
        ^ data_i[141]
        ^ data_i[143]
        ^ data_i[145]
        ^ data_i[146]
        ^ data_i[149]
        ^ data_i[151]
        ^ data_i[152]
        ^ data_i[155]
        ^ data_i[156]
        ^ data_i[159]
        ^ data_i[160]
        ^ data_i[163]
        ^ data_i[165]
        ^ data_i[167]
        ^ data_i[168]
        ^ data_i[171]
        ^ data_i[173]
        ^ data_i[175]
        ^ data_i[176]
        ^ data_i[179]
        ^ data_i[181]
        ^ data_i[182]
        ^ data_i[185]
        ^ data_i[186]
        ^ data_i[189]
        ^ data_i[190]
        ^ data_i[193]
        ^ data_i[195]
        ^ data_i[196]
        ^ data_i[199]
        ^ data_i[201]
        ^ data_i[202]
        ^ data_i[205]
        ^ data_i[206]
        ^ data_i[209]
        ^ data_i[210]
        ^ data_i[213]
        ^ data_i[214]
        ^ data_i[217]
        ^ data_i[218]
        ^ data_i[221]
        ^ data_i[222]
        ^ data_i[224]
        ^ data_i[227]
        ^ data_i[228]
        ^ data_i[230]
        ^ data_i[233]
        ^ data_i[235]
        ^ data_i[237]
        ^ data_i[238]
        ^ data_i[241]
        ^ data_i[243]
        ^ data_i[245]
        ^ data_i[246]
        ^ data_i[249]
        ^ data_i[251]
        ^ data_i[252]
        ^ data_i[255]
        ;
    assign syndrome_o[9] = check_i[9]
        ^ data_i[3]
        ^ data_i[6]
        ^ data_i[9]
        ^ data_i[12]
        ^ data_i[16]
        ^ data_i[19]
        ^ data_i[23]
        ^ data_i[26]
        ^ data_i[30]
        ^ data_i[32]
        ^ data_i[36]
        ^ data_i[40]
        ^ data_i[42]
        ^ data_i[46]
        ^ data_i[50]
        ^ data_i[52]
        ^ data_i[55]
        ^ data_i[60]
        ^ data_i[63]
        ^ data_i[66]
        ^ data_i[68]
        ^ data_i[71]
        ^ data_i[75]
        ^ data_i[79]
        ^ data_i[83]
        ^ data_i[85]
        ^ data_i[90]
        ^ data_i[91]
        ^ data_i[95]
        ^ data_i[100]
        ^ data_i[104]
        ^ data_i[105]
        ^ data_i[110]
        ^ data_i[113]
        ^ data_i[116]
        ^ data_i[119]
        ^ data_i[121]
        ^ data_i[123]
        ^ data_i[125]
        ^ data_i[127]
        ^ data_i[129]
        ^ data_i[130]
        ^ data_i[133]
        ^ data_i[135]
        ^ data_i[137]
        ^ data_i[139]
        ^ data_i[140]
        ^ data_i[143]
        ^ data_i[145]
        ^ data_i[147]
        ^ data_i[148]
        ^ data_i[151]
        ^ data_i[153]
        ^ data_i[154]
        ^ data_i[157]
        ^ data_i[158]
        ^ data_i[160]
        ^ data_i[163]
        ^ data_i[165]
        ^ data_i[167]
        ^ data_i[169]
        ^ data_i[170]
        ^ data_i[173]
        ^ data_i[175]
        ^ data_i[177]
        ^ data_i[178]
        ^ data_i[181]
        ^ data_i[183]
        ^ data_i[184]
        ^ data_i[187]
        ^ data_i[188]
        ^ data_i[190]
        ^ data_i[193]
        ^ data_i[195]
        ^ data_i[197]
        ^ data_i[198]
        ^ data_i[201]
        ^ data_i[203]
        ^ data_i[204]
        ^ data_i[207]
        ^ data_i[208]
        ^ data_i[210]
        ^ data_i[213]
        ^ data_i[215]
        ^ data_i[216]
        ^ data_i[219]
        ^ data_i[220]
        ^ data_i[222]
        ^ data_i[225]
        ^ data_i[226]
        ^ data_i[228]
        ^ data_i[230]
        ^ data_i[233]
        ^ data_i[235]
        ^ data_i[237]
        ^ data_i[239]
        ^ data_i[240]
        ^ data_i[243]
        ^ data_i[245]
        ^ data_i[247]
        ^ data_i[248]
        ^ data_i[251]
        ^ data_i[253]
        ^ data_i[254]
        ;

endmodule

module vc3d_secded_cor_256 (
    input  wire [255:0] data_i,      // registered, same beat as syndrome
    input  wire [9:0] syndrome_i,
    input  wire poison_i,
    output wire [255:0] data_o,
    output wire ce_o,
    output wire ue_o,
    output wire poison_o
);

    wire syndrome_nz  = |syndrome_i;
    wire syndrome_odd = ^syndrome_i;
    assign ce_o     = syndrome_nz &  syndrome_odd & ~poison_i;
    assign ue_o     = (syndrome_nz & ~syndrome_odd) | poison_i;
    assign poison_o = poison_i | (syndrome_nz & ~syndrome_odd);

    wire [255:0] correct;
    assign correct[0] = (syndrome_i == 10'd7);
    assign correct[1] = (syndrome_i == 10'd56);
    assign correct[2] = (syndrome_i == 10'd448);
    assign correct[3] = (syndrome_i == 10'd515);
    assign correct[4] = (syndrome_i == 10'd28);
    assign correct[5] = (syndrome_i == 10'd224);
    assign correct[6] = (syndrome_i == 10'd769);
    assign correct[7] = (syndrome_i == 10'd14);
    assign correct[8] = (syndrome_i == 10'd112);
    assign correct[9] = (syndrome_i == 10'd896);
    assign correct[10] = (syndrome_i == 10'd11);
    assign correct[11] = (syndrome_i == 10'd52);
    assign correct[12] = (syndrome_i == 10'd704);
    assign correct[13] = (syndrome_i == 10'd259);
    assign correct[14] = (syndrome_i == 10'd44);
    assign correct[15] = (syndrome_i == 10'd208);
    assign correct[16] = (syndrome_i == 10'd770);
    assign correct[17] = (syndrome_i == 10'd13);
    assign correct[18] = (syndrome_i == 10'd176);
    assign correct[19] = (syndrome_i == 10'd832);
    assign correct[20] = (syndrome_i == 10'd19);
    assign correct[21] = (syndrome_i == 10'd76);
    assign correct[22] = (syndrome_i == 10'd416);
    assign correct[23] = (syndrome_i == 10'd517);
    assign correct[24] = (syndrome_i == 10'd26);
    assign correct[25] = (syndrome_i == 10'd352);
    assign correct[26] = (syndrome_i == 10'd641);
    assign correct[27] = (syndrome_i == 10'd22);
    assign correct[28] = (syndrome_i == 10'd104);
    assign correct[29] = (syndrome_i == 10'd385);
    assign correct[30] = (syndrome_i == 10'd518);
    assign correct[31] = (syndrome_i == 10'd88);
    assign correct[32] = (syndrome_i == 10'd672);
    assign correct[33] = (syndrome_i == 10'd261);
    assign correct[34] = (syndrome_i == 10'd42);
    assign correct[35] = (syndrome_i == 10'd336);
    assign correct[36] = (syndrome_i == 10'd642);
    assign correct[37] = (syndrome_i == 10'd21);
    assign correct[38] = (syndrome_i == 10'd168);
    assign correct[39] = (syndrome_i == 10'd321);
    assign correct[40] = (syndrome_i == 10'd522);
    assign correct[41] = (syndrome_i == 10'd84);
    assign correct[42] = (syndrome_i == 10'd800);
    assign correct[43] = (syndrome_i == 10'd131);
    assign correct[44] = (syndrome_i == 10'd140);
    assign correct[45] = (syndrome_i == 10'd304);
    assign correct[46] = (syndrome_i == 10'd577);
    assign correct[47] = (syndrome_i == 10'd38);
    assign correct[48] = (syndrome_i == 10'd152);
    assign correct[49] = (syndrome_i == 10'd322);
    assign correct[50] = (syndrome_i == 10'd521);
    assign correct[51] = (syndrome_i == 10'd148);
    assign correct[52] = (syndrome_i == 10'd608);
    assign correct[53] = (syndrome_i == 10'd265);
    assign correct[54] = (syndrome_i == 10'd70);
    assign correct[55] = (syndrome_i == 10'd560);
    assign correct[56] = (syndrome_i == 10'd386);
    assign correct[57] = (syndrome_i == 10'd37);
    assign correct[58] = (syndrome_i == 10'd280);
    assign correct[59] = (syndrome_i == 10'd193);
    assign correct[60] = (syndrome_i == 10'd530);
    assign correct[61] = (syndrome_i == 10'd268);
    assign correct[62] = (syndrome_i == 10'd97);
    assign correct[63] = (syndrome_i == 10'd644);
    assign correct[64] = (syndrome_i == 10'd74);
    assign correct[65] = (syndrome_i == 10'd400);
    assign correct[66] = (syndrome_i == 10'd545);
    assign correct[67] = (syndrome_i == 10'd134);
    assign correct[68] = (syndrome_i == 10'd536);
    assign correct[69] = (syndrome_i == 10'd289);
    assign correct[70] = (syndrome_i == 10'd82);
    assign correct[71] = (syndrome_i == 10'd524);
    assign correct[72] = (syndrome_i == 10'd161);
    assign correct[73] = (syndrome_i == 10'd324);
    assign correct[74] = (syndrome_i == 10'd138);
    assign correct[75] = (syndrome_i == 10'd592);
    assign correct[76] = (syndrome_i == 10'd290);
    assign correct[77] = (syndrome_i == 10'd69);
    assign correct[78] = (syndrome_i == 10'd296);
    assign correct[79] = (syndrome_i == 10'd656);
    assign correct[80] = (syndrome_i == 10'd35);
    assign correct[81] = (syndrome_i == 10'd276);
    assign correct[82] = (syndrome_i == 10'd200);
    assign correct[83] = (syndrome_i == 10'd529);
    assign correct[84] = (syndrome_i == 10'd262);
    assign correct[85] = (syndrome_i == 10'd552);
    assign correct[86] = (syndrome_i == 10'd194);
    assign correct[87] = (syndrome_i == 10'd133);
    assign correct[88] = (syndrome_i == 10'd328);
    assign correct[89] = (syndrome_i == 10'd49);
    assign correct[90] = (syndrome_i == 10'd546);
    assign correct[91] = (syndrome_i == 10'd532);
    assign correct[92] = (syndrome_i == 10'd392);
    assign correct[93] = (syndrome_i == 10'd67);
    assign correct[94] = (syndrome_i == 10'd100);
    assign correct[95] = (syndrome_i == 10'd648);
    assign correct[96] = (syndrome_i == 10'd273);
    assign correct[97] = (syndrome_i == 10'd266);
    assign correct[98] = (syndrome_i == 10'd164);
    assign correct[99] = (syndrome_i == 10'd81);
    assign correct[100] = (syndrome_i == 10'd578);
    assign correct[101] = (syndrome_i == 10'd292);
    assign correct[102] = (syndrome_i == 10'd25);
    assign correct[103] = (syndrome_i == 10'd146);
    assign correct[104] = (syndrome_i == 10'd548);
    assign correct[105] = (syndrome_i == 10'd584);
    assign correct[106] = (syndrome_i == 10'd388);
    assign correct[107] = (syndrome_i == 10'd41);
    assign correct[108] = (syndrome_i == 10'd274);
    assign correct[109] = (syndrome_i == 10'd196);
    assign correct[110] = (syndrome_i == 10'd776);
    assign correct[111] = (syndrome_i == 10'd145);
    assign correct[112] = (syndrome_i == 10'd98);
    assign correct[113] = (syndrome_i == 10'd580);
    assign correct[114] = (syndrome_i == 10'd137);
    assign correct[115] = (syndrome_i == 10'd50);
    assign correct[116] = (syndrome_i == 10'd772);
    assign correct[117] = (syndrome_i == 10'd73);
    assign correct[118] = (syndrome_i == 10'd162);
    assign correct[119] = (syndrome_i == 10'd784);
    assign correct[120] = (syndrome_i == 10'd31);
    assign correct[121] = (syndrome_i == 10'd992);
    assign correct[122] = (syndrome_i == 10'd47);
    assign correct[123] = (syndrome_i == 10'd976);
    assign correct[124] = (syndrome_i == 10'd79);
    assign correct[125] = (syndrome_i == 10'd944);
    assign correct[126] = (syndrome_i == 10'd143);
    assign correct[127] = (syndrome_i == 10'd880);
    assign correct[128] = (syndrome_i == 10'd271);
    assign correct[129] = (syndrome_i == 10'd752);
    assign correct[130] = (syndrome_i == 10'd527);
    assign correct[131] = (syndrome_i == 10'd496);
    assign correct[132] = (syndrome_i == 10'd55);
    assign correct[133] = (syndrome_i == 10'd968);
    assign correct[134] = (syndrome_i == 10'd87);
    assign correct[135] = (syndrome_i == 10'd936);
    assign correct[136] = (syndrome_i == 10'd151);
    assign correct[137] = (syndrome_i == 10'd872);
    assign correct[138] = (syndrome_i == 10'd279);
    assign correct[139] = (syndrome_i == 10'd744);
    assign correct[140] = (syndrome_i == 10'd535);
    assign correct[141] = (syndrome_i == 10'd488);
    assign correct[142] = (syndrome_i == 10'd103);
    assign correct[143] = (syndrome_i == 10'd920);
    assign correct[144] = (syndrome_i == 10'd167);
    assign correct[145] = (syndrome_i == 10'd856);
    assign correct[146] = (syndrome_i == 10'd295);
    assign correct[147] = (syndrome_i == 10'd728);
    assign correct[148] = (syndrome_i == 10'd551);
    assign correct[149] = (syndrome_i == 10'd472);
    assign correct[150] = (syndrome_i == 10'd199);
    assign correct[151] = (syndrome_i == 10'd824);
    assign correct[152] = (syndrome_i == 10'd327);
    assign correct[153] = (syndrome_i == 10'd696);
    assign correct[154] = (syndrome_i == 10'd583);
    assign correct[155] = (syndrome_i == 10'd440);
    assign correct[156] = (syndrome_i == 10'd391);
    assign correct[157] = (syndrome_i == 10'd632);
    assign correct[158] = (syndrome_i == 10'd647);
    assign correct[159] = (syndrome_i == 10'd376);
    assign correct[160] = (syndrome_i == 10'd775);
    assign correct[161] = (syndrome_i == 10'd248);
    assign correct[162] = (syndrome_i == 10'd59);
    assign correct[163] = (syndrome_i == 10'd964);
    assign correct[164] = (syndrome_i == 10'd91);
    assign correct[165] = (syndrome_i == 10'd932);
    assign correct[166] = (syndrome_i == 10'd155);
    assign correct[167] = (syndrome_i == 10'd868);
    assign correct[168] = (syndrome_i == 10'd283);
    assign correct[169] = (syndrome_i == 10'd740);
    assign correct[170] = (syndrome_i == 10'd539);
    assign correct[171] = (syndrome_i == 10'd484);
    assign correct[172] = (syndrome_i == 10'd107);
    assign correct[173] = (syndrome_i == 10'd916);
    assign correct[174] = (syndrome_i == 10'd171);
    assign correct[175] = (syndrome_i == 10'd852);
    assign correct[176] = (syndrome_i == 10'd299);
    assign correct[177] = (syndrome_i == 10'd724);
    assign correct[178] = (syndrome_i == 10'd555);
    assign correct[179] = (syndrome_i == 10'd468);
    assign correct[180] = (syndrome_i == 10'd203);
    assign correct[181] = (syndrome_i == 10'd820);
    assign correct[182] = (syndrome_i == 10'd331);
    assign correct[183] = (syndrome_i == 10'd692);
    assign correct[184] = (syndrome_i == 10'd587);
    assign correct[185] = (syndrome_i == 10'd436);
    assign correct[186] = (syndrome_i == 10'd395);
    assign correct[187] = (syndrome_i == 10'd628);
    assign correct[188] = (syndrome_i == 10'd651);
    assign correct[189] = (syndrome_i == 10'd372);
    assign correct[190] = (syndrome_i == 10'd779);
    assign correct[191] = (syndrome_i == 10'd244);
    assign correct[192] = (syndrome_i == 10'd115);
    assign correct[193] = (syndrome_i == 10'd908);
    assign correct[194] = (syndrome_i == 10'd179);
    assign correct[195] = (syndrome_i == 10'd844);
    assign correct[196] = (syndrome_i == 10'd307);
    assign correct[197] = (syndrome_i == 10'd716);
    assign correct[198] = (syndrome_i == 10'd563);
    assign correct[199] = (syndrome_i == 10'd460);
    assign correct[200] = (syndrome_i == 10'd211);
    assign correct[201] = (syndrome_i == 10'd812);
    assign correct[202] = (syndrome_i == 10'd339);
    assign correct[203] = (syndrome_i == 10'd684);
    assign correct[204] = (syndrome_i == 10'd595);
    assign correct[205] = (syndrome_i == 10'd428);
    assign correct[206] = (syndrome_i == 10'd403);
    assign correct[207] = (syndrome_i == 10'd620);
    assign correct[208] = (syndrome_i == 10'd659);
    assign correct[209] = (syndrome_i == 10'd364);
    assign correct[210] = (syndrome_i == 10'd787);
    assign correct[211] = (syndrome_i == 10'd236);
    assign correct[212] = (syndrome_i == 10'd227);
    assign correct[213] = (syndrome_i == 10'd796);
    assign correct[214] = (syndrome_i == 10'd355);
    assign correct[215] = (syndrome_i == 10'd668);
    assign correct[216] = (syndrome_i == 10'd611);
    assign correct[217] = (syndrome_i == 10'd412);
    assign correct[218] = (syndrome_i == 10'd419);
    assign correct[219] = (syndrome_i == 10'd604);
    assign correct[220] = (syndrome_i == 10'd675);
    assign correct[221] = (syndrome_i == 10'd348);
    assign correct[222] = (syndrome_i == 10'd803);
    assign correct[223] = (syndrome_i == 10'd220);
    assign correct[224] = (syndrome_i == 10'd451);
    assign correct[225] = (syndrome_i == 10'd572);
    assign correct[226] = (syndrome_i == 10'd707);
    assign correct[227] = (syndrome_i == 10'd316);
    assign correct[228] = (syndrome_i == 10'd835);
    assign correct[229] = (syndrome_i == 10'd188);
    assign correct[230] = (syndrome_i == 10'd899);
    assign correct[231] = (syndrome_i == 10'd124);
    assign correct[232] = (syndrome_i == 10'd61);
    assign correct[233] = (syndrome_i == 10'd962);
    assign correct[234] = (syndrome_i == 10'd93);
    assign correct[235] = (syndrome_i == 10'd930);
    assign correct[236] = (syndrome_i == 10'd157);
    assign correct[237] = (syndrome_i == 10'd866);
    assign correct[238] = (syndrome_i == 10'd285);
    assign correct[239] = (syndrome_i == 10'd738);
    assign correct[240] = (syndrome_i == 10'd541);
    assign correct[241] = (syndrome_i == 10'd482);
    assign correct[242] = (syndrome_i == 10'd109);
    assign correct[243] = (syndrome_i == 10'd914);
    assign correct[244] = (syndrome_i == 10'd173);
    assign correct[245] = (syndrome_i == 10'd850);
    assign correct[246] = (syndrome_i == 10'd301);
    assign correct[247] = (syndrome_i == 10'd722);
    assign correct[248] = (syndrome_i == 10'd557);
    assign correct[249] = (syndrome_i == 10'd466);
    assign correct[250] = (syndrome_i == 10'd205);
    assign correct[251] = (syndrome_i == 10'd818);
    assign correct[252] = (syndrome_i == 10'd333);
    assign correct[253] = (syndrome_i == 10'd690);
    assign correct[254] = (syndrome_i == 10'd589);
    assign correct[255] = (syndrome_i == 10'd434);

    assign data_o = data_i ^ (correct & {256{ce_o}});

endmodule

