// ---------------------------------------------------------------------------
// AUTO-GENERATED by gen/vc3d_gen_ecc.py -- DO NOT HAND EDIT.
// SECDED (Hsiao) codec for 64 data bits + 8 check bits.
// Code distance 4: corrects 1 bit, detects 2 bits, detects all odd-weight
// error patterns.  Row loads (XOR-tree fan-in per check bit): [26, 26, 26, 26, 26, 26, 26, 26]
// Max fan-in 26  ->  balanced XOR depth ceil(log2(max)) = 5.
// ---------------------------------------------------------------------------
`timescale 1ns/1ps

module vc3d_secded_enc_64 (
    input  wire [63:0] data_i,
    output wire [7:0] check_o
);

    // check bit 0: 26 taps
    assign check_o[0] =
          data_i[0] ^
        data_i[2] ^
        data_i[5] ^
        data_i[8] ^
        data_i[11] ^
        data_i[13] ^
        data_i[16] ^
        data_i[18] ^
        data_i[21] ^
        data_i[23] ^
        data_i[27] ^
        data_i[29] ^
        data_i[31] ^
        data_i[35] ^
        data_i[37] ^
        data_i[39] ^
        data_i[42] ^
        data_i[45] ^
        data_i[47] ^
        data_i[51] ^
        data_i[54] ^
        data_i[56] ^
        data_i[57] ^
        data_i[59] ^
        data_i[60] ^
        data_i[62];

    // check bit 1: 26 taps
    assign check_o[1] =
          data_i[0] ^
        data_i[3] ^
        data_i[5] ^
        data_i[8] ^
        data_i[10] ^
        data_i[13] ^
        data_i[16] ^
        data_i[19] ^
        data_i[22] ^
        data_i[24] ^
        data_i[26] ^
        data_i[30] ^
        data_i[32] ^
        data_i[35] ^
        data_i[38] ^
        data_i[40] ^
        data_i[43] ^
        data_i[46] ^
        data_i[48] ^
        data_i[50] ^
        data_i[53] ^
        data_i[56] ^
        data_i[57] ^
        data_i[59] ^
        data_i[61] ^
        data_i[62];

    // check bit 2: 26 taps
    assign check_o[2] =
          data_i[0] ^
        data_i[3] ^
        data_i[6] ^
        data_i[9] ^
        data_i[11] ^
        data_i[14] ^
        data_i[17] ^
        data_i[19] ^
        data_i[21] ^
        data_i[24] ^
        data_i[27] ^
        data_i[29] ^
        data_i[33] ^
        data_i[34] ^
        data_i[38] ^
        data_i[40] ^
        data_i[44] ^
        data_i[45] ^
        data_i[49] ^
        data_i[52] ^
        data_i[55] ^
        data_i[56] ^
        data_i[58] ^
        data_i[59] ^
        data_i[61] ^
        data_i[62];

    // check bit 3: 26 taps
    assign check_o[3] =
          data_i[1] ^
        data_i[3] ^
        data_i[6] ^
        data_i[8] ^
        data_i[11] ^
        data_i[14] ^
        data_i[17] ^
        data_i[20] ^
        data_i[22] ^
        data_i[25] ^
        data_i[28] ^
        data_i[30] ^
        data_i[32] ^
        data_i[36] ^
        data_i[37] ^
        data_i[41] ^
        data_i[43] ^
        data_i[47] ^
        data_i[49] ^
        data_i[51] ^
        data_i[54] ^
        data_i[56] ^
        data_i[58] ^
        data_i[59] ^
        data_i[61] ^
        data_i[63];

    // check bit 4: 26 taps
    assign check_o[4] =
          data_i[1] ^
        data_i[4] ^
        data_i[6] ^
        data_i[9] ^
        data_i[12] ^
        data_i[15] ^
        data_i[16] ^
        data_i[19] ^
        data_i[22] ^
        data_i[25] ^
        data_i[27] ^
        data_i[31] ^
        data_i[33] ^
        data_i[36] ^
        data_i[39] ^
        data_i[42] ^
        data_i[44] ^
        data_i[46] ^
        data_i[48] ^
        data_i[51] ^
        data_i[53] ^
        data_i[56] ^
        data_i[58] ^
        data_i[60] ^
        data_i[61] ^
        data_i[63];

    // check bit 5: 26 taps
    assign check_o[5] =
          data_i[1] ^
        data_i[4] ^
        data_i[7] ^
        data_i[9] ^
        data_i[12] ^
        data_i[14] ^
        data_i[18] ^
        data_i[20] ^
        data_i[23] ^
        data_i[26] ^
        data_i[28] ^
        data_i[30] ^
        data_i[34] ^
        data_i[35] ^
        data_i[38] ^
        data_i[42] ^
        data_i[45] ^
        data_i[46] ^
        data_i[50] ^
        data_i[52] ^
        data_i[54] ^
        data_i[57] ^
        data_i[58] ^
        data_i[60] ^
        data_i[61] ^
        data_i[63];

    // check bit 6: 26 taps
    assign check_o[6] =
          data_i[2] ^
        data_i[4] ^
        data_i[7] ^
        data_i[10] ^
        data_i[13] ^
        data_i[15] ^
        data_i[17] ^
        data_i[20] ^
        data_i[23] ^
        data_i[25] ^
        data_i[29] ^
        data_i[31] ^
        data_i[33] ^
        data_i[37] ^
        data_i[40] ^
        data_i[41] ^
        data_i[43] ^
        data_i[48] ^
        data_i[50] ^
        data_i[52] ^
        data_i[55] ^
        data_i[57] ^
        data_i[58] ^
        data_i[60] ^
        data_i[62] ^
        data_i[63];

    // check bit 7: 26 taps
    assign check_o[7] =
          data_i[2] ^
        data_i[5] ^
        data_i[7] ^
        data_i[10] ^
        data_i[12] ^
        data_i[15] ^
        data_i[18] ^
        data_i[21] ^
        data_i[24] ^
        data_i[26] ^
        data_i[28] ^
        data_i[32] ^
        data_i[34] ^
        data_i[36] ^
        data_i[39] ^
        data_i[41] ^
        data_i[44] ^
        data_i[47] ^
        data_i[49] ^
        data_i[53] ^
        data_i[55] ^
        data_i[57] ^
        data_i[59] ^
        data_i[60] ^
        data_i[62] ^
        data_i[63];

endmodule

module vc3d_secded_dec_64 (
    input  wire [63:0] data_i,
    input  wire [7:0] check_i,
    input  wire poison_i,
    output wire [63:0] data_o,
    output wire [7:0] syndrome_o,
    output wire ce_o,           // corrected single-bit error
    output wire ue_o,           // uncorrectable (double bit) error
    output wire ce_in_check_o,  // the corrected bit was a check bit
    output wire poison_o
);

    wire [7:0] syndrome;
    assign syndrome[0] = check_i[0]
        ^ data_i[0]
        ^ data_i[2]
        ^ data_i[5]
        ^ data_i[8]
        ^ data_i[11]
        ^ data_i[13]
        ^ data_i[16]
        ^ data_i[18]
        ^ data_i[21]
        ^ data_i[23]
        ^ data_i[27]
        ^ data_i[29]
        ^ data_i[31]
        ^ data_i[35]
        ^ data_i[37]
        ^ data_i[39]
        ^ data_i[42]
        ^ data_i[45]
        ^ data_i[47]
        ^ data_i[51]
        ^ data_i[54]
        ^ data_i[56]
        ^ data_i[57]
        ^ data_i[59]
        ^ data_i[60]
        ^ data_i[62]
        ;
    assign syndrome[1] = check_i[1]
        ^ data_i[0]
        ^ data_i[3]
        ^ data_i[5]
        ^ data_i[8]
        ^ data_i[10]
        ^ data_i[13]
        ^ data_i[16]
        ^ data_i[19]
        ^ data_i[22]
        ^ data_i[24]
        ^ data_i[26]
        ^ data_i[30]
        ^ data_i[32]
        ^ data_i[35]
        ^ data_i[38]
        ^ data_i[40]
        ^ data_i[43]
        ^ data_i[46]
        ^ data_i[48]
        ^ data_i[50]
        ^ data_i[53]
        ^ data_i[56]
        ^ data_i[57]
        ^ data_i[59]
        ^ data_i[61]
        ^ data_i[62]
        ;
    assign syndrome[2] = check_i[2]
        ^ data_i[0]
        ^ data_i[3]
        ^ data_i[6]
        ^ data_i[9]
        ^ data_i[11]
        ^ data_i[14]
        ^ data_i[17]
        ^ data_i[19]
        ^ data_i[21]
        ^ data_i[24]
        ^ data_i[27]
        ^ data_i[29]
        ^ data_i[33]
        ^ data_i[34]
        ^ data_i[38]
        ^ data_i[40]
        ^ data_i[44]
        ^ data_i[45]
        ^ data_i[49]
        ^ data_i[52]
        ^ data_i[55]
        ^ data_i[56]
        ^ data_i[58]
        ^ data_i[59]
        ^ data_i[61]
        ^ data_i[62]
        ;
    assign syndrome[3] = check_i[3]
        ^ data_i[1]
        ^ data_i[3]
        ^ data_i[6]
        ^ data_i[8]
        ^ data_i[11]
        ^ data_i[14]
        ^ data_i[17]
        ^ data_i[20]
        ^ data_i[22]
        ^ data_i[25]
        ^ data_i[28]
        ^ data_i[30]
        ^ data_i[32]
        ^ data_i[36]
        ^ data_i[37]
        ^ data_i[41]
        ^ data_i[43]
        ^ data_i[47]
        ^ data_i[49]
        ^ data_i[51]
        ^ data_i[54]
        ^ data_i[56]
        ^ data_i[58]
        ^ data_i[59]
        ^ data_i[61]
        ^ data_i[63]
        ;
    assign syndrome[4] = check_i[4]
        ^ data_i[1]
        ^ data_i[4]
        ^ data_i[6]
        ^ data_i[9]
        ^ data_i[12]
        ^ data_i[15]
        ^ data_i[16]
        ^ data_i[19]
        ^ data_i[22]
        ^ data_i[25]
        ^ data_i[27]
        ^ data_i[31]
        ^ data_i[33]
        ^ data_i[36]
        ^ data_i[39]
        ^ data_i[42]
        ^ data_i[44]
        ^ data_i[46]
        ^ data_i[48]
        ^ data_i[51]
        ^ data_i[53]
        ^ data_i[56]
        ^ data_i[58]
        ^ data_i[60]
        ^ data_i[61]
        ^ data_i[63]
        ;
    assign syndrome[5] = check_i[5]
        ^ data_i[1]
        ^ data_i[4]
        ^ data_i[7]
        ^ data_i[9]
        ^ data_i[12]
        ^ data_i[14]
        ^ data_i[18]
        ^ data_i[20]
        ^ data_i[23]
        ^ data_i[26]
        ^ data_i[28]
        ^ data_i[30]
        ^ data_i[34]
        ^ data_i[35]
        ^ data_i[38]
        ^ data_i[42]
        ^ data_i[45]
        ^ data_i[46]
        ^ data_i[50]
        ^ data_i[52]
        ^ data_i[54]
        ^ data_i[57]
        ^ data_i[58]
        ^ data_i[60]
        ^ data_i[61]
        ^ data_i[63]
        ;
    assign syndrome[6] = check_i[6]
        ^ data_i[2]
        ^ data_i[4]
        ^ data_i[7]
        ^ data_i[10]
        ^ data_i[13]
        ^ data_i[15]
        ^ data_i[17]
        ^ data_i[20]
        ^ data_i[23]
        ^ data_i[25]
        ^ data_i[29]
        ^ data_i[31]
        ^ data_i[33]
        ^ data_i[37]
        ^ data_i[40]
        ^ data_i[41]
        ^ data_i[43]
        ^ data_i[48]
        ^ data_i[50]
        ^ data_i[52]
        ^ data_i[55]
        ^ data_i[57]
        ^ data_i[58]
        ^ data_i[60]
        ^ data_i[62]
        ^ data_i[63]
        ;
    assign syndrome[7] = check_i[7]
        ^ data_i[2]
        ^ data_i[5]
        ^ data_i[7]
        ^ data_i[10]
        ^ data_i[12]
        ^ data_i[15]
        ^ data_i[18]
        ^ data_i[21]
        ^ data_i[24]
        ^ data_i[26]
        ^ data_i[28]
        ^ data_i[32]
        ^ data_i[34]
        ^ data_i[36]
        ^ data_i[39]
        ^ data_i[41]
        ^ data_i[44]
        ^ data_i[47]
        ^ data_i[49]
        ^ data_i[53]
        ^ data_i[55]
        ^ data_i[57]
        ^ data_i[59]
        ^ data_i[60]
        ^ data_i[62]
        ^ data_i[63]
        ;

    assign syndrome_o = syndrome;

    wire syndrome_nz  = |syndrome;
    wire syndrome_odd = ^syndrome;
    // Hsiao: odd syndrome parity == single-bit (correctable) error.
    assign ce_o = syndrome_nz &  syndrome_odd & ~poison_i;
    assign ue_o = (syndrome_nz & ~syndrome_odd) | poison_i;
    assign poison_o = poison_i | (syndrome_nz & ~syndrome_odd);

    wire [63:0] correct;
    assign correct[0] = (syndrome == 8'd7);
    assign correct[1] = (syndrome == 8'd56);
    assign correct[2] = (syndrome == 8'd193);
    assign correct[3] = (syndrome == 8'd14);
    assign correct[4] = (syndrome == 8'd112);
    assign correct[5] = (syndrome == 8'd131);
    assign correct[6] = (syndrome == 8'd28);
    assign correct[7] = (syndrome == 8'd224);
    assign correct[8] = (syndrome == 8'd11);
    assign correct[9] = (syndrome == 8'd52);
    assign correct[10] = (syndrome == 8'd194);
    assign correct[11] = (syndrome == 8'd13);
    assign correct[12] = (syndrome == 8'd176);
    assign correct[13] = (syndrome == 8'd67);
    assign correct[14] = (syndrome == 8'd44);
    assign correct[15] = (syndrome == 8'd208);
    assign correct[16] = (syndrome == 8'd19);
    assign correct[17] = (syndrome == 8'd76);
    assign correct[18] = (syndrome == 8'd161);
    assign correct[19] = (syndrome == 8'd22);
    assign correct[20] = (syndrome == 8'd104);
    assign correct[21] = (syndrome == 8'd133);
    assign correct[22] = (syndrome == 8'd26);
    assign correct[23] = (syndrome == 8'd97);
    assign correct[24] = (syndrome == 8'd134);
    assign correct[25] = (syndrome == 8'd88);
    assign correct[26] = (syndrome == 8'd162);
    assign correct[27] = (syndrome == 8'd21);
    assign correct[28] = (syndrome == 8'd168);
    assign correct[29] = (syndrome == 8'd69);
    assign correct[30] = (syndrome == 8'd42);
    assign correct[31] = (syndrome == 8'd81);
    assign correct[32] = (syndrome == 8'd138);
    assign correct[33] = (syndrome == 8'd84);
    assign correct[34] = (syndrome == 8'd164);
    assign correct[35] = (syndrome == 8'd35);
    assign correct[36] = (syndrome == 8'd152);
    assign correct[37] = (syndrome == 8'd73);
    assign correct[38] = (syndrome == 8'd38);
    assign correct[39] = (syndrome == 8'd145);
    assign correct[40] = (syndrome == 8'd70);
    assign correct[41] = (syndrome == 8'd200);
    assign correct[42] = (syndrome == 8'd49);
    assign correct[43] = (syndrome == 8'd74);
    assign correct[44] = (syndrome == 8'd148);
    assign correct[45] = (syndrome == 8'd37);
    assign correct[46] = (syndrome == 8'd50);
    assign correct[47] = (syndrome == 8'd137);
    assign correct[48] = (syndrome == 8'd82);
    assign correct[49] = (syndrome == 8'd140);
    assign correct[50] = (syndrome == 8'd98);
    assign correct[51] = (syndrome == 8'd25);
    assign correct[52] = (syndrome == 8'd100);
    assign correct[53] = (syndrome == 8'd146);
    assign correct[54] = (syndrome == 8'd41);
    assign correct[55] = (syndrome == 8'd196);
    assign correct[56] = (syndrome == 8'd31);
    assign correct[57] = (syndrome == 8'd227);
    assign correct[58] = (syndrome == 8'd124);
    assign correct[59] = (syndrome == 8'd143);
    assign correct[60] = (syndrome == 8'd241);
    assign correct[61] = (syndrome == 8'd62);
    assign correct[62] = (syndrome == 8'd199);
    assign correct[63] = (syndrome == 8'd248);

    // A syndrome equal to a unit vector points at a check bit, not data.
    assign ce_in_check_o = ce_o & ((syndrome == 8'd1) | (syndrome == 8'd2) | (syndrome == 8'd4) | (syndrome == 8'd8) | (syndrome == 8'd16) | (syndrome == 8'd32) | (syndrome == 8'd64) | (syndrome == 8'd128));

    assign data_o = data_i ^ (correct & {64{ce_o}});

endmodule

// ---------------------------------------------------------------------------
// Pipelined split of the same code: vc3d_secded_syn_64 computes the
// syndrome (stage 1) and vc3d_secded_cor_64 applies the correction
// (stage 2) from a REGISTERED syndrome.  Splitting the decoder is what lets
// the ECC sit in a 3 GHz pipeline: the XOR tree and the 1-of-N correction
// compare are each about half of the combinational decoder.
// ---------------------------------------------------------------------------
module vc3d_secded_syn_64 (
    input  wire [63:0] data_i,
    input  wire [7:0] check_i,
    output wire [7:0] syndrome_o
);

    assign syndrome_o[0] = check_i[0]
        ^ data_i[0]
        ^ data_i[2]
        ^ data_i[5]
        ^ data_i[8]
        ^ data_i[11]
        ^ data_i[13]
        ^ data_i[16]
        ^ data_i[18]
        ^ data_i[21]
        ^ data_i[23]
        ^ data_i[27]
        ^ data_i[29]
        ^ data_i[31]
        ^ data_i[35]
        ^ data_i[37]
        ^ data_i[39]
        ^ data_i[42]
        ^ data_i[45]
        ^ data_i[47]
        ^ data_i[51]
        ^ data_i[54]
        ^ data_i[56]
        ^ data_i[57]
        ^ data_i[59]
        ^ data_i[60]
        ^ data_i[62]
        ;
    assign syndrome_o[1] = check_i[1]
        ^ data_i[0]
        ^ data_i[3]
        ^ data_i[5]
        ^ data_i[8]
        ^ data_i[10]
        ^ data_i[13]
        ^ data_i[16]
        ^ data_i[19]
        ^ data_i[22]
        ^ data_i[24]
        ^ data_i[26]
        ^ data_i[30]
        ^ data_i[32]
        ^ data_i[35]
        ^ data_i[38]
        ^ data_i[40]
        ^ data_i[43]
        ^ data_i[46]
        ^ data_i[48]
        ^ data_i[50]
        ^ data_i[53]
        ^ data_i[56]
        ^ data_i[57]
        ^ data_i[59]
        ^ data_i[61]
        ^ data_i[62]
        ;
    assign syndrome_o[2] = check_i[2]
        ^ data_i[0]
        ^ data_i[3]
        ^ data_i[6]
        ^ data_i[9]
        ^ data_i[11]
        ^ data_i[14]
        ^ data_i[17]
        ^ data_i[19]
        ^ data_i[21]
        ^ data_i[24]
        ^ data_i[27]
        ^ data_i[29]
        ^ data_i[33]
        ^ data_i[34]
        ^ data_i[38]
        ^ data_i[40]
        ^ data_i[44]
        ^ data_i[45]
        ^ data_i[49]
        ^ data_i[52]
        ^ data_i[55]
        ^ data_i[56]
        ^ data_i[58]
        ^ data_i[59]
        ^ data_i[61]
        ^ data_i[62]
        ;
    assign syndrome_o[3] = check_i[3]
        ^ data_i[1]
        ^ data_i[3]
        ^ data_i[6]
        ^ data_i[8]
        ^ data_i[11]
        ^ data_i[14]
        ^ data_i[17]
        ^ data_i[20]
        ^ data_i[22]
        ^ data_i[25]
        ^ data_i[28]
        ^ data_i[30]
        ^ data_i[32]
        ^ data_i[36]
        ^ data_i[37]
        ^ data_i[41]
        ^ data_i[43]
        ^ data_i[47]
        ^ data_i[49]
        ^ data_i[51]
        ^ data_i[54]
        ^ data_i[56]
        ^ data_i[58]
        ^ data_i[59]
        ^ data_i[61]
        ^ data_i[63]
        ;
    assign syndrome_o[4] = check_i[4]
        ^ data_i[1]
        ^ data_i[4]
        ^ data_i[6]
        ^ data_i[9]
        ^ data_i[12]
        ^ data_i[15]
        ^ data_i[16]
        ^ data_i[19]
        ^ data_i[22]
        ^ data_i[25]
        ^ data_i[27]
        ^ data_i[31]
        ^ data_i[33]
        ^ data_i[36]
        ^ data_i[39]
        ^ data_i[42]
        ^ data_i[44]
        ^ data_i[46]
        ^ data_i[48]
        ^ data_i[51]
        ^ data_i[53]
        ^ data_i[56]
        ^ data_i[58]
        ^ data_i[60]
        ^ data_i[61]
        ^ data_i[63]
        ;
    assign syndrome_o[5] = check_i[5]
        ^ data_i[1]
        ^ data_i[4]
        ^ data_i[7]
        ^ data_i[9]
        ^ data_i[12]
        ^ data_i[14]
        ^ data_i[18]
        ^ data_i[20]
        ^ data_i[23]
        ^ data_i[26]
        ^ data_i[28]
        ^ data_i[30]
        ^ data_i[34]
        ^ data_i[35]
        ^ data_i[38]
        ^ data_i[42]
        ^ data_i[45]
        ^ data_i[46]
        ^ data_i[50]
        ^ data_i[52]
        ^ data_i[54]
        ^ data_i[57]
        ^ data_i[58]
        ^ data_i[60]
        ^ data_i[61]
        ^ data_i[63]
        ;
    assign syndrome_o[6] = check_i[6]
        ^ data_i[2]
        ^ data_i[4]
        ^ data_i[7]
        ^ data_i[10]
        ^ data_i[13]
        ^ data_i[15]
        ^ data_i[17]
        ^ data_i[20]
        ^ data_i[23]
        ^ data_i[25]
        ^ data_i[29]
        ^ data_i[31]
        ^ data_i[33]
        ^ data_i[37]
        ^ data_i[40]
        ^ data_i[41]
        ^ data_i[43]
        ^ data_i[48]
        ^ data_i[50]
        ^ data_i[52]
        ^ data_i[55]
        ^ data_i[57]
        ^ data_i[58]
        ^ data_i[60]
        ^ data_i[62]
        ^ data_i[63]
        ;
    assign syndrome_o[7] = check_i[7]
        ^ data_i[2]
        ^ data_i[5]
        ^ data_i[7]
        ^ data_i[10]
        ^ data_i[12]
        ^ data_i[15]
        ^ data_i[18]
        ^ data_i[21]
        ^ data_i[24]
        ^ data_i[26]
        ^ data_i[28]
        ^ data_i[32]
        ^ data_i[34]
        ^ data_i[36]
        ^ data_i[39]
        ^ data_i[41]
        ^ data_i[44]
        ^ data_i[47]
        ^ data_i[49]
        ^ data_i[53]
        ^ data_i[55]
        ^ data_i[57]
        ^ data_i[59]
        ^ data_i[60]
        ^ data_i[62]
        ^ data_i[63]
        ;

endmodule

module vc3d_secded_cor_64 (
    input  wire [63:0] data_i,      // registered, same beat as syndrome
    input  wire [7:0] syndrome_i,
    input  wire poison_i,
    output wire [63:0] data_o,
    output wire ce_o,
    output wire ue_o,
    output wire poison_o
);

    wire syndrome_nz  = |syndrome_i;
    wire syndrome_odd = ^syndrome_i;
    assign ce_o     = syndrome_nz &  syndrome_odd & ~poison_i;
    assign ue_o     = (syndrome_nz & ~syndrome_odd) | poison_i;
    assign poison_o = poison_i | (syndrome_nz & ~syndrome_odd);

    wire [63:0] correct;
    assign correct[0] = (syndrome_i == 8'd7);
    assign correct[1] = (syndrome_i == 8'd56);
    assign correct[2] = (syndrome_i == 8'd193);
    assign correct[3] = (syndrome_i == 8'd14);
    assign correct[4] = (syndrome_i == 8'd112);
    assign correct[5] = (syndrome_i == 8'd131);
    assign correct[6] = (syndrome_i == 8'd28);
    assign correct[7] = (syndrome_i == 8'd224);
    assign correct[8] = (syndrome_i == 8'd11);
    assign correct[9] = (syndrome_i == 8'd52);
    assign correct[10] = (syndrome_i == 8'd194);
    assign correct[11] = (syndrome_i == 8'd13);
    assign correct[12] = (syndrome_i == 8'd176);
    assign correct[13] = (syndrome_i == 8'd67);
    assign correct[14] = (syndrome_i == 8'd44);
    assign correct[15] = (syndrome_i == 8'd208);
    assign correct[16] = (syndrome_i == 8'd19);
    assign correct[17] = (syndrome_i == 8'd76);
    assign correct[18] = (syndrome_i == 8'd161);
    assign correct[19] = (syndrome_i == 8'd22);
    assign correct[20] = (syndrome_i == 8'd104);
    assign correct[21] = (syndrome_i == 8'd133);
    assign correct[22] = (syndrome_i == 8'd26);
    assign correct[23] = (syndrome_i == 8'd97);
    assign correct[24] = (syndrome_i == 8'd134);
    assign correct[25] = (syndrome_i == 8'd88);
    assign correct[26] = (syndrome_i == 8'd162);
    assign correct[27] = (syndrome_i == 8'd21);
    assign correct[28] = (syndrome_i == 8'd168);
    assign correct[29] = (syndrome_i == 8'd69);
    assign correct[30] = (syndrome_i == 8'd42);
    assign correct[31] = (syndrome_i == 8'd81);
    assign correct[32] = (syndrome_i == 8'd138);
    assign correct[33] = (syndrome_i == 8'd84);
    assign correct[34] = (syndrome_i == 8'd164);
    assign correct[35] = (syndrome_i == 8'd35);
    assign correct[36] = (syndrome_i == 8'd152);
    assign correct[37] = (syndrome_i == 8'd73);
    assign correct[38] = (syndrome_i == 8'd38);
    assign correct[39] = (syndrome_i == 8'd145);
    assign correct[40] = (syndrome_i == 8'd70);
    assign correct[41] = (syndrome_i == 8'd200);
    assign correct[42] = (syndrome_i == 8'd49);
    assign correct[43] = (syndrome_i == 8'd74);
    assign correct[44] = (syndrome_i == 8'd148);
    assign correct[45] = (syndrome_i == 8'd37);
    assign correct[46] = (syndrome_i == 8'd50);
    assign correct[47] = (syndrome_i == 8'd137);
    assign correct[48] = (syndrome_i == 8'd82);
    assign correct[49] = (syndrome_i == 8'd140);
    assign correct[50] = (syndrome_i == 8'd98);
    assign correct[51] = (syndrome_i == 8'd25);
    assign correct[52] = (syndrome_i == 8'd100);
    assign correct[53] = (syndrome_i == 8'd146);
    assign correct[54] = (syndrome_i == 8'd41);
    assign correct[55] = (syndrome_i == 8'd196);
    assign correct[56] = (syndrome_i == 8'd31);
    assign correct[57] = (syndrome_i == 8'd227);
    assign correct[58] = (syndrome_i == 8'd124);
    assign correct[59] = (syndrome_i == 8'd143);
    assign correct[60] = (syndrome_i == 8'd241);
    assign correct[61] = (syndrome_i == 8'd62);
    assign correct[62] = (syndrome_i == 8'd199);
    assign correct[63] = (syndrome_i == 8'd248);

    assign data_o = data_i ^ (correct & {64{ce_o}});

endmodule

