// VCACHE-3D testbenches (needs filelist_base.f too)
// GENERATED by gen/vc3d_gen_filelists.py -- do not edit.
+incdir+include
+incdir+tb
tb/tb_vc3d_96mib.sv
tb/tb_vc3d_ecc.sv
tb/tb_vc3d_repair.sv
tb/tb_vc3d_slice.sv
tb/tb_vc3d_stack_bond.sv
