# =============================================================================
# VCACHE-3D -- OpenROAD-flow-scripts configuration (3D / two-tier flow)
#
#   make -C pd/openroad base    : build the base-die tier
#   make -C pd/openroad cache   : build the cache-dielet tier
#   make -C pd/openroad bond    : check the bond-pad alignment between tiers
#   make -C pd/openroad all
#
# The two tiers are separate physical implementations that share ONE bond-pad
# coordinate file (package/bond_pad_map.csv).  That file is generated by
# pd/package/gen_bump_map.py and consumed by both floorplans, which is what
# guarantees the pads actually line up when the dies are bonded face to face.
# =============================================================================

export DESIGN_NICKNAME  = vcache3d
export PLATFORM         ?= asap7

# ---- tier selection ---------------------------------------------------------
TIER ?= base

ifeq ($(TIER),base)
  export DESIGN_NAME    = vc3d_l3_96mib_top
  export VERILOG_FILES  = $(shell cat ../../filelist_base.f)
  export SDC_FILE       = ../sdc/vc3d_base.sdc
  export CORE_UTILIZATION = 55
  export PLACE_DENSITY    = 0.62
  export DIE_AREA         = 0 0 5200 4600
  export CORE_AREA        = 20 20 5180 4580
  export ADDITIONAL_SCRIPT = ../scripts/floorplan_base.tcl
endif

ifeq ($(TIER),cache)
  export DESIGN_NAME    = vc3d_stack_die_top
  export VERILOG_FILES  = $(shell cat ../../filelist_cache.f)
  export SDC_FILE       = ../sdc/vc3d_cache.sdc
  export CORE_UTILIZATION = 82
  export PLACE_DENSITY    = 0.88
  export DIE_AREA         = 0 0 4900 4800
  export CORE_AREA        = 10 10 4890 4790
  export ADDITIONAL_SCRIPT = ../scripts/floorplan_cache.tcl
endif

# ---- clocks -----------------------------------------------------------------
export CLOCK_PORT       = clk
export CLOCK_NET        = clk
export CLOCK_PERIOD     = 0.333        # 3.0 GHz base tier
export ARRAY_CLOCK_PERIOD = 0.500      # 2.0 GHz cache tier

# ---- macros -----------------------------------------------------------------
export MACRO_PLACE_HALO   = 4 4
export MACRO_PLACE_CHANNEL = 12 12
export MACRO_BLOCKAGE_HALO = 4

# ---- power ------------------------------------------------------------------
export PWR_NETS_VOLTAGES  = VDD 0.95 VDD_ARRAY 0.75 VDD_RET 0.55
export GND_NETS_VOLTAGES  = VSS 0.0
export PDN_TCL            = ../scripts/pdn_$(TIER).tcl

# ---- signoff ----------------------------------------------------------------
export SETUP_SLACK_MARGIN = 0.010
export HOLD_SLACK_MARGIN  = 0.005
export TNS_END_PERCENT    = 100
export REMOVE_ABC_BUFFERS = 1
