#!/usr/bin/env python3
"""Generate the deliberately fully-expanded CHI telemetry fabric.

The checked-in RTL is the build artifact.  Keeping this deterministic generator
next to it makes review/reproduction practical while retaining the explicitly
unrolled gates/registers requested for synthesis and physical-design analysis.
"""
from pathlib import Path

LANES = 256
OUT = Path(__file__).resolve().parents[1] / "_noc" / "misc" / "chi_ultra_telemetry_fabric.v"


def p(s=""):
    lines.append(s)


lines = []
p("// AUTO-GENERATED by tools/generate_chi_ultra_telemetry.py; DO NOT HAND EDIT.")
p("// Fully expanded 256-lane CHI transaction telemetry, watchdog, and QoS fabric.")
p("`timescale 1ns/1ps")
p("module chi_ultra_telemetry_fabric #(")
p("    parameter TIMESTAMP_WIDTH = 48,")
p("    parameter TIMEOUT_CYCLES = 4096")
p(") (")
p("    input wire clk,")
p("    input wire rst_n,")
p("    input wire clear_counters,")
p(f"    input wire [{LANES-1}:0] req_valid,")
p(f"    input wire [{LANES-1}:0] req_ready,")
p(f"    input wire [{LANES*8-1}:0] req_opcode,")
p(f"    input wire [{LANES*4-1}:0] req_qos,")
p(f"    input wire [{LANES-1}:0] rsp_valid,")
p(f"    input wire [{LANES-1}:0] rsp_ready,")
p(f"    input wire [{LANES*3-1}:0] rsp_code,")
p(f"    input wire [{LANES-1}:0] dat_valid,")
p(f"    input wire [{LANES-1}:0] dat_ready,")
p(f"    input wire [{LANES*6-1}:0] dat_bytes,")
p(f"    output wire [{LANES-1}:0] lane_active,")
p(f"    output wire [{LANES-1}:0] lane_timeout,")
p(f"    output wire [{LANES-1}:0] lane_protocol_error,")
p(f"    output wire [{LANES*32-1}:0] lane_request_count,")
p(f"    output wire [{LANES*32-1}:0] lane_response_count,")
p(f"    output wire [{LANES*32-1}:0] lane_stall_cycles,")
p(f"    output wire [{LANES*32-1}:0] lane_average_latency,")
p("    output wire [63:0] total_requests,")
p("    output wire [63:0] total_responses,")
p("    output wire [63:0] total_data_bytes,")
p("    output wire [31:0] aggregate_error_count,")
p("    output wire any_timeout,")
p("    output wire any_protocol_error")
p(");")
p("")
p("reg [TIMESTAMP_WIDTH-1:0] global_timestamp;")
p("always @(posedge clk or negedge rst_n) begin")
p("    if (!rst_n) global_timestamp <= {TIMESTAMP_WIDTH{1'b0}};")
p("    else global_timestamp <= global_timestamp + {{(TIMESTAMP_WIDTH-1){1'b0}}, 1'b1};")
p("end")
p("")

for i in range(LANES):
    rb=i*8; qb=i*4; sb=i*3; db=i*6
    p(f"// -------------------------------------------------------------------------")
    p(f"// Lane {i:03d}: explicitly instantiated protocol accounting pipeline")
    p(f"// -------------------------------------------------------------------------")
    p(f"wire lane_{i}_req_fire = req_valid[{i}] & req_ready[{i}];")
    p(f"wire lane_{i}_rsp_fire = rsp_valid[{i}] & rsp_ready[{i}];")
    p(f"wire lane_{i}_dat_fire = dat_valid[{i}] & dat_ready[{i}];")
    p(f"wire [7:0] lane_{i}_opcode = req_opcode[{rb} +: 8];")
    p(f"wire [3:0] lane_{i}_qos = req_qos[{qb} +: 4];")
    p(f"wire [2:0] lane_{i}_rsp_code = rsp_code[{sb} +: 3];")
    p(f"wire [5:0] lane_{i}_dat_bytes = dat_bytes[{db} +: 6];")
    for decl in [
        "reg active", "reg timeout", "reg protocol_error", "reg [TIMESTAMP_WIDTH-1:0] start_time",
        "reg [31:0] request_count", "reg [31:0] response_count", "reg [31:0] data_flit_count",
        "reg [63:0] data_byte_count", "reg [31:0] stall_cycles", "reg [31:0] latency_sum",
        "reg [31:0] average_latency", "reg [31:0] maximum_latency", "reg [31:0] minimum_latency",
        "reg [31:0] outstanding_highwater", "reg [7:0] outstanding", "reg [31:0] error_count",
        "reg [31:0] timeout_count", "reg [31:0] retry_count", "reg [31:0] qos_accumulator",
        "reg [31:0] ewma_latency", "reg [31:0] hist_0_7", "reg [31:0] hist_8_15",
        "reg [31:0] hist_16_31", "reg [31:0] hist_32_63", "reg [31:0] hist_64_127",
        "reg [31:0] hist_128_255", "reg [31:0] hist_256_1023", "reg [31:0] hist_1024_plus",
        "reg [31:0] read_requests", "reg [31:0] write_requests", "reg [31:0] atomic_requests",
        "reg [31:0] maintenance_requests", "reg [31:0] backpressure_events"
    ]:
        declaration_type, signal_name = decl.rsplit(" ", 1)
        p(f"{declaration_type} lane_{i}_{signal_name};")
    p(f"wire [TIMESTAMP_WIDTH-1:0] lane_{i}_age = global_timestamp - lane_{i}_start_time;")
    p(f"wire [31:0] lane_{i}_latency32 = lane_{i}_age[31:0];")
    p(f"always @(posedge clk or negedge rst_n) begin")
    p(f"    if (!rst_n) begin")
    reset_names = ["active","timeout","protocol_error","start_time","request_count","response_count","data_flit_count","data_byte_count","stall_cycles","latency_sum","average_latency","maximum_latency","outstanding_highwater","outstanding","error_count","timeout_count","retry_count","qos_accumulator","ewma_latency","hist_0_7","hist_8_15","hist_16_31","hist_32_63","hist_64_127","hist_128_255","hist_256_1023","hist_1024_plus","read_requests","write_requests","atomic_requests","maintenance_requests","backpressure_events"]
    for n in reset_names: p(f"        lane_{i}_{n} <= 0;")
    p(f"        lane_{i}_minimum_latency <= 32'hffffffff;")
    p(f"    end else if (clear_counters) begin")
    for n in reset_names:
        if n in ("active","start_time","outstanding"): continue
        p(f"        lane_{i}_{n} <= 0;")
    p(f"        lane_{i}_minimum_latency <= 32'hffffffff;")
    p(f"    end else begin")
    p(f"        if (req_valid[{i}] & ~req_ready[{i}]) lane_{i}_stall_cycles <= lane_{i}_stall_cycles + 1'b1;")
    p(f"        if (req_valid[{i}] & ~req_ready[{i}] & (lane_{i}_stall_cycles == 0)) lane_{i}_backpressure_events <= lane_{i}_backpressure_events + 1'b1;")
    p(f"        if (lane_{i}_req_fire) begin")
    p(f"            lane_{i}_request_count <= lane_{i}_request_count + 1'b1;")
    p(f"            lane_{i}_qos_accumulator <= lane_{i}_qos_accumulator + lane_{i}_qos;")
    p(f"            lane_{i}_outstanding <= lane_{i}_outstanding + 1'b1;")
    p(f"            if (lane_{i}_outstanding + 1'b1 > lane_{i}_outstanding_highwater) lane_{i}_outstanding_highwater <= lane_{i}_outstanding + 1'b1;")
    p(f"            if (!lane_{i}_active) begin lane_{i}_active <= 1'b1; lane_{i}_start_time <= global_timestamp; end")
    p(f"            case (lane_{i}_opcode[7:6])")
    p(f"                2'b00: lane_{i}_read_requests <= lane_{i}_read_requests + 1'b1;")
    p(f"                2'b01: lane_{i}_write_requests <= lane_{i}_write_requests + 1'b1;")
    p(f"                2'b10: lane_{i}_atomic_requests <= lane_{i}_atomic_requests + 1'b1;")
    p(f"                2'b11: lane_{i}_maintenance_requests <= lane_{i}_maintenance_requests + 1'b1;")
    p(f"            endcase")
    p(f"        end")
    p(f"        if (lane_{i}_rsp_fire) begin")
    p(f"            lane_{i}_response_count <= lane_{i}_response_count + 1'b1;")
    p(f"            if (lane_{i}_outstanding != 0) lane_{i}_outstanding <= lane_{i}_outstanding - 1'b1;")
    p(f"            else begin lane_{i}_protocol_error <= 1'b1; lane_{i}_error_count <= lane_{i}_error_count + 1'b1; end")
    p(f"            if (lane_{i}_rsp_code == 3'b010) lane_{i}_retry_count <= lane_{i}_retry_count + 1'b1;")
    p(f"            lane_{i}_latency_sum <= lane_{i}_latency_sum + lane_{i}_latency32;")
    p(f"            lane_{i}_average_latency <= (lane_{i}_average_latency == 0) ? lane_{i}_latency32 : ((lane_{i}_average_latency * 7) + lane_{i}_latency32) >> 3;")
    p(f"            lane_{i}_ewma_latency <= (lane_{i}_ewma_latency == 0) ? lane_{i}_latency32 : lane_{i}_ewma_latency - (lane_{i}_ewma_latency >> 4) + (lane_{i}_latency32 >> 4);")
    p(f"            if (lane_{i}_latency32 > lane_{i}_maximum_latency) lane_{i}_maximum_latency <= lane_{i}_latency32;")
    p(f"            if (lane_{i}_latency32 < lane_{i}_minimum_latency) lane_{i}_minimum_latency <= lane_{i}_latency32;")
    p(f"            if (lane_{i}_latency32 < 8) lane_{i}_hist_0_7 <= lane_{i}_hist_0_7 + 1'b1;")
    p(f"            else if (lane_{i}_latency32 < 16) lane_{i}_hist_8_15 <= lane_{i}_hist_8_15 + 1'b1;")
    p(f"            else if (lane_{i}_latency32 < 32) lane_{i}_hist_16_31 <= lane_{i}_hist_16_31 + 1'b1;")
    p(f"            else if (lane_{i}_latency32 < 64) lane_{i}_hist_32_63 <= lane_{i}_hist_32_63 + 1'b1;")
    p(f"            else if (lane_{i}_latency32 < 128) lane_{i}_hist_64_127 <= lane_{i}_hist_64_127 + 1'b1;")
    p(f"            else if (lane_{i}_latency32 < 256) lane_{i}_hist_128_255 <= lane_{i}_hist_128_255 + 1'b1;")
    p(f"            else if (lane_{i}_latency32 < 1024) lane_{i}_hist_256_1023 <= lane_{i}_hist_256_1023 + 1'b1;")
    p(f"            else lane_{i}_hist_1024_plus <= lane_{i}_hist_1024_plus + 1'b1;")
    p(f"            if (lane_{i}_outstanding <= 1) lane_{i}_active <= 1'b0;")
    p(f"            else lane_{i}_start_time <= global_timestamp;")
    p(f"        end")
    p(f"        if (lane_{i}_dat_fire) begin")
    p(f"            lane_{i}_data_flit_count <= lane_{i}_data_flit_count + 1'b1;")
    p(f"            lane_{i}_data_byte_count <= lane_{i}_data_byte_count + lane_{i}_dat_bytes;")
    p(f"        end")
    p(f"        if (lane_{i}_active && lane_{i}_age >= TIMEOUT_CYCLES) begin")
    p(f"            if (!lane_{i}_timeout) lane_{i}_timeout_count <= lane_{i}_timeout_count + 1'b1;")
    p(f"            lane_{i}_timeout <= 1'b1;")
    p(f"        end")
    p(f"    end")
    p(f"end")
    p(f"assign lane_active[{i}] = lane_{i}_active;")
    p(f"assign lane_timeout[{i}] = lane_{i}_timeout;")
    p(f"assign lane_protocol_error[{i}] = lane_{i}_protocol_error;")
    p(f"assign lane_request_count[{i*32} +: 32] = lane_{i}_request_count;")
    p(f"assign lane_response_count[{i*32} +: 32] = lane_{i}_response_count;")
    p(f"assign lane_stall_cycles[{i*32} +: 32] = lane_{i}_stall_cycles;")
    p(f"assign lane_average_latency[{i*32} +: 32] = lane_{i}_average_latency;")
    p("")

# Explicit balanced reduction trees: synthesis sees deterministic fan-in.
for metric, width, source in [("req",64,"request_count"),("rsp",64,"response_count"),("bytes",64,"data_byte_count"),("errors",32,"error_count")]:
    current=[]
    for i in range(LANES):
        name=f"reduce_{metric}_l0_{i}"
        p(f"wire [{width-1}:0] {name} = lane_{i}_{source};")
        current.append(name)
    level=1
    while len(current)>1:
        nxt=[]
        for j in range(0,len(current),2):
            name=f"reduce_{metric}_l{level}_{j//2}"
            p(f"wire [{width-1}:0] {name} = {current[j]} + {current[j+1]};")
            nxt.append(name)
        current=nxt; level+=1
    out={"req":"total_requests","rsp":"total_responses","bytes":"total_data_bytes","errors":"aggregate_error_count"}[metric]
    p(f"assign {out} = {current[0]};")
    p("")

p("assign any_timeout = |lane_timeout;")
p("assign any_protocol_error = |lane_protocol_error;")
p("endmodule")
p("")
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(lines))
print(f"generated {OUT} ({len(lines):,} lines)")
